// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x83670A31, "StatEventScoreScaler")]
    public class StatEventScoreScaler : STUInstance {
        [STUFieldAttribute(0x7759B5C3)]
        public Enum_D7506F80 m_7759B5C3;

        [STUFieldAttribute(0xCCA3AC7F)]
        public float m_CCA3AC7F;

        [STUFieldAttribute(0x2AA06473)]
        public byte m_2AA06473;
    }
}
