// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA913E038)]
    public class STU_A913E038 : STUInstance {
        [STUFieldAttribute(0x4EA50E53)]
        public byte m_4EA50E53;

        [STUFieldAttribute(0xEE2FBA55)]
        public byte m_EE2FBA55;

        [STUFieldAttribute(0x3164E07F)]
        public byte m_3164E07F;

        [STUFieldAttribute(0xE58120EF)]
        public byte m_E58120EF;

        [STUFieldAttribute(0x148507D4)]
        public byte m_148507D4;
    }
}
