// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC37E44D7)]
    public class STU_C37E44D7 : STU_09FB0449 {
        [STUFieldAttribute(0x79501B77, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_79501B77;

        [STUFieldAttribute(0x5ED70D3C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5ED70D3C;

        [STUFieldAttribute(0x3E3CCF0C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3E3CCF0C;
    }
}
