// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x80ED48C9)]
    public class STU_80ED48C9 : STUGenericSettings_Base {
        [STUFieldAttribute(0x7FCD7E24, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUStatescriptGraphWithOverrides[] m_7FCD7E24;

        [STUFieldAttribute(0x56F194D4)]
        public float m_56F194D4;

        [STUFieldAttribute(0x8572D9A1)]
        public float m_8572D9A1;

        [STUFieldAttribute(0x1D372905)]
        public float m_1D372905;

        [STUFieldAttribute(0x4B7E4BCD)]
        public float m_4B7E4BCD;

        [STUFieldAttribute(0xD695D6C3)]
        public float m_D695D6C3;

        [STUFieldAttribute(0x5DC34718)]
        public float m_5DC34718;

        [STUFieldAttribute(0x8F70F086)]
        public float m_8F70F086;

        [STUFieldAttribute(0xDA537969)]
        public float m_DA537969;

        [STUFieldAttribute(0xEB09495B)]
        public uint m_EB09495B;

        [STUFieldAttribute(0xAF819F2C)]
        public float m_AF819F2C;

        [STUFieldAttribute(0x72DF1828)]
        public float m_72DF1828;

        [STUFieldAttribute(0x9B2F805A)]
        public float m_9B2F805A;

        [STUFieldAttribute(0x3C6A59F6)]
        public float m_3C6A59F6;
    }
}
