// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA7EB909A)]
    public class STU_A7EB909A : STUStatescriptActionMovementModOp {
        [STUFieldAttribute(0x5C703862, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5C703862;

        [STUFieldAttribute(0xA8A3E0F7)]
        public Enum_0BBA0C7B m_A8A3E0F7;
    }
}
