// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4BBFD4C5)]
    public class STU_4BBFD4C5 : STUConfigVarStringBase {
        [STUFieldAttribute(0x526640D9, "m_teamIndex", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_teamIndex;
    }
}
