// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x138CCAB0)]
    public class STU_138CCAB0 : STUStatescriptBase {
        [STUFieldAttribute(0xC77035BE)]
        public int[] m_C77035BE;

        [STUFieldAttribute(0x59C48F73, "m_inPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptInputPlug m_inPlug;

        [STUFieldAttribute(0x460C9ED6, "m_outPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_outPlug;

        [STUFieldAttribute(0x5E756553)]
        public int m_5E756553;
    }
}
