// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB5A03445)]
    public class STU_B5A03445 : STU_3F7D2DCF {
        [STUFieldAttribute(0xFBB95E89)]
        public Enum_3121BB9D m_FBB95E89;
    }
}
