// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x27B5F23B)]
    public class STU_27B5F23B : STU_2679D4F3 {
        [STUFieldAttribute(0xEF646D9F, "m_state", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_91A2B8D8 m_state;
    }
}
