// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x05E0DD02)]
    public class STU_05E0DD02 : STU_9D2A65BE {
        [STUFieldAttribute(0xADDF889C, "m_voiceStimulus", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_D72A8DCC m_voiceStimulus;
    }
}
