// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC2B6CE4B)]
    public class STU_C2B6CE4B : STUStatescriptWeaponProjectileMotion {
        [STUFieldAttribute(0x005269EE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_005269EE;
    }
}
