// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5046363D)]
    public class STU_5046363D : STUStatescriptAction {
        [STUFieldAttribute(0x124470E3, "m_effects", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_41CB5614[] m_effects;
    }
}
