// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x91DBD6E2)]
    public class STU_91DBD6E2 : STU_3F7D2DCF {
        [STUFieldAttribute(0xFBB95E89)]
        public Enum_99DE76A5 m_FBB95E89;

        [STUFieldAttribute(0x189C1A4D)]
        public Enum_99DE76A5 m_189C1A4D;
    }
}
