// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x07A74D6E)]
    public class STU_07A74D6E : STU_988BCA34 {
        [STUFieldAttribute(0xFF5B84E3)]
        public teStructuredDataAssetRef<STUAnimation> m_FF5B84E3;

        [STUFieldAttribute(0xB3DF3F56)]
        public teStructuredDataAssetRef<STUAnimation> m_B3DF3F56;

        [STUFieldAttribute(0x6D6151A4)]
        public teStructuredDataAssetRef<STUAnimation> m_6D6151A4;

        [STUFieldAttribute(0x240DE6DE)]
        public teStructuredDataAssetRef<STUAnimation> m_240DE6DE;

        [STUFieldAttribute(0x920D3DB8)]
        public teStructuredDataAssetRef<STUAnimation> m_920D3DB8;

        [STUFieldAttribute(0xD0D9538F)]
        public teStructuredDataAssetRef<STUAnimation> m_D0D9538F;

        [STUFieldAttribute(0x61B44CF0)]
        public teStructuredDataAssetRef<STUAnimation> m_61B44CF0;

        [STUFieldAttribute(0xD7B49796)]
        public teStructuredDataAssetRef<STUAnimation> m_D7B49796;

        [STUFieldAttribute(0x9ED820EC)]
        public teStructuredDataAssetRef<STUAnimation> m_9ED820EC;

        [STUFieldAttribute(0x425D4221)]
        public teStructuredDataAssetRef<STUAnimation> m_425D4221;

        [STUFieldAttribute(0x9F2A57F0)]
        public teStructuredDataAssetRef<STUAnimation> m_9F2A57F0;

        [STUFieldAttribute(0x52F8A211)]
        public teStructuredDataAssetRef<STUAnimation> m_52F8A211;

        [STUFieldAttribute(0x08F88E78)]
        public teStructuredDataAssetRef<STUAnimation> m_08F88E78;

        [STUFieldAttribute(0xAD94CE0D)]
        public teStructuredDataAssetRef<STUAnimation> m_AD94CE0D;

        [STUFieldAttribute(0xFC2C3B29)]
        public teStructuredDataAssetRef<STUAnimation> m_FC2C3B29;

        [STUFieldAttribute(0x5E2DBF45)]
        public teStructuredDataAssetRef<STUAnimation> m_5E2DBF45;

        [STUFieldAttribute(0xFB41FF30)]
        public teStructuredDataAssetRef<STUAnimation> m_FB41FF30;

        [STUFieldAttribute(0xA141D359)]
        public teStructuredDataAssetRef<STUAnimation> m_A141D359;

        [STUFieldAttribute(0x54161545, "m_globalWeightMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalWeightMultipliers m_globalWeightMultipliers;

        [STUFieldAttribute(0xE57007D5, "m_userWeights", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimUserWeights m_userWeights;

        [STUFieldAttribute(0x94166C37, "m_globalLayerMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalLayerMultipliers m_globalLayerMultipliers;

        [STUFieldAttribute(0xB8BB0D9C)]
        public float m_B8BB0D9C;

        [STUFieldAttribute(0x78067117)]
        public float m_78067117;

        [STUFieldAttribute(0xF3A05E34)]
        public float m_F3A05E34;

        [STUFieldAttribute(0x46507DD1)]
        public float m_46507DD1;

        [STUFieldAttribute(0xCF87A9F9)]
        public float m_CF87A9F9;

        [STUFieldAttribute(0x9A702D02)]
        public float m_9A702D02;
    }
}
