// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x05C955DA)]
    public class STU_05C955DA : STU_90C195E7 {
        [STUFieldAttribute(0x94DF8DB3, "m_input", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_input;
    }
}
