// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE1524276)]
    public class STU_E1524276 : STUConfigVarBoolBase {
    }
}
