// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x2501A4DB)]
    public class STU_2501A4DB : STUStatescriptAction {
        [STUFieldAttribute(0x7E13BAA9, "m_buckets")]
        public teStructuredDataAssetRef<STUIdentifier>[] m_buckets;

        [STUFieldAttribute(0x4F00BDD2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4F00BDD2;

        [STUFieldAttribute(0x604ABCE2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_604ABCE2;

        [STUFieldAttribute(0x510E6F9B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_510E6F9B;

        [STUFieldAttribute(0x8C7E1F1F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8C7E1F1F;

        [STUFieldAttribute(0x0A32AFA1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0A32AFA1;

        [STUFieldAttribute(0xEDDC4B9C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EDDC4B9C;

        [STUFieldAttribute(0x4418C132, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4418C132;
    }
}
