// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8647E7BC)]
    public class STU_8647E7BC : STU_D5EE5EA3 {
        [STUFieldAttribute(0xC79A0A34, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5198605D m_C79A0A34;

        [STUFieldAttribute(0x8DF62AC4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_8DF62AC4;

        [STUFieldAttribute(0x14FF7B7E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_14FF7B7E;

        [STUFieldAttribute(0x63F84BE8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_63F84BE8;

        [STUFieldAttribute(0xB9114C96, "m_default", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_default;
    }
}
