// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD9B504B6)]
    public class STU_D9B504B6 : STUInstance {
        [STUFieldAttribute(0x84DAE6B4)]
        public teStructuredDataAssetRef<ulong> m_84DAE6B4;

        [STUFieldAttribute(0xC63A2084)]
        public teStructuredDataAssetRef<ulong> m_C63A2084;

        [STUFieldAttribute(0xB7ADD87F)]
        public teStructuredDataAssetRef<ulong> m_B7ADD87F;

        [STUFieldAttribute(0x1EC3FE1F)]
        public teStructuredDataAssetRef<ulong> m_1EC3FE1F;

        [STUFieldAttribute(0x36DCFA9D)]
        public teStructuredDataAssetRef<ulong> m_36DCFA9D;

        [STUFieldAttribute(0xF3DD2BEF)]
        public teStructuredDataAssetRef<ulong> m_F3DD2BEF;
    }
}
