// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x112C0773)]
    public class STU_112C0773 : STU_988BCA34 {
        [STUFieldAttribute(0x428B8F34, "m_idle")]
        public teStructuredDataAssetRef<STUAnimation> m_idle;

        [STUFieldAttribute(0xC836E575)]
        public teStructuredDataAssetRef<STUAnimation> m_C836E575;

        [STUFieldAttribute(0xF7C9B5A3)]
        public teStructuredDataAssetRef<STUAnimation> m_F7C9B5A3;

        [STUFieldAttribute(0x5BE677EB)]
        public float m_5BE677EB;

        [STUFieldAttribute(0x6DD2D7A0)]
        public byte m_6DD2D7A0;
    }
}
