// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3399FB2E)]
    public class STU_3399FB2E : STUInstance {
        [STUFieldAttribute(0x44BB1696, "m_entity")]
        public teStructuredDataAssetRef<STUEntityDefinition> m_entity;

        [STUFieldAttribute(0x9B62CDBD, "m_model")]
        public teStructuredDataAssetRef<STUModel> m_model;

        [STUFieldAttribute(0xB595EE23, "m_look")]
        public teStructuredDataAssetRef<STUModelLook> m_look;

        [STUFieldAttribute(0xDA37BCF8, "m_hardPoint")]
        public teStructuredDataAssetRef<STUHardPoint> m_hardPoint;
    }
}
