// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3DF41D8F)]
    public class STU_3DF41D8F : STU_82972D9D {
        [STUFieldAttribute(0x93F49971, "m_raycastType")]
        public teStructuredDataAssetRef<STURaycastType> m_raycastType;
    }
}
