// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB370E625)]
    public class STU_B370E625 : STUInstance {
        [STUFieldAttribute(0x47F2FEDE, "m_flags")]
        public ushort m_flags;
    }
}
