// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4776F396)]
    public class STU_4776F396 : STUCriteria {
        [STUFieldAttribute(0x5E427904, "m_heroAmount")]
        public uint m_heroAmount;

        [STUFieldAttribute(0xD61D7377, "m_level")]
        public uint m_level;
    }
}
