// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xADFC9542)]
    public class STU_ADFC9542 : STUConfigVarBoolBase {
        [STUFieldAttribute(0xFB524C40, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FB524C40;

        [STUFieldAttribute(0x1E7586B7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1E7586B7;

        [STUFieldAttribute(0xDF848896, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_DF848896;
    }
}
