// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5DCC2147)]
    public class STU_5DCC2147 : STUStatescriptState {
        [STUFieldAttribute(0x72D77B4A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_72D77B4A;

        [STUFieldAttribute(0x7D6D7A12, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7D6D7A12;
    }
}
