// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF1201EDA)]
    public class STU_F1201EDA : STUStatescriptAction {
    }
}
