// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBB28634B)]
    public class STU_BB28634B : STUStatescriptState {
        [STUFieldAttribute(0x352D3187, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_352D3187;
    }
}
