// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xDCDF6679)]
    public class STU_DCDF6679 : STUConfigVarEntityID {
    }
}
