// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x1C218E02)]
    public class STU_1C218E02 : STU_42851043 {
        [STUFieldAttribute(0x1B6EE2D3, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_6F5CF35E m_1B6EE2D3;
    }
}
