// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC2BF346D)]
    public class STU_C2BF346D : STU_2CAA4AFB {
        [STUFieldAttribute(0xF072EAAB)]
        public teStructuredDataAssetRef<STUAnimation> m_F072EAAB;
    }
}
