// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8AA57B38)]
    public class STU_8AA57B38 : STU_E4CC91FE {
        [STUFieldAttribute(0x79A27A47)]
        public float m_79A27A47;

        [STUFieldAttribute(0xC92AC8C5)]
        public float m_C92AC8C5;
    }
}
