// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC843E89D)]
    public class STU_C843E89D : STUCriteria {
        [STUFieldAttribute(0xD61D7377, "m_level")]
        public uint m_level;
    }
}
