// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD3EB1B97)]
    public class STU_D3EB1B97 : STUConfigVarNumeric {
        [STUFieldAttribute(0x172F02EF)]
        public Enum_0591572D m_172F02EF;
    }
}
