// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x648F62A7)]
    public class STU_648F62A7 : STUStatescriptState {
        [STUFieldAttribute(0x7C8CE224, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_7426D7EF m_7C8CE224;

        [STUFieldAttribute(0x3B363BCA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_2309C11B m_3B363BCA;

        [STUFieldAttribute(0xD0136EC2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D0136EC2;
    }
}
