// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0676FE02)]
    public class STU_0676FE02 : STU_EE48F03A {
        [STUFieldAttribute(0xF8D55022, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUGraphPlug m_F8D55022;

        [STUFieldAttribute(0x241D6ABA)]
        public byte m_241D6ABA;
    }
}
