// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x26E79CA0)]
    public class STU_26E79CA0 : STUInstance {
        [STUFieldAttribute(0xE75BEDA5, "m_heroGUID")]
        public ulong m_heroGUID;

        [STUFieldAttribute(0x5180E750, "m_value")]
        public float m_value;
    }
}
