// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x06593992)]
    public class STU_06593992 : STUStatescriptState {
        [STUFieldAttribute(0xE59A5847, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E59A5847;

        [STUFieldAttribute(0x4CAED1B7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4CAED1B7;

        [STUFieldAttribute(0xB29B19AF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_B29B19AF;

        [STUFieldAttribute(0x21D206B2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_21D206B2;

        [STUFieldAttribute(0x12716D08, "m_type")]
        public Enum_40EE834B m_type;
    }
}
