// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0D05B4E1)]
    public class STU_0D05B4E1 : STUStatescriptAction {
        [STUFieldAttribute(0xFFD31124)]
        public Enum_361F7C9B m_FFD31124;
    }
}
