// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x99433920)]
    public class STU_99433920 : STUInstance {
        [STUFieldAttribute(0x74CBC83A)]
        public teUUID m_74CBC83A;

        [STUFieldAttribute(0x551C5925)]
        public teStructuredDataAssetRef<STUEmptyAsset> m_551C5925;

        [STUFieldAttribute(0x655700A0)]
        public teStructuredDataAssetRef<STUTexture> m_655700A0;

        [STUFieldAttribute(0x71E4C04E)]
        public teStructuredDataAssetRef<STUEmptyAsset> m_71E4C04E;

        [STUFieldAttribute(0xFD5A351A)]
        public teStructuredDataAssetRef<STUTexture> m_FD5A351A;

        [STUFieldAttribute(0x3073BBAF)]
        public float m_3073BBAF;

        [STUFieldAttribute(0xC1670582)]
        public float m_C1670582;

        [STUFieldAttribute(0x20CBF962)]
        public int m_20CBF962;
    }
}
