// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA02984E1)]
    public class STU_A02984E1 : STU_02D49F9A {
        [STUFieldAttribute(0x409D3F11, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUStatescriptTrackTargetsSortRuleWeight[] m_409D3F11;
    }
}
