// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xDC254019)]
    public class STU_DC254019 : STUConfigVarBoolBase {
    }
}
