// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF5D0E634)]
    public class STU_F5D0E634 : STUConfigVarBoolBase {
    }
}
