// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE1254F43)]
    public class STU_E1254F43 : STUConfigVarVecBase {
        [STUFieldAttribute(0xA9F8B247, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A9F8B247;

        [STUFieldAttribute(0x30F1E3FD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_30F1E3FD;
    }
}
