// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9508B806)]
    public class STU_9508B806 : STUGenericSettings_Base {
        [STUFieldAttribute(0xFA95BC46, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5307099C[] m_FA95BC46;

        [STUFieldAttribute(0x3BEFD759, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5307099C[] m_3BEFD759;

        [STUFieldAttribute(0x9857CC27, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_96D7026C[] m_9857CC27;

        [STUFieldAttribute(0x74143CC5, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_96D7026C[] m_74143CC5;

        [STUFieldAttribute(0x686AE80E)]
        public teStructuredDataAssetRef<STU_53706BC9>[] m_686AE80E;

        [STUFieldAttribute(0xED9D2A09)]
        public teStructuredDataAssetRef<STU_53706BC9>[] m_ED9D2A09;

        [STUFieldAttribute(0xC9688A95)]
        public teStructuredDataAssetRef<STUMap>[] m_C9688A95;

        [STUFieldAttribute(0x2954D5F9)]
        public double m_2954D5F9;

        [STUFieldAttribute(0xCF10ACAE)]
        public double m_CF10ACAE;

        [STUFieldAttribute(0x73811612)]
        public double m_73811612;

        [STUFieldAttribute(0x2DBB5F3A)]
        public int m_2DBB5F3A;

        [STUFieldAttribute(0x78B4C2AB)]
        public float m_78B4C2AB;

        [STUFieldAttribute(0xCCE95334)]
        public float m_CCE95334;
    }
}
