// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF5408971)]
    public class STU_F5408971 : STU_52D8FB50 {
        [STUFieldAttribute(0x5DBEDE02, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_52D8FB50[] m_5DBEDE02;

        [STUFieldAttribute(0x3B0192C1)]
        public Enum_B45767B9 m_3B0192C1;
    }
}
