// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0980BC8D)]
    public class STU_0980BC8D : STUStatescriptState {
        [STUFieldAttribute(0xA4BCD30C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_A4BCD30C;

        [STUFieldAttribute(0xEA271BF8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_EA271BF8;

        [STUFieldAttribute(0x8874925D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_8874925D;

        [STUFieldAttribute(0x1F82ECFB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_1F82ECFB;

        [STUFieldAttribute(0xCEF6E8C1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_CEF6E8C1;

        [STUFieldAttribute(0xE3017A4F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_E3017A4F;

        [STUFieldAttribute(0xA3CAE6B8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_A3CAE6B8;

        [STUFieldAttribute(0xA0B95DB2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_A0B95DB2;

        [STUFieldAttribute(0x69A8210B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_69A8210B;

        [STUFieldAttribute(0xFE36BEF1)]
        public byte m_FE36BEF1;
    }
}
