// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF84FC1E2)]
    public class STU_F84FC1E2 : STUStatescriptState {
        [STUFieldAttribute(0x6D047768, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6D047768;

        [STUFieldAttribute(0x41BA609A, "m_onAbortPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onAbortPlug;

        [STUFieldAttribute(0xFE841C79, "m_onFinishedPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onFinishedPlug;

        [STUFieldAttribute(0x1BFF3867)]
        public byte m_1BFF3867;
    }
}
