// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8A322446)]
    public class STU_8A322446 : STUStatescriptState {
        [STUFieldAttribute(0x93FBE76A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_93FBE76A;

        [STUFieldAttribute(0xD61D7377, "m_level")]
        public Enum_9214D388 m_level;
    }
}
