// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4F205FAF)]
    public class STU_4F205FAF : STUConfigVarEntityID {
    }
}
