// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC8C71BBC)]
    public class STU_C8C71BBC : STU_F1C8D756 {
        [STUFieldAttribute(0x5D14C945, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5D14C945;

        [STUFieldAttribute(0x6E1A2648, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6E1A2648;

        [STUFieldAttribute(0xFE841C79, "m_onFinishedPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onFinishedPlug;
    }
}
