// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xEB91A587)]
    public class STU_EB91A587 : STUAnimNode_AnimBlendTreeProxy {
    }
}
