// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC5384890)]
    public class STU_C5384890 : STUConfigVarEntityID {
        [STUFieldAttribute(0x44BB1696, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;
    }
}
