// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE69588F7)]
    public class STU_E69588F7 : STUConfigVarResource {
        [STUFieldAttribute(0x12716D08, "m_type", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_type;

        [STUFieldAttribute(0x32A11A46, "m_slot", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_slot;

        [STUFieldAttribute(0xCF6154A7, "m_hero", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_hero;
    }
}
