// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5856151F)]
    public class STU_5856151F : STU_FB404714 {
        [STUFieldAttribute(0x02941849)]
        public teStructuredDataAssetRef<STUIdentifier> m_02941849;
    }
}
