// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE67871C5)]
    public class STU_E67871C5 : STU_4A8EEA04 {
        [STUFieldAttribute(0x2B7A937B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2B7A937B;
    }
}
