// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8248EBF8)]
    public class STU_8248EBF8 : STU_2679D4F3 {
        [STUFieldAttribute(0x44233934)]
        public int m_44233934;
    }
}
