// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3226F3A8)]
    public class STU_3226F3A8 : STU_16151658 {
        [STUFieldAttribute(0x547D9847, "m_dataFlow", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_197AA12D m_dataFlow;

        [STUFieldAttribute(0x5180E750, "m_value", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_7059BA29 m_value;

        [STUFieldAttribute(0x6C95EA69)]
        public Enum_2B1F7FBB m_6C95EA69;
    }
}
