// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFCD20366)]
    public class STU_FCD20366 : STUConfigVarNumeric {
        [STUFieldAttribute(0x5A4F9C3E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5A4F9C3E;
    }
}
