// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x37FA4C62)]
    public class STU_37FA4C62 : STUInstance {
        [STUFieldAttribute(0x5BD152E9)]
        public teStructuredDataAssetRef<STUUXDisplayText> m_5BD152E9;

        [STUFieldAttribute(0xE9BA0AB9)]
        public Enum_7B64DB3D m_E9BA0AB9;
    }
}
