// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9B047AFE)]
    public class STU_9B047AFE : STU_054BC7E8 {
        [STUFieldAttribute(0x874DF199)]
        public teStructuredDataAssetRef<STU_53908303> m_874DF199;

        [STUFieldAttribute(0x1468A3D1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1468A3D1;

        [STUFieldAttribute(0xBE2D57CD)]
        public uint m_BE2D57CD;
    }
}
