// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xAF814BC3)]
    public class STU_AF814BC3 : STUGameModeLegacy {
        [STUFieldAttribute(0xCF6154A7, "m_hero")]
        public teStructuredDataAssetRef<STUHero> m_hero;
    }
}
