// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8681ED02)]
    public class STU_8681ED02 : STUConfigVarIterable {
        [STUFieldAttribute(0x65CE2851, "m_configVars", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar[] m_configVars;
    }
}
