// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x518C5BB3)]
    public class STU_518C5BB3 : STUConfigVarVecBase {
        [STUFieldAttribute(0x11792233, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_11792233;

        [STUFieldAttribute(0x4EC37567, "m_previewEntity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_previewEntity;
    }
}
