// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x17FB815B)]
    public class STU_17FB815B : STUStatescriptAction {
    }
}
