// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4A1FB19A)]
    public class STU_4A1FB19A : STUConfigVarBoolBase {
    }
}
