// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0CDC2E1A)]
    public class STU_0CDC2E1A : STUStatescriptAction {
        [STUFieldAttribute(0xCC84D865, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_CC84D865;

        [STUFieldAttribute(0x5D633127, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_5D633127;

        [STUFieldAttribute(0x413F29AE, "m_key", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_key;

        [STUFieldAttribute(0x5180E750, "m_value", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_value;

        [STUFieldAttribute(0xA7E46EA2)]
        public byte m_A7E46EA2;
    }
}
