// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5101DC01)]
    public class STU_5101DC01 : STU_D38527FF {
        [STUFieldAttribute(0x5180E750, "m_value")]
        public float m_value;
    }
}
