// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x6E363AA3)]
    public class STU_6E363AA3 : STU_AF2D57CA {
        [STUFieldAttribute(0x60E81BA5, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_0ACA861C m_60E81BA5;

        [STUFieldAttribute(0x3484F7E6, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_0ACA861C m_3484F7E6;

        [STUFieldAttribute(0xCEDDD08C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_CEDDD08C;

        [STUFieldAttribute(0x36146B41, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_36146B41;
    }
}
