// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x614C3A0A)]
    public class STU_614C3A0A : STUStatescriptState {
        [STUFieldAttribute(0x4976528D, "m_position", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_position;

        [STUFieldAttribute(0x609B720B, "m_direction", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_direction;

        [STUFieldAttribute(0xC0EDFA4B, "m_width", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_width;

        [STUFieldAttribute(0x45561961, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_45561961;

        [STUFieldAttribute(0x92BDAB20, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_92BDAB20;

        [STUFieldAttribute(0xA358340A, "m_castFilter", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarFilter m_castFilter;

        [STUFieldAttribute(0x5556C513, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_8DCB62EA m_5556C513;

        [STUFieldAttribute(0x8CF01B33, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_8CF01B33;

        [STUFieldAttribute(0x3D1F6FBF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_3D1F6FBF;

        [STUFieldAttribute(0x7D5017C9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_7D5017C9;
    }
}
