// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4C2555E3)]
    public class STU_4C2555E3 : STUEffectTemplateState {
    }
}
