// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xECFFF88D)]
    public class STU_ECFFF88D : STUAnimNode_Blend2d {
        [STUFieldAttribute(0x8C6A9ADF, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_CFB183E4 m_8C6A9ADF;
    }
}
