// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA0265CF5)]
    public class STU_A0265CF5 : STUEntityComponent {
        [STUFieldAttribute(0x2084D8E5)]
        public teStructuredDataAssetRef<STU_032D9792> m_2084D8E5;
    }
}
