// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5A5E3AF5)]
    public class STU_5A5E3AF5 : STU_AA172924 {
        [STUFieldAttribute(0xADE95629, "m_items", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimNode_AdjustBoneTransformParams_SetRotationPSItem[] m_items;
    }
}
