// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x34493776)]
    public class STU_34493776 : STUInstance {
        [STUFieldAttribute(0x6FA954AC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_1E89514B[] m_6FA954AC;

        [STUFieldAttribute(0x5566DD37, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_11A55CDD m_5566DD37;

        [STUFieldAttribute(0x6751FF10, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_61A3DBC4 m_6751FF10;

        [STUFieldAttribute(0x14FA858F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_14FA858F;

        [STUFieldAttribute(0x6D746BBE)]
        public Enum_260698A9 m_6D746BBE;
    }
}
