// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5198605D)]
    public class STU_5198605D : STU_269F50CB {
        [STUFieldAttribute(0xDF66931C)]
        public teStructuredDataAssetRef<STUAnimCategory> m_DF66931C;

        [STUFieldAttribute(0x9E945E56)]
        public float m_9E945E56;

        [STUFieldAttribute(0x010D40B2)]
        public byte m_010D40B2;
    }
}
