// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5D93B951)]
    public class STU_5D93B951 : STUConfigVarBoolBase {
        [STUFieldAttribute(0x5E99EFF1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5E99EFF1;
    }
}
