// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x728AC69F)]
    public class STU_728AC69F : STUStatescriptAction {
    }
}
