// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9D2A65BE)]
    public class STU_9D2A65BE : STU_8E6EF5E8 {
        [STUFieldAttribute(0xB5062C21, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_D65889E9 m_B5062C21;

        [STUFieldAttribute(0x6A07F315, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_91DBD6E2 m_6A07F315;

        [STUFieldAttribute(0xD3216864, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_91DBD6E2 m_D3216864;

        [STUFieldAttribute(0xBD6DE678, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_CEDF11E3 m_BD6DE678;

        [STUFieldAttribute(0x5E6FD93F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_CEDF11E3 m_5E6FD93F;

        [STUFieldAttribute(0x60FA495A, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_60FA495A;

        [STUFieldAttribute(0xB9DE2CFC, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_CEDF11E3 m_B9DE2CFC;

        [STUFieldAttribute(0x0BB55995, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_0BB55995;

        [STUFieldAttribute(0x8A7D33E2, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_535EC683 m_8A7D33E2;

        [STUFieldAttribute(0x6AA51974, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_6AA51974;

        [STUFieldAttribute(0xFC64B3D3, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_FC64B3D3;

        [STUFieldAttribute(0x9DEB52B5, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_9DEB52B5;

        [STUFieldAttribute(0x4F7A6F21, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_4F7A6F21;

        [STUFieldAttribute(0x8C9941CB, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_CEDF11E3 m_8C9941CB;

        [STUFieldAttribute(0x3DE81C2F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_CEDF11E3 m_3DE81C2F;

        [STUFieldAttribute(0x51F6D7E4, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_CEDF11E3 m_51F6D7E4;

        [STUFieldAttribute(0x81360032, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_CEDF11E3 m_81360032;

        [STUFieldAttribute(0x376D0923, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_376D0923;

        [STUFieldAttribute(0x4AA991DE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_98F341A5 m_4AA991DE;

        [STUFieldAttribute(0xA561815C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_A561815C;

        [STUFieldAttribute(0xCCE7D70A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_CCE7D70A;

        [STUFieldAttribute(0x946AA91D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_946AA91D;

        [STUFieldAttribute(0x4D4343CE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_4D4343CE;

        [STUFieldAttribute(0xA977A7EE)]
        public float m_A977A7EE;

        [STUFieldAttribute(0x85748AB1)]
        public byte m_85748AB1;
    }
}
