// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x98F63B8A)]
    public class STU_98F63B8A : STU_120840DB {
        [STUFieldAttribute(0xF3C155BA)]
        public teStructuredDataAssetRef<STUTexture> m_F3C155BA;

        [STUFieldAttribute(0x030DD6E3)]
        public teStructuredDataAssetRef<STUTexture> m_030DD6E3;

        [STUFieldAttribute(0x573812F8)]
        public teStructuredDataAssetRef<STUTexture> m_573812F8;

        [STUFieldAttribute(0xFE4C6B33)]
        public teStructuredDataAssetRef<STUTexture> m_FE4C6B33;

        [STUFieldAttribute(0xD372FFB7)]
        public teStructuredDataAssetRef<STUTexture> m_D372FFB7;

        [STUFieldAttribute(0x7A0E41D6)]
        public teStructuredDataAssetRef<STUTexture> m_7A0E41D6;

        [STUFieldAttribute(0xB560CCD6, "m_shader")]
        public teStructuredDataAssetRef<STUEmptyAsset> m_shader;

        [STUFieldAttribute(0x1F945D78)]
        public teStructuredDataAssetRef<STUDataFlow> m_1F945D78;

        [STUFieldAttribute(0x44717256)]
        public teStructuredDataAssetRef<STUTexture> m_44717256;

        [STUFieldAttribute(0x5A43C586)]
        public teStructuredDataAssetRef<STUTexture> m_5A43C586;

        [STUFieldAttribute(0x7A79E1C3)]
        public teStructuredDataAssetRef<STUTexture> m_7A79E1C3;

        [STUFieldAttribute(0xB8CCDDC4)]
        public teStructuredDataAssetRef<STUTexture> m_B8CCDDC4;

        [STUFieldAttribute(0x63C1B5DB)]
        public teColorRGB m_63C1B5DB;

        [STUFieldAttribute(0x0BB774E4)]
        public teColorRGB m_0BB774E4;

        [STUFieldAttribute(0xDDACBE48)]
        public uint m_DDACBE48;

        [STUFieldAttribute(0xEFAF00F6)]
        public uint m_EFAF00F6;

        [STUFieldAttribute(0xCD386949)]
        public float m_CD386949;

        [STUFieldAttribute(0x125D5A2E)]
        public Enum_7A15278C m_125D5A2E;

        [STUFieldAttribute(0x603907A5)]
        public float m_603907A5;

        [STUFieldAttribute(0xBC09D06D)]
        public float m_BC09D06D;

        [STUFieldAttribute(0x8236A193)]
        public uint m_8236A193;

        [STUFieldAttribute(0xB2E6411D)]
        public Enum_27281BCF m_B2E6411D;

        [STUFieldAttribute(0x0B4189D3)]
        public byte m_0B4189D3;

        [STUFieldAttribute(0x05047CEA)]
        public byte m_05047CEA;

        [STUFieldAttribute(0xFC03CA7F)]
        public byte m_FC03CA7F;

        [STUFieldAttribute(0xAD9FAD42)]
        public byte m_AD9FAD42;

        [STUFieldAttribute(0x004BA030)]
        public byte m_004BA030;

        [STUFieldAttribute(0x7A672BFA)]
        public byte m_7A672BFA;

        [STUFieldAttribute(0x9E630F62)]
        public byte m_9E630F62;
    }
}
