// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x120840DB)]
    public class STU_120840DB : STU_DD6A7BCF {
        [STUFieldAttribute(0x7C813033, "m_editorOnly")]
        public byte m_editorOnly;

        [STUFieldAttribute(0x9706DF56)]
        public sbyte m_9706DF56;

        [STUFieldAttribute(0xA0721041)]
        public sbyte m_A0721041;
    }
}
