// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x25DAD842)]
    public class STU_25DAD842 : STUGameModeLegacy {
    }
}
