// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4D0854D0)]
    public class STU_4D0854D0 : STU_7010A7BE {
        [STUFieldAttribute(0x8EE62DEE)]
        public teVec3 m_8EE62DEE;
    }
}
