// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD689BFE4)]
    public class STU_D689BFE4 : STU_988BCA34 {
        [STUFieldAttribute(0xE120561A)]
        public teStructuredDataAssetRef<STUAnimation> m_E120561A;

        [STUFieldAttribute(0xF718EB97)]
        public teStructuredDataAssetRef<STUAnimation> m_F718EB97;

        [STUFieldAttribute(0xB3E6C71F)]
        public teStructuredDataAssetRef<STUAnimation> m_B3E6C71F;

        [STUFieldAttribute(0x14C56DAD)]
        public teVec2 m_14C56DAD;

        [STUFieldAttribute(0x11506170)]
        public float m_11506170;

        [STUFieldAttribute(0x6A68503B)]
        public float m_6A68503B;

        [STUFieldAttribute(0x72CFCEA3)]
        public float m_72CFCEA3;

        [STUFieldAttribute(0x05C8FE35)]
        public float m_05C8FE35;

        [STUFieldAttribute(0xE1D00983)]
        public float m_E1D00983;

        [STUFieldAttribute(0x96D73915)]
        public float m_96D73915;

        [STUFieldAttribute(0x81D481DE)]
        public float m_81D481DE;

        [STUFieldAttribute(0x51956F34)]
        public float m_51956F34;

        [STUFieldAttribute(0x9505C79D)]
        public float m_9505C79D;

        [STUFieldAttribute(0x0DC67F17)]
        public float m_0DC67F17;

        [STUFieldAttribute(0x9017556A)]
        public float m_9017556A;

        [STUFieldAttribute(0x648F5E0F)]
        public byte m_648F5E0F;
    }
}
