// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC1429428)]
    public class STU_C1429428 : STU_529F45C0 {
        [STUFieldAttribute(0xD120D20C, "m_input1", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_input1;

        [STUFieldAttribute(0x482983B6, "m_input2", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_input2;
    }
}
