// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x2E07AD4E)]
    public class STU_2E07AD4E : STU_AF2D57CA {
        [STUFieldAttribute(0x43F71807, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_43F71807;
    }
}
