// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3BE5172E)]
    public class STU_3BE5172E : STUStatescriptAction {
        [STUFieldAttribute(0xEEFEEC53, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EEFEEC53;

        [STUFieldAttribute(0x0AB6F7CD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0AB6F7CD;
    }
}
