// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x66B2E95F)]
    public class STU_66B2E95F : STU_D5EE5EA3 {
        [STUFieldAttribute(0xC79A0A34, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_AC3C92D6 m_C79A0A34;
    }
}
