// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xAC5A427C)]
    public class STU_AC5A427C : STUEntityComponent {
        [STUFieldAttribute(0x1D36DE6D)]
        public teStructuredDataAssetRef<ulong> m_1D36DE6D;

        [STUFieldAttribute(0x86785DCB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_78C3B9AA[] m_86785DCB;
    }
}
