// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x650EE232)]
    public class STU_650EE232 : STUStatescriptAction {
        [STUFieldAttribute(0xC1769D54, "m_displayText", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_displayText;
    }
}
