// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xCEBE779E)]
    public class STU_CEBE779E : STUInstance {
        [STUFieldAttribute(0xF21D13AC)]
        public teStructuredDataAssetRef<STUUXViewModelSchema> m_F21D13AC;

        [STUFieldAttribute(0x84A8AAA6)]
        public teString m_84A8AAA6;

        [STUFieldAttribute(0xDB80F546, "m_propertyKey")]
        public uint m_propertyKey;
    }
}
