// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC2D0763A)]
    public class STU_C2D0763A : STU_988BCA34 {
        [STUFieldAttribute(0xC58A1D2B, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimCurve m_C58A1D2B;

        [STUFieldAttribute(0x7D932DE7, "m_runN")]
        public teStructuredDataAssetRef<STUAnimation> m_runN;

        [STUFieldAttribute(0xD1C99EAC, "m_runNE")]
        public teStructuredDataAssetRef<STUAnimation> m_runNE;

        [STUFieldAttribute(0xEA41F46F, "m_runE")]
        public teStructuredDataAssetRef<STUAnimation> m_runE;

        [STUFieldAttribute(0x2EA5F2B0, "m_runSE")]
        public teStructuredDataAssetRef<STUAnimation> m_runSE;

        [STUFieldAttribute(0x1E95413E, "m_runS")]
        public teStructuredDataAssetRef<STUAnimation> m_runS;

        [STUFieldAttribute(0xDD1C83F8, "m_runSW")]
        public teStructuredDataAssetRef<STUAnimation> m_runSW;

        [STUFieldAttribute(0x19F88527, "m_runW")]
        public teStructuredDataAssetRef<STUAnimation> m_runW;

        [STUFieldAttribute(0x2270EFE4, "m_runNW")]
        public teStructuredDataAssetRef<STUAnimation> m_runNW;

        [STUFieldAttribute(0x8148F905, "m_runAimAdditiveN")]
        public teStructuredDataAssetRef<STUAnimation> m_runAimAdditiveN;

        [STUFieldAttribute(0x9F31C62C, "m_runAimAdditiveNE")]
        public teStructuredDataAssetRef<STUAnimation> m_runAimAdditiveNE;

        [STUFieldAttribute(0x169A208D, "m_runAimAdditiveE")]
        public teStructuredDataAssetRef<STUAnimation> m_runAimAdditiveE;

        [STUFieldAttribute(0x605DAA30, "m_runAimAdditiveSE")]
        public teStructuredDataAssetRef<STUAnimation> m_runAimAdditiveSE;

        [STUFieldAttribute(0xE24E95DC, "m_runAimAdditiveS")]
        public teStructuredDataAssetRef<STUAnimation> m_runAimAdditiveS;

        [STUFieldAttribute(0x93E4DB78, "m_runAimAdditiveSW")]
        public teStructuredDataAssetRef<STUAnimation> m_runAimAdditiveSW;

        [STUFieldAttribute(0xE52351C5, "m_runAimAdditiveW")]
        public teStructuredDataAssetRef<STUAnimation> m_runAimAdditiveW;

        [STUFieldAttribute(0x6C88B764, "m_runAimAdditiveNW")]
        public teStructuredDataAssetRef<STUAnimation> m_runAimAdditiveNW;

        [STUFieldAttribute(0x588D9E77)]
        public teStructuredDataAssetRef<STUAnimIdentifier> m_588D9E77;

        [STUFieldAttribute(0x21E3135B)]
        public teStructuredDataAssetRef<STUAnimIdentifier> m_21E3135B;

        [STUFieldAttribute(0xCF5F47FF)]
        public teStructuredDataAssetRef<STUAnimIdentifier> m_CF5F47FF;

        [STUFieldAttribute(0xDE8F7F47)]
        public teStructuredDataAssetRef<STUAnimIdentifier> m_DE8F7F47;

        [STUFieldAttribute(0x3B8BF2AE)]
        public teStructuredDataAssetRef<STUAnimIdentifier> m_3B8BF2AE;

        [STUFieldAttribute(0x2D360E0F)]
        public teStructuredDataAssetRef<STUAnimIdentifier> m_2D360E0F;

        [STUFieldAttribute(0x3CE636B7)]
        public teStructuredDataAssetRef<STUAnimIdentifier> m_3CE636B7;

        [STUFieldAttribute(0xD25A6213)]
        public teStructuredDataAssetRef<STUAnimIdentifier> m_D25A6213;

        [STUFieldAttribute(0x12852FC3)]
        public teStructuredDataAssetRef<STUDataFlow> m_12852FC3;

        [STUFieldAttribute(0x5AE83B80)]
        public teStructuredDataAssetRef<STUAnimBoneWeightMask> m_5AE83B80;

        [STUFieldAttribute(0x54161545, "m_globalWeightMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalWeightMultipliers m_globalWeightMultipliers;

        [STUFieldAttribute(0xE57007D5, "m_userWeights", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimUserWeights m_userWeights;

        [STUFieldAttribute(0x94166C37, "m_globalLayerMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalLayerMultipliers m_globalLayerMultipliers;

        [STUFieldAttribute(0xC4AF87AF, "m_runSpeedN")]
        public float m_runSpeedN;

        [STUFieldAttribute(0xA9776BA4, "m_runSpeedNE")]
        public float m_runSpeedNE;

        [STUFieldAttribute(0x537D5E27, "m_runSpeedE")]
        public float m_runSpeedE;

        [STUFieldAttribute(0x561B07B8, "m_runSpeedSE")]
        public float m_runSpeedSE;

        [STUFieldAttribute(0xA7A9EB76, "m_runSpeedS")]
        public float m_runSpeedS;

        [STUFieldAttribute(0xA5A276F0, "m_runSpeedSW")]
        public float m_runSpeedSW;

        [STUFieldAttribute(0xA0C42F6F, "m_runSpeedW")]
        public float m_runSpeedW;

        [STUFieldAttribute(0x5ACE1AEC, "m_runSpeedNW")]
        public float m_runSpeedNW;

        [STUFieldAttribute(0x1B81FBF4)]
        public float m_1B81FBF4;

        [STUFieldAttribute(0x3829B6AE)]
        public float m_3829B6AE;

        [STUFieldAttribute(0x8C6A9ADF)]
        public byte m_8C6A9ADF;
    }
}
