// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xCC7B6828)]
    public class STU_CC7B6828 : STUStatescriptAction {
        [STUFieldAttribute(0xC55D5C0D, "m_params", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A51F99C5[] m_params;

        [STUFieldAttribute(0x5FBCE770, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_5FBCE770;

        [STUFieldAttribute(0x5612D5C4, "m_script", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_script;

        [STUFieldAttribute(0x5178F207, "m_gameMessage", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_gameMessage;

        [STUFieldAttribute(0x53E84AEF)]
        public Enum_728E2AED m_53E84AEF;
    }
}
