// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBAE88C4E)]
    public class STU_BAE88C4E : STUStatescriptState {
        [STUFieldAttribute(0xEF7FD201)]
        public teStructuredDataAssetRef<STUUXLink> m_EF7FD201;

        [STUFieldAttribute(0x5CBE813F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_24AB1F0B m_5CBE813F;

        [STUFieldAttribute(0x1C6696A5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1C6696A5;

        [STUFieldAttribute(0x4594C65E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4594C65E;

        [STUFieldAttribute(0xD9CBCA19, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D9CBCA19;

        [STUFieldAttribute(0xBD7A212D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BD7A212D;

        [STUFieldAttribute(0x257E385C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_257E385C;
    }
}
