// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x1139A327)]
    public class STU_1139A327 : STU_D5EE5EA3 {
        [STUFieldAttribute(0xC79A0A34, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_373AE577 m_C79A0A34;

        [STUFieldAttribute(0xB9114C96, "m_default", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_default;
    }
}
