// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE9FA3240)]
    public class STU_E9FA3240 : STUConfigVarResource {
        [STUFieldAttribute(0x580228BC, "m_map", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_map;

        [STUFieldAttribute(0x5A4F9C3E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5A4F9C3E;
    }
}
