// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x010391EA)]
    public class STU_010391EA : STUStatescriptAction {
        [STUFieldAttribute(0xDBFEC0F3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_FE37D416 m_DBFEC0F3;

        [STUFieldAttribute(0xD891AA3F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D891AA3F;

        [STUFieldAttribute(0x8881E00D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_8881E00D;
    }
}
