// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xCD216DEA)]
    public class STU_CD216DEA : STUConfigVarIntBase {
    }
}
