// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x14258EB1)]
    public class STU_14258EB1 : STU_82972D9D {
        [STUFieldAttribute(0xBAB19D43)]
        public teStructuredDataAssetRef<STU_8FB4DAC5> m_BAB19D43;
    }
}
