// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD33D6329)]
    public class STU_D33D6329 : STUConfigVarNumeric {
        [STUFieldAttribute(0xC53BF4D1)]
        public Enum_5ABF4830 m_C53BF4D1;
    }
}
