// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x265F48EB)]
    public class STU_265F48EB : STUStatescriptState {
        [STUFieldAttribute(0xFE1FC848, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FE1FC848;

        [STUFieldAttribute(0x9CD6523F, "m_skin", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_skin;

        [STUFieldAttribute(0xF295D0CF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F295D0CF;

        [STUFieldAttribute(0x2077E211, "m_unlock", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_unlock;

        [STUFieldAttribute(0x41BA609A, "m_onAbortPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onAbortPlug;

        [STUFieldAttribute(0xFE841C79, "m_onFinishedPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onFinishedPlug;

        [STUFieldAttribute(0x5013ED30, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_5013ED30;
    }
}
