// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xAEA182DC)]
    public class STU_AEA182DC : STUStatescriptAction {
    }
}
