// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xEC502A81)]
    public class STU_EC502A81 : STUConfigVarExpression {
    }
}
