// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9E114049)]
    public class STU_9E114049 : STU_1359915D {
        [STUFieldAttribute(0x20623CAB, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimBlendTimeParams m_20623CAB;

        [STUFieldAttribute(0x9A702D02, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimOverrideBlendTime m_9A702D02;

        [STUFieldAttribute(0xC98FA74D, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimOverrideBlendTime m_C98FA74D;

        [STUFieldAttribute(0x1172CDED, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimOverrideBlendTime m_1172CDED;

        [STUFieldAttribute(0xC75FDDF2, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_7059BA29 m_C75FDDF2;

        [STUFieldAttribute(0x9A90E6DC, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_7059BA29 m_9A90E6DC;

        [STUFieldAttribute(0x17F60F1B)]
        public short[] m_17F60F1B;

        [STUFieldAttribute(0x810753DD)]
        public short[] m_810753DD;

        [STUFieldAttribute(0x2A4BF788, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_16151658 m_2A4BF788;

        [STUFieldAttribute(0xE2931663, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_F0900F0C m_E2931663;

        [STUFieldAttribute(0x2129032A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_16151658 m_2129032A;
    }
}
