// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF910F2BE)]
    public class STU_F910F2BE : STU_AF2D57CA {
        [STUFieldAttribute(0x3C58DEF7, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_3C58DEF7;

        [STUFieldAttribute(0x49076F14, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_49076F14;

        [STUFieldAttribute(0x8EECC7D1, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_8EECC7D1;

        [STUFieldAttribute(0x2AA1F78D, "m_color", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_color;

        [STUFieldAttribute(0x2FE0F3E8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_2FE0F3E8;

        [STUFieldAttribute(0x490D86E2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_490D86E2;

        [STUFieldAttribute(0xFCA57CD2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_FCA57CD2;
    }
}
