// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0866127F)]
    public class STU_0866127F : STUMaterialDataFlow {
        [STUFieldAttribute(0x547D9847, "m_dataFlow")]
        public teStructuredDataAssetRef<STUDataFlow> m_dataFlow;
    }
}
