// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5C12D7D9)]
    public class STU_5C12D7D9 : STU_5A844B17 {
        [STUFieldAttribute(0x5180E750, "m_value")]
        public teStructuredDataAssetRef<STUAnimSynchGroup> m_value;
    }
}
