// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x37F3F062)]
    public class STU_37F3F062 : STUInstance {
        [STUFieldAttribute(0xE549FAC7)]
        public teMtx43A m_E549FAC7;

        [STUFieldAttribute(0x9A6C6487)]
        public teVec3A m_9A6C6487;

        [STUFieldAttribute(0xD04D2067)]
        public float[] m_D04D2067;

        [STUFieldAttribute(0xDD7BF655)]
        public teQuat[] m_DD7BF655;

        [STUFieldAttribute(0x362AE05D)]
        public teVec3A[] m_362AE05D;

        [STUFieldAttribute(0x3C2FABB0, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUDataFlowStream_Float[] m_3C2FABB0;

        [STUFieldAttribute(0xC9755D7E, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUDataFlowStream_Guid[] m_C9755D7E;

        [STUFieldAttribute(0x0DBDF638)]
        public ulong m_0DBDF638;

        [STUFieldAttribute(0xC2C4606D)]
        public ulong m_C2C4606D;

        [STUFieldAttribute(0x01ADCC62, "m_weaponGuid")]
        public ulong m_weaponGuid;

        [STUFieldAttribute(0xFF4E5A67, "m_animBlendTreeSetGUID")]
        public ulong m_animBlendTreeSetGUID;

        [STUFieldAttribute(0xC04FCA63)]
        public ulong m_C04FCA63;

        [STUFieldAttribute(0x36EE42DD)]
        public byte m_36EE42DD;
    }
}
