// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x6BA643E0)]
    public class STU_6BA643E0 : STUConfigVarBoolBase {
    }
}
