// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4B5D2F3F)]
    public class STU_4B5D2F3F : STUConfigVarNumeric {
        [STUFieldAttribute(0xF26A2FC7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F26A2FC7;
    }
}
