// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x85136F31)]
    public class STU_85136F31 : STUInstance {
        [STUFieldAttribute(0x00E64F84, "m_areaID")]
        public teUUID m_areaID;

        [STUFieldAttribute(0x6DFC6A5F, "m_priority")]
        public short m_priority;
    }
}
