// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x47D36F63)]
    public class STU_47D36F63 : STUConfigVarBoolBase {
    }
}
