// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x97772070)]
    public class STU_97772070 : STUStatescriptAction {
    }
}
