// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA3C0D79C)]
    public class STU_A3C0D79C : STU_6EE4C0FE {
        [STUFieldAttribute(0x319CC53B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_319CC53B;
    }
}
