// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD50895BE)]
    public class STU_D50895BE : STUStatescriptWeaponVolleyLaunch {
        [STUFieldAttribute(0xEE107893, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUStatescriptWeaponVolleyShotgunRing[] m_EE107893;

        [STUFieldAttribute(0x3626F286, "m_spread", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_spread;

        [STUFieldAttribute(0xD738B2E8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D738B2E8;

        [STUFieldAttribute(0x29B1B16A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_29B1B16A;
    }
}
