// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB10424C3)]
    public class STU_B10424C3 : STU_120840DB {
        [STUFieldAttribute(0xF3C155BA)]
        public teStructuredDataAssetRef<STUTexture> m_F3C155BA;

        [STUFieldAttribute(0x573812F8)]
        public teStructuredDataAssetRef<STUTexture> m_573812F8;

        [STUFieldAttribute(0xFE4C6B33)]
        public teStructuredDataAssetRef<STUTexture> m_FE4C6B33;

        [STUFieldAttribute(0xD372FFB7)]
        public teStructuredDataAssetRef<STUTexture> m_D372FFB7;

        [STUFieldAttribute(0x030DD6E3)]
        public teStructuredDataAssetRef<STUTexture> m_030DD6E3;

        [STUFieldAttribute(0x8C422367)]
        public teStructuredDataAssetRef<STUTexture> m_8C422367;

        [STUFieldAttribute(0x8781157E)]
        public teStructuredDataAssetRef<STUTexture> m_8781157E;

        [STUFieldAttribute(0xBC20EED9)]
        public teStructuredDataAssetRef<STUTexture> m_BC20EED9;

        [STUFieldAttribute(0xB4519547)]
        public teStructuredDataAssetRef<STUTexture> m_B4519547;

        [STUFieldAttribute(0xB560CCD6, "m_shader")]
        public teStructuredDataAssetRef<STUEmptyAsset> m_shader;

        [STUFieldAttribute(0xF286A267)]
        public teVec2 m_F286A267;

        [STUFieldAttribute(0x03DBDB77)]
        public teVec2 m_03DBDB77;

        [STUFieldAttribute(0x765F85DD)]
        public teVec2 m_765F85DD;

        [STUFieldAttribute(0x8702FCCD)]
        public teVec2 m_8702FCCD;

        [STUFieldAttribute(0x70D5340F)]
        public float m_70D5340F;

        [STUFieldAttribute(0x125D5A2E)]
        public Enum_060C77D8 m_125D5A2E;

        [STUFieldAttribute(0x82515A1C)]
        public byte m_82515A1C;

        [STUFieldAttribute(0xF1BCD74A)]
        public byte m_F1BCD74A;

        [STUFieldAttribute(0x03C2E0AB)]
        public byte m_03C2E0AB;

        [STUFieldAttribute(0x31AA1DCB)]
        public byte m_31AA1DCB;
    }
}
