// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC6366130)]
    public class STU_C6366130 : STUStatescriptState {
        [STUFieldAttribute(0x9866CBBC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9866CBBC;

        [STUFieldAttribute(0xFA1237B2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FA1237B2;

        [STUFieldAttribute(0x44BB1696, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;

        [STUFieldAttribute(0x1399982E, "m_offset", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_offset;

        [STUFieldAttribute(0xDA37BCF8, "m_hardPoint", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_hardPoint;

        [STUFieldAttribute(0x792C04D2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_792C04D2;
    }
}
