// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFB5F9460)]
    public class STU_FB5F9460 : STUStatescriptAction {
        [STUFieldAttribute(0x66D96F5C)]
        public byte m_66D96F5C;
    }
}
