// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x79C1D9A5)]
    public class STU_79C1D9A5 : STU_988BCA34 {
        [STUFieldAttribute(0xA7EC997E)]
        public teStructuredDataAssetRef<STUAnimation> m_A7EC997E;

        [STUFieldAttribute(0xAFB4BC40)]
        public teStructuredDataAssetRef<STUAnimation> m_AFB4BC40;

        [STUFieldAttribute(0x1641F9E5)]
        public teStructuredDataAssetRef<STUDataFlow> m_1641F9E5;

        [STUFieldAttribute(0x26C862BC)]
        public teStructuredDataAssetRef<STUAnimation> m_26C862BC;

        [STUFieldAttribute(0x32C93EF3)]
        public teStructuredDataAssetRef<STUDataFlow> m_32C93EF3;

        [STUFieldAttribute(0x79D573B3)]
        public teStructuredDataAssetRef<STUAnimation> m_79D573B3;

        [STUFieldAttribute(0x25714B90)]
        public teStructuredDataAssetRef<STUDataFlow> m_25714B90;

        [STUFieldAttribute(0xA466AAB7)]
        public float m_A466AAB7;

        [STUFieldAttribute(0xF8B737F2)]
        public float m_F8B737F2;

        [STUFieldAttribute(0xF310D75B)]
        public float m_F310D75B;

        [STUFieldAttribute(0x318C2B60)]
        public float m_318C2B60;

        [STUFieldAttribute(0x809D5B3A)]
        public float m_809D5B3A;

        [STUFieldAttribute(0x241065FC)]
        public float m_241065FC;

        [STUFieldAttribute(0x8326838C)]
        public float m_8326838C;
    }
}
