// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x288540BF)]
    public class STU_288540BF : STUStatescriptStateUXLoading {
    }
}
