// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x973DF238)]
    public class STU_973DF238 : STUStatescriptState {
        [STUFieldAttribute(0x5EDFA332, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5EDFA332;

        [STUFieldAttribute(0xA2ABD155, "m_sourceEntity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_sourceEntity;

        [STUFieldAttribute(0x87089166, "m_targetEntity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_targetEntity;

        [STUFieldAttribute(0x49592351, "m_targetHardpoint", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_targetHardpoint;

        [STUFieldAttribute(0x1B4AF499, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1B4AF499;

        [STUFieldAttribute(0xEEA00369, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EEA00369;

        [STUFieldAttribute(0xA019E487, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_A019E487;

        [STUFieldAttribute(0x58AFEF2F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_58AFEF2F;

        [STUFieldAttribute(0x9675EE8A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_9675EE8A;

        [STUFieldAttribute(0x91C740BC)]
        public Enum_30C9D075 m_91C740BC;
    }
}
