// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA7E10128)]
    public class STU_A7E10128 : STU_BB5480D2 {
        [STUFieldAttribute(0x94462148, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_FA29D97E m_94462148;
    }
}
