// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC6329C4C)]
    public class STU_C6329C4C : STUAnimParamUpdater_Base {
    }
}
