// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8194C261)]
    public class STU_8194C261 : STUStatescriptAction {
        [STUFieldAttribute(0x7E13BAA9, "m_buckets")]
        public teStructuredDataAssetRef<STUIdentifier>[] m_buckets;
    }
}
