// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xCFC060FC)]
    public class STU_CFC060FC : STU_31F561D3 {
        [STUFieldAttribute(0xFD6E7A84, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A458F8DB m_FD6E7A84;
    }
}
