// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFC7E2BA7)]
    public class STU_FC7E2BA7 : STUConfigVarNumeric {
        [STUFieldAttribute(0xC419B6DE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C419B6DE;

        [STUFieldAttribute(0x4A894399, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4A894399;

        [STUFieldAttribute(0xDE7F5261, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_DE7F5261;

        [STUFieldAttribute(0x57E6F640, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_57E6F640;

        [STUFieldAttribute(0xB04BECCB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B04BECCB;

        [STUFieldAttribute(0x641AB937, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_641AB937;
    }
}
