// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5A6C982D)]
    public class STU_5A6C982D : STUStatescriptAction {
    }
}
