// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x86F80EA5)]
    public class STU_86F80EA5 : STUStatescriptState {
        [STUFieldAttribute(0xE21DC621, "m_bodyEntity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_bodyEntity;
    }
}
