// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB0D4B2C2)]
    public class STU_B0D4B2C2 : STUStatescriptState {
        [STUFieldAttribute(0x07D00975, "m_onEntity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_onEntity;
    }
}
