// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4E383817)]
    public class STU_4E383817 : STUInstance {
        [STUFieldAttribute(0xD51F8DA1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D51F8DA1;

        [STUFieldAttribute(0xA1101766, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A1101766;

        [STUFieldAttribute(0xF95CE325, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F95CE325;

        [STUFieldAttribute(0xDDE1F5A5, "m_castLength", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_castLength;
    }
}
