// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xEAC1D3CA)]
    public class STU_EAC1D3CA : STUStatescriptStateUXBase {
    }
}
