// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x02278581)]
    public class STU_02278581 : STUConfigVarBoolBase {
        [STUFieldAttribute(0x4D901272, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4D901272;
    }
}
