// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x07B23524)]
    public class STU_07B23524 : STU_2381CD8E {
        [STUFieldAttribute(0x832E1C9D)]
        public float m_832E1C9D;

        [STUFieldAttribute(0xA02FD77B)]
        public float m_A02FD77B;

        [STUFieldAttribute(0xCF87A9F9)]
        public float m_CF87A9F9;

        [STUFieldAttribute(0x9A702D02)]
        public float m_9A702D02;

        [STUFieldAttribute(0xE2EEE534)]
        public float m_E2EEE534;

        [STUFieldAttribute(0xE2E50DD9)]
        public float m_E2E50DD9;
    }
}
