// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD77BDBBE)]
    public class STU_D77BDBBE : STU_7010A7BE {
        [STUFieldAttribute(0xBFDEB7F1, "m_height")]
        public float m_height;

        [STUFieldAttribute(0x71EF3CA4, "m_radius")]
        public float m_radius;
    }
}
