// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x66716A6D)]
    public class STU_66716A6D : STUConfigVarIterable {
        [STUFieldAttribute(0x65CE2851, "m_configVars", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar[] m_configVars;
    }
}
