// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4CF3EAFA)]
    public class STU_4CF3EAFA : STU_7D34E861 {
        [STUFieldAttribute(0xC7EE7D15, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C7EE7D15;
    }
}
