// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x15278C0F)]
    public class STU_15278C0F : STU_C7E05A5D {
        [STUFieldAttribute(0xF5928F34)]
        public teStructuredDataAssetRef<STU_51BAFC27> m_F5928F34;
    }
}
