// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x01E84A80)]
    public class STU_01E84A80 : STU_3444FBD1 {
        [STUFieldAttribute(0x15192D8D, "m_source", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUTextureSource m_source;

        [STUFieldAttribute(0x684928DE)]
        public uint m_684928DE;

        [STUFieldAttribute(0xF157BC30)]
        public byte m_F157BC30;

        [STUFieldAttribute(0x428F3A60)]
        public byte m_428F3A60;

        [STUFieldAttribute(0xDEF0D12D)]
        public byte m_DEF0D12D;

        [STUFieldAttribute(0x97719656)]
        public byte m_97719656;

        [STUFieldAttribute(0xD792633C)]
        public byte m_D792633C;

        [STUFieldAttribute(0x48E93856)]
        public byte m_48E93856;

        [STUFieldAttribute(0x0C6224CC)]
        public byte m_0C6224CC;
    }
}
