// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE7103546)]
    public class STU_E7103546 : STUConfigVarBoolBase {
        [STUFieldAttribute(0x44BB1696, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;

        [STUFieldAttribute(0xB8426A9E, "m_raycast", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_raycast;

        [STUFieldAttribute(0x13C82CF9, "m_distance", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_distance;
    }
}
