// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF26F968D)]
    public class STU_F26F968D : STUStatescriptOutputPlug {
    }
}
