// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x28460D41)]
    public class STU_28460D41 : STUStatescriptStateUXScreen {
        [STUFieldAttribute(0xFD2C111F, "m_productId", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_productId;

        [STUFieldAttribute(0x4ADCFADB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_4ADCFADB;
    }
}
