// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x43A9ECA7)]
    public class STU_43A9ECA7 : STU_2CAA4AFB {
        [STUFieldAttribute(0xF072EAAB)]
        public teStructuredDataAssetRef<STUEffect> m_F072EAAB;
    }
}
