// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x82771E07)]
    public class STU_82771E07 : STUStatescriptStateUXPresenter {
    }
}
