// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xADC6D1A0)]
    public class STU_ADC6D1A0 : STUConfigVarBoolBase {
    }
}
