// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x1DC233E2)]
    public class STU_1DC233E2 : STUConfigVarResource {
        [STUFieldAttribute(0x2077E211, "m_unlock", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_unlock;
    }
}
