// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x6EED6E50)]
    public class STU_6EED6E50 : STU_988BCA34 {
        [STUFieldAttribute(0xCC1B8224)]
        public teStructuredDataAssetRef<STUAnimation> m_CC1B8224;

        [STUFieldAttribute(0x56F27A44)]
        public teStructuredDataAssetRef<STUAnimation> m_56F27A44;

        [STUFieldAttribute(0x42101314)]
        public teStructuredDataAssetRef<STUAnimation> m_42101314;

        [STUFieldAttribute(0xDB1942AE)]
        public teStructuredDataAssetRef<STUAnimation> m_DB1942AE;

        [STUFieldAttribute(0x3F467588)]
        public teStructuredDataAssetRef<STUAnimation> m_3F467588;

        [STUFieldAttribute(0xA64F2432)]
        public teStructuredDataAssetRef<STUAnimation> m_A64F2432;

        [STUFieldAttribute(0xE17C656E)]
        public teStructuredDataAssetRef<STUAnimation> m_E17C656E;

        [STUFieldAttribute(0x6AC09B3A)]
        public teStructuredDataAssetRef<STUAnimation> m_6AC09B3A;

        [STUFieldAttribute(0x01B5D122)]
        public teStructuredDataAssetRef<STUDataFlow> m_01B5D122;

        [STUFieldAttribute(0x9BE2ACE4)]
        public teStructuredDataAssetRef<STUDataFlow> m_9BE2ACE4;

        [STUFieldAttribute(0x59F32C29, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigWeightSet1P m_59F32C29;

        [STUFieldAttribute(0xE57007D5, "m_userWeights", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimUserWeights m_userWeights;

        [STUFieldAttribute(0x94166C37, "m_globalLayerMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalLayerMultipliers m_globalLayerMultipliers;

        [STUFieldAttribute(0x0B0BDD51)]
        public float m_0B0BDD51;

        [STUFieldAttribute(0xCF87A9F9)]
        public float m_CF87A9F9;

        [STUFieldAttribute(0x9A702D02)]
        public float m_9A702D02;

        [STUFieldAttribute(0x54161545, "m_globalWeightMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalWeightMultipliers1P m_globalWeightMultipliers;
    }
}
