// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x52AE1043)]
    public class STU_52AE1043 : STUInstance {
        [STUFieldAttribute(0x6D86E7DF)]
        public teStructuredDataHashMap<STU_DFFD7080> m_6D86E7DF;

        [STUFieldAttribute(0x4A0D3E2E, "m_volumeID")]
        public int m_volumeID;
    }
}
