// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB49A497A)]
    public class STU_B49A497A : STUStatescriptStateUXBase {
        [STUFieldAttribute(0x60C7149E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_60C7149E;

        [STUFieldAttribute(0xAD2E57F4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_AD2E57F4;
    }
}
