// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3D225EF4)]
    public class STU_3D225EF4 : STUConfigVarNumeric {
        [STUFieldAttribute(0x44BB1696, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;

        [STUFieldAttribute(0x36967FDE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_36967FDE;

        [STUFieldAttribute(0xA8AFF195, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A8AFF195;
    }
}
