// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9A6E35E3)]
    public class STU_9A6E35E3 : STUStatescriptStateUXPresenter {
    }
}
