// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x16403206)]
    public class STU_16403206 : STUConfigVarResource {
        [STUFieldAttribute(0x44BB1696, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;

        [STUFieldAttribute(0x32A11A46, "m_slot", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_slot;
    }
}
