// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x01A17F2E)]
    public class STU_01A17F2E : STU_8B07626D {
        [STUFieldAttribute(0xF9E2C020, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_7059BA29 m_F9E2C020;

        [STUFieldAttribute(0x123B83F7, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_7059BA29 m_123B83F7;
    }
}
