// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF57E9A8A)]
    public class STU_F57E9A8A : STU_500EFDAC {
        [STUFieldAttribute(0x4E480A15)]
        public teVec3[] m_4E480A15;

        [STUFieldAttribute(0xBCE4ADF8)]
        public teVec4[] m_BCE4ADF8;

        [STUFieldAttribute(0xCA435417)]
        public byte[] m_CA435417;

        [STUFieldAttribute(0x1E4CA27F)]
        public byte[] m_1E4CA27F;

        [STUFieldAttribute(0xAF63148B)]
        public teVec3 m_AF63148B;

        [STUFieldAttribute(0xDA53285E)]
        public int m_DA53285E;

        [STUFieldAttribute(0xF3099F20, "m_volume")]
        public float m_volume;

        [STUFieldAttribute(0x493B0749)]
        public float m_493B0749;
    }
}
