// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8D643265)]
    public class STU_8D643265 : STUShippable {
        [STUFieldAttribute(0x39824653)]
        public teString m_39824653;

        [STUFieldAttribute(0x9564A554, "m_commands")]
        public teString m_commands;
    }
}
