// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4ADCD381)]
    public class STU_4ADCD381 : STUStatescriptState {
        [STUFieldAttribute(0x53E84AEF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_53E84AEF;

        [STUFieldAttribute(0xD32654DB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D32654DB;

        [STUFieldAttribute(0xFE841C79, "m_onFinishedPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onFinishedPlug;
    }
}
