// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4768E4A3)]
    public class STU_4768E4A3 : STUStatescriptCondition {
        [STUFieldAttribute(0xC77035BE)]
        public int[] m_C77035BE;

        [STUFieldAttribute(0x3C9341F5, "m_logicalButton", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_logicalButton;

        [STUFieldAttribute(0x30C0A41D)]
        public byte m_30C0A41D;

        [STUFieldAttribute(0x86CD8AF0)]
        public byte m_86CD8AF0;

        [STUFieldAttribute(0xA3E7D1E9)]
        public byte m_A3E7D1E9;

        [STUFieldAttribute(0xB4015D42)]
        public byte m_B4015D42;
    }
}
