// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB98638C6)]
    public class STU_B98638C6 : STU_52D8FB50 {
        [STUFieldAttribute(0x5180E750, "m_value")]
        public float m_value;

        [STUFieldAttribute(0x6C95EA69)]
        public Enum_2B1F7FBB m_6C95EA69;

        [STUFieldAttribute(0x50EB2F1A)]
        public byte m_50EB2F1A;
    }
}
