// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB1750356)]
    public class STU_B1750356 : STUGenericSettings_Base {
        [STUFieldAttribute(0xC596E81F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_9030EBD4 m_C596E81F;

        [STUFieldAttribute(0x3D1E92C8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_9030EBD4[] m_3D1E92C8;
    }
}
