// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x35B431B4)]
    public class STU_35B431B4 : STUStatescriptStateUXPresenter {
        [STUFieldAttribute(0xA0C757A8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A0C757A8;

        [STUFieldAttribute(0x253FA200, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_253FA200;

        [STUFieldAttribute(0x5D3F9849, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_5D3F9849;

        [STUFieldAttribute(0xB206AAFE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_B206AAFE;
    }
}
