// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA6B61CB4)]
    public class STU_A6B61CB4 : STUInstance {
        [STUFieldAttribute(0x0A8484FF)]
        public teStructuredDataAssetRef<STUIdentifier> m_0A8484FF;

        [STUFieldAttribute(0x82CC8608)]
        public teVec3[] m_82CC8608;
    }
}
