// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB8874962)]
    public class STU_B8874962 : STUConfigVarBoolBase {
    }
}
