// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD0907B57)]
    public class STU_D0907B57 : STUStatescriptAction {
        [STUFieldAttribute(0xCC84D865, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_CC84D865;
    }
}
