// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x00CF4A25)]
    public class STU_00CF4A25 : STU_16151658 {
        [STUFieldAttribute(0x36B1BDDE)]
        public int m_36B1BDDE;
    }
}
