// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xAF42564F)]
    public class STU_AF42564F : STUStatescriptInputPlug {
    }
}
