// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB53E9D8C)]
    public class STU_B53E9D8C : STUConfigVarBoolBase {
    }
}
