// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFFC97765)]
    public class STU_FFC97765 : STU_988BCA34 {
        [STUFieldAttribute(0x56F27A44)]
        public teStructuredDataAssetRef<STUAnimation> m_56F27A44;

        [STUFieldAttribute(0xBB8E5DAF)]
        public teStructuredDataAssetRef<STUAnimation> m_BB8E5DAF;

        [STUFieldAttribute(0x2F3CBE7F)]
        public teStructuredDataAssetRef<STUAnimation> m_2F3CBE7F;

        [STUFieldAttribute(0xB635EFC5)]
        public teStructuredDataAssetRef<STUAnimation> m_B635EFC5;

        [STUFieldAttribute(0xC132DF53)]
        public teStructuredDataAssetRef<STUAnimation> m_C132DF53;

        [STUFieldAttribute(0xD4C3E7A0)]
        public teStructuredDataAssetRef<STUAnimation> m_D4C3E7A0;

        [STUFieldAttribute(0x5C4AFF67)]
        public float m_5C4AFF67;

        [STUFieldAttribute(0xCE862056)]
        public float m_CE862056;

        [STUFieldAttribute(0x7CD5CC7A)]
        public float m_7CD5CC7A;

        [STUFieldAttribute(0xE5DC9DC0)]
        public float m_E5DC9DC0;

        [STUFieldAttribute(0x92DBAD56)]
        public float m_92DBAD56;

        [STUFieldAttribute(0xFA7D3C85)]
        public byte m_FA7D3C85;
    }
}
