// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x25DD6768)]
    public class STU_25DD6768 : STUConfigVarBoolBase {
    }
}
