// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB6C6910F)]
    public class STU_B6C6910F : STU_CD99C848 {
        [STUFieldAttribute(0xA808FBB7, "m_animationStreams", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimPlaybackStream[] m_animationStreams;
    }
}
