// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7C735618)]
    public class STU_7C735618 : STUGenericSettings_Base {
        [STUFieldAttribute(0x23F22EDD)]
        public float m_23F22EDD;

        [STUFieldAttribute(0xEB5CC394)]
        public float m_EB5CC394;
    }
}
