// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE438DA5C)]
    public class STU_E438DA5C : STUInstance {
        [STUFieldAttribute(0xA4DE4495, "m_displayName")]
        public teString m_displayName;

        [STUFieldAttribute(0xF1076DB5)]
        public byte[] m_F1076DB5;

        [STUFieldAttribute(0x3B486B27)]
        public uint m_3B486B27;
    }
}
