// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD43BF558)]
    public class STU_D43BF558 : STUStatescriptState {
        [STUFieldAttribute(0xBFA46EDF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BFA46EDF;
    }
}
