// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5C7DDBD8)]
    public class STU_5C7DDBD8 : STU_2CAA4AFB {
        [STUFieldAttribute(0xF072EAAB)]
        public teStructuredDataAssetRef<STU_46F1EF57> m_F072EAAB;
    }
}
