// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBF00B8A0)]
    public class STU_BF00B8A0 : STUInstance {
        [STUFieldAttribute(0xAE77A93E)]
        public float m_AE77A93E;

        [STUFieldAttribute(0xEAC3543E)]
        public float m_EAC3543E;

        [STUFieldAttribute(0x7662D6B6)]
        public float m_7662D6B6;

        [STUFieldAttribute(0x7458186E)]
        public float m_7458186E;

        [STUFieldAttribute(0x57B34058)]
        public float m_57B34058;

        [STUFieldAttribute(0x8E9E707E)]
        public float m_8E9E707E;

        [STUFieldAttribute(0xD979A740)]
        public float m_D979A740;

        [STUFieldAttribute(0x7BF7C639)]
        public float m_7BF7C639;

        [STUFieldAttribute(0x6EE9E49A)]
        public float m_6EE9E49A;

        [STUFieldAttribute(0x307CEECE)]
        public float m_307CEECE;

        [STUFieldAttribute(0x38A82E20)]
        public float m_38A82E20;

        [STUFieldAttribute(0x6B1077B5)]
        public float m_6B1077B5;

        [STUFieldAttribute(0x93949315)]
        public float m_93949315;
    }
}
