// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x1B789210)]
    public class STU_1B789210 : STUStatescriptAction {
        [STUFieldAttribute(0x41090CE8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_41090CE8;
    }
}
