// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7059BA29)]
    public class STU_7059BA29 : STU_5A844B17 {
        [STUFieldAttribute(0x5180E750, "m_value")]
        public float m_value;
    }
}
