// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC3CE719E)]
    public class STU_C3CE719E : STUInstance {
        [STUFieldAttribute(0x63033A92)]
        public teString m_63033A92;

        [STUFieldAttribute(0x3E15B7C2)]
        public uint m_3E15B7C2;
    }
}
