// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5552D718)]
    public class STU_5552D718 : STU_D5EE5EA3 {
        [STUFieldAttribute(0xC79A0A34, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_9FDCAC91 m_C79A0A34;

        [STUFieldAttribute(0x28678CA5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_28678CA5;

        [STUFieldAttribute(0xBFB5552D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_BFB5552D;

        [STUFieldAttribute(0x4B61E07C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_4B61E07C;

        [STUFieldAttribute(0x4C0C2465, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_4C0C2465;
    }
}
