// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0EACBF96)]
    public class STU_0EACBF96 : STUConfigVarVecBase {
        [STUFieldAttribute(0x480BCC63, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_480BCC63;
    }
}
