// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC7409708)]
    public class STU_C7409708 : STU_985D49FE {
        [STUFieldAttribute(0xC3FC0311, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C3FC0311;
    }
}
