// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBED0B494)]
    public class STU_BED0B494 : STU_012A1554 {
        [STUFieldAttribute(0x5F5A826C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5F5A826C;

        [STUFieldAttribute(0x2B68B937, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2B68B937;
    }
}
