// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0D1C206A)]
    public class STU_0D1C206A : STU_054BC7E8 {
        [STUFieldAttribute(0xF21D13AC)]
        public teStructuredDataAssetRef<STU_53908303> m_F21D13AC;

        [STUFieldAttribute(0x413F29AE, "m_key")]
        public ulong m_key;
    }
}
