// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x98642924)]
    public class STU_98642924 : STU_60C836A8 {
        [STUFieldAttribute(0x7EABA9B0)]
        public teStructuredDataAssetRef<STUTexture> m_7EABA9B0;

        [STUFieldAttribute(0x9AE726B3)]
        public teStructuredDataAssetRef<STUTexture> m_9AE726B3;

        [STUFieldAttribute(0xB0A6D155)]
        public teColorRGB m_B0A6D155;

        [STUFieldAttribute(0x2AB46586)]
        public teVec2 m_2AB46586;

        [STUFieldAttribute(0x72CE929F)]
        public teVec2 m_72CE929F;

        [STUFieldAttribute(0xD45D66B9)]
        public teVec2 m_D45D66B9;

        [STUFieldAttribute(0x3561C80C)]
        public float m_3561C80C;

        [STUFieldAttribute(0xC0115596)]
        public float m_C0115596;

        [STUFieldAttribute(0xB7631B2A)]
        public float m_B7631B2A;

        [STUFieldAttribute(0x5C2E034D)]
        public byte m_5C2E034D;
    }
}
