// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x98756158)]
    public class STU_98756158 : STU_EE48F03A {
        [STUFieldAttribute(0x12716D08, "m_type", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_6428396E m_type;

        [STUFieldAttribute(0x64C6C0F5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_C2B92620 m_64C6C0F5;

        [STUFieldAttribute(0x6785219F)]
        public Enum_3EB3DAC6 m_6785219F;

        [STUFieldAttribute(0xFE8C7025)]
        public Enum_3EB3DAC6 m_FE8C7025;
    }
}
