// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFBB0F3F0)]
    public class STU_FBB0F3F0 : STU_8EF1C54B {
        [STUFieldAttribute(0x609B720B, "m_direction", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_direction;

        [STUFieldAttribute(0x13C82CF9, "m_distance", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_distance;
    }
}
