// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x13422347)]
    public class STU_13422347 : STU_DDEA1B93 {
        [STUFieldAttribute(0x030DD6E3)]
        public teStructuredDataAssetRef<STUTexture> m_030DD6E3;

        [STUFieldAttribute(0xF650FDEB)]
        public float m_F650FDEB;
    }
}
