// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3F825AEF)]
    public class STU_3F825AEF : STU_00BEC203 {
        [STUFieldAttribute(0x19857773)]
        public teStructuredDataAssetRef<STUTexture> m_19857773;

        [STUFieldAttribute(0x970A7090)]
        public teStructuredDataAssetRef<STUTexture> m_970A7090;

        [STUFieldAttribute(0x43016058)]
        public teStructuredDataAssetRef<STUTexture> m_43016058;

        [STUFieldAttribute(0x3F22BFA1)]
        public teVec2 m_3F22BFA1;

        [STUFieldAttribute(0x16EA0B53)]
        public teVec2 m_16EA0B53;

        [STUFieldAttribute(0x38764882)]
        public float m_38764882;

        [STUFieldAttribute(0x40318CA1)]
        public float m_40318CA1;

        [STUFieldAttribute(0x3F0EA658)]
        public float m_3F0EA658;

        [STUFieldAttribute(0x9B20CE2B)]
        public float m_9B20CE2B;

        [STUFieldAttribute(0x36D4B59C)]
        public float m_36D4B59C;

        [STUFieldAttribute(0xB181A1BB)]
        public float m_B181A1BB;

        [STUFieldAttribute(0x02E3E010)]
        public byte m_02E3E010;

        [STUFieldAttribute(0x330BFA8D)]
        public byte m_330BFA8D;
    }
}
