// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4B034326)]
    public class STU_4B034326 : STUInstance {
        [STUFieldAttribute(0x6E2FF633)]
        public byte m_6E2FF633;
    }
}
