// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF72B9557)]
    public class STU_F72B9557 : STUInstance {
        [STUFieldAttribute(0x4E9B37A3)]
        public ulong m_4E9B37A3;

        [STUFieldAttribute(0x964BD5D0)]
        public uint m_964BD5D0;
    }
}
