// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x07D859F2)]
    public class STU_07D859F2 : STUStatescriptState {
        [STUFieldAttribute(0x95AE2E29)]
        public float m_95AE2E29;

        [STUFieldAttribute(0x5B9FA57C)]
        public float m_5B9FA57C;
    }
}
