// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB89B824E)]
    public class STU_B89B824E : STU_988BCA34 {
        [STUFieldAttribute(0x2AEB0AF1)]
        public teStructuredDataAssetRef<STUAnimation> m_2AEB0AF1;

        [STUFieldAttribute(0x2737FEC3)]
        public teStructuredDataAssetRef<STUAnimation> m_2737FEC3;

        [STUFieldAttribute(0x9900762F)]
        public teStructuredDataAssetRef<STUAnimation> m_9900762F;

        [STUFieldAttribute(0x3CE23B29)]
        public teStructuredDataAssetRef<STUAnimSynchGroup> m_3CE23B29;

        [STUFieldAttribute(0xBFACE1C5)]
        public float m_BFACE1C5;

        [STUFieldAttribute(0x06961051)]
        public float m_06961051;

        [STUFieldAttribute(0x5052C2F4)]
        public float m_5052C2F4;

        [STUFieldAttribute(0x6D640A54)]
        public byte m_6D640A54;
    }
}
