// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBF58CF0C)]
    public class STU_BF58CF0C : STUConfigVarVecBase {
        [STUFieldAttribute(0xA8A3E0F7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A8A3E0F7;

        [STUFieldAttribute(0x44BB1696, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;
    }
}
