// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x95897DD7)]
    public class STU_95897DD7 : STU_9D2A65BE {
        [STUFieldAttribute(0x9B272345, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_83A5F473 m_9B272345;

        [STUFieldAttribute(0xD7C8350B, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_D7C8350B;

        [STUFieldAttribute(0xC69D3ECF, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_89E66C6E m_C69D3ECF;

        [STUFieldAttribute(0x6FB4FB4F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_89E66C6E m_6FB4FB4F;

        [STUFieldAttribute(0xB6FB3D7F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_89E66C6E m_B6FB3D7F;
    }
}
