// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x70CBB013)]
    public class STU_70CBB013 : STUGameModeLegacy {
    }
}
