// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBA5B4438)]
    public class STU_BA5B4438 : STUConfigVarBoolBase {
    }
}
