// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x69A7A281)]
    public class STU_69A7A281 : STUEntityComponent {
    }
}
