// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x48A6550F)]
    public class STU_48A6550F : STUInstance {
        [STUFieldAttribute(0x1863265C)]
        public byte[] m_1863265C;

        [STUFieldAttribute(0x722E909E)]
        public byte[] m_722E909E;

        [STUFieldAttribute(0xF03BBBDD)]
        public byte[] m_F03BBBDD;

        [STUFieldAttribute(0xB5C0F593, "m_guid")]
        public ulong m_guid;

        [STUFieldAttribute(0x9AB20571, "m_fileSize")]
        public long m_fileSize;

        [STUFieldAttribute(0x771C5097)]
        public ulong m_771C5097;

        [STUFieldAttribute(0x47F2FEDE, "m_flags")]
        public uint m_flags;
    }
}
