// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x208441AE)]
    public class STU_208441AE : STUInstance {
        [STUFieldAttribute(0x4BCAC479)]
        public teString m_4BCAC479;

        [STUFieldAttribute(0xB4B4FE56)]
        public teStructuredDataAssetRef<STU_E438DA5C> m_B4B4FE56;
    }
}
