// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x31B1E932)]
    public class STU_31B1E932 : STUInstance {
        [STUFieldAttribute(0xFA1F65E6)]
        public teStructuredDataAssetRef<STU_D9B62A91> m_FA1F65E6;

        [STUFieldAttribute(0x74E354A1)]
        public Enum_DC059083 m_74E354A1;
    }
}
