// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3A081DB6)]
    public class STU_3A081DB6 : STUGenericSettings_Base {
        [STUFieldAttribute(0x4FC96D5F, "m_heroLevels")]
        public uint[] m_heroLevels;
    }
}
