// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9383789F)]
    public class STU_9383789F : STU_988BCA34 {
        [STUFieldAttribute(0x4FFCB593)]
        public teStructuredDataAssetRef<STUAnimation> m_4FFCB593;

        [STUFieldAttribute(0x1BC89B24)]
        public teStructuredDataAssetRef<STUDataFlow> m_1BC89B24;

        [STUFieldAttribute(0x04269389)]
        public teStructuredDataAssetRef<STUAnimation> m_04269389;

        [STUFieldAttribute(0x54161545, "m_globalWeightMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalWeightMultipliers m_globalWeightMultipliers;

        [STUFieldAttribute(0xE57007D5, "m_userWeights", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimUserWeights m_userWeights;

        [STUFieldAttribute(0x94166C37, "m_globalLayerMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalLayerMultipliers m_globalLayerMultipliers;

        [STUFieldAttribute(0xBB5D1B64)]
        public float m_BB5D1B64;

        [STUFieldAttribute(0xC4C621AC)]
        public float m_C4C621AC;

        [STUFieldAttribute(0x4573D30C)]
        public float m_4573D30C;

        [STUFieldAttribute(0xCF87A9F9)]
        public float m_CF87A9F9;

        [STUFieldAttribute(0x9A702D02)]
        public float m_9A702D02;

        [STUFieldAttribute(0x6D640A54)]
        public byte m_6D640A54;

        [STUFieldAttribute(0x8C6A9ADF)]
        public byte m_8C6A9ADF;
    }
}
