// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xADA69A43)]
    public class STU_ADA69A43 : STUConfigVarIntBase {
    }
}
