// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8D591677)]
    public class STU_8D591677 : STUConfigVarVecBase {
        [STUFieldAttribute(0xE7E6C790, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E7E6C790;

        [STUFieldAttribute(0x90E1F706, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_90E1F706;

        [STUFieldAttribute(0x09E8A6BC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_09E8A6BC;
    }
}
