// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0683EF9F)]
    public class STU_0683EF9F : STU_8245A944 {
        [STUFieldAttribute(0xC08C4427, "m_name")]
        public teStructuredDataAssetRef<ulong> m_name;

        [STUFieldAttribute(0x7EF482CC)]
        public teStructuredDataAssetRef<STUUXLink> m_7EF482CC;
    }
}
