// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3967459E)]
    public class STU_3967459E : STU_988BCA34 {
        [STUFieldAttribute(0xA9A953D9)]
        public teStructuredDataAssetRef<STUAnimation> m_A9A953D9;

        [STUFieldAttribute(0xCFEDE282)]
        public teStructuredDataAssetRef<STUAnimation> m_CFEDE282;

        [STUFieldAttribute(0x680C8BD4)]
        public teStructuredDataAssetRef<STUAnimation> m_680C8BD4;

        [STUFieldAttribute(0x30A00263)]
        public teStructuredDataAssetRef<STUAnimation> m_30A00263;

        [STUFieldAttribute(0x56E4B338)]
        public teStructuredDataAssetRef<STUAnimation> m_56E4B338;

        [STUFieldAttribute(0xF105DA6E)]
        public teStructuredDataAssetRef<STUAnimation> m_F105DA6E;

        [STUFieldAttribute(0x47A732F5)]
        public teStructuredDataAssetRef<STUAnimation> m_47A732F5;

        [STUFieldAttribute(0x21E383AE)]
        public teStructuredDataAssetRef<STUAnimation> m_21E383AE;

        [STUFieldAttribute(0x8602EAF8)]
        public teStructuredDataAssetRef<STUAnimation> m_8602EAF8;

        [STUFieldAttribute(0x3CE23B29)]
        public teStructuredDataAssetRef<STUAnimSynchGroup> m_3CE23B29;

        [STUFieldAttribute(0x62FF81C8)]
        public teStructuredDataAssetRef<STUDataFlow> m_62FF81C8;

        [STUFieldAttribute(0xBFACE1C5)]
        public float m_BFACE1C5;

        [STUFieldAttribute(0x06961051)]
        public float m_06961051;

        [STUFieldAttribute(0x5052C2F4)]
        public float m_5052C2F4;

        [STUFieldAttribute(0xC2F8F7EB)]
        public float m_C2F8F7EB;

        [STUFieldAttribute(0x5BF1A651)]
        public float m_5BF1A651;

        [STUFieldAttribute(0x2CF696C7)]
        public float m_2CF696C7;

        [STUFieldAttribute(0x6D640A54)]
        public byte m_6D640A54;

        [STUFieldAttribute(0x9CA98815)]
        public byte m_9CA98815;
    }
}
