// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x1BB99C36)]
    public class STU_1BB99C36 : STUStatescriptAction {
        [STUFieldAttribute(0x40877716, "m_entityDefinition", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entityDefinition;

        [STUFieldAttribute(0x679AF128, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_679AF128;

        [STUFieldAttribute(0x25D9F07F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_25D9F07F;

        [STUFieldAttribute(0x4976528D, "m_position", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_position;

        [STUFieldAttribute(0x99EEFF9F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_99EEFF9F;

        [STUFieldAttribute(0x87018F61, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_87018F61;

        [STUFieldAttribute(0x4736F464, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4736F464;

        [STUFieldAttribute(0x2C6BA8AE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2C6BA8AE;

        [STUFieldAttribute(0x9C93DC34, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9C93DC34;

        [STUFieldAttribute(0x7D34796D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7D34796D;

        [STUFieldAttribute(0xA07AF76E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A07AF76E;

        [STUFieldAttribute(0x62395F5D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_62395F5D;

        [STUFieldAttribute(0x2982E640, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarFilter m_2982E640;

        [STUFieldAttribute(0xAFEFA59A, "m_basedEntity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_basedEntity;

        [STUFieldAttribute(0xD7C59487, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_D7C59487;
    }
}
