// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD2B5B485)]
    public class STU_D2B5B485 : STUStatescriptActionMovementModOp {
        [STUFieldAttribute(0x687E19A2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_687E19A2;

        [STUFieldAttribute(0x2D7C5A20, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2D7C5A20;

        [STUFieldAttribute(0x8552E1F1)]
        public Enum_BBD83BFC m_8552E1F1;
    }
}
