// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x6643747B)]
    public class STU_6643747B : STUInstance {
        [STUFieldAttribute(0x7337B336, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_52B83235[] m_7337B336;

        [STUFieldAttribute(0x6CF6BB26, "m_entityID")]
        public teEntityID m_entityID;

        [STUFieldAttribute(0xA828AAEE)]
        public uint m_A828AAEE;

        [STUFieldAttribute(0x8FB4D039)]
        public byte m_8FB4D039;

        [STUFieldAttribute(0x783C3A1D)]
        public byte m_783C3A1D;
    }
}
