// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x17FFD332)]
    public class STU_17FFD332 : STU_7010A7BE {
        [STUFieldAttribute(0x38A4D36A)]
        public teStructuredDataAssetRef<STU_46F1EF57> m_38A4D36A;
    }
}
