// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF9F1E339)]
    public class STU_F9F1E339 : STUStatescriptAction {
        [STUFieldAttribute(0xC55D5C0D, "m_params", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A51F99C5[] m_params;

        [STUFieldAttribute(0x5178F207, "m_gameMessage", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_gameMessage;

        [STUFieldAttribute(0x694D2B8B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_694D2B8B;
    }
}
