// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC64F1640)]
    public class STU_C64F1640 : STUInstance {
        [STUFieldAttribute(0xB2CA6977, "m_identifier")]
        public teStructuredDataAssetRef<STUIdentifier> m_identifier;
    }
}
