// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD37440B3)]
    public class STU_D37440B3 : STUStatescriptAction {
        [STUFieldAttribute(0x652FA432, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_652FA432;
    }
}
