// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA091BBB3)]
    public class STU_A091BBB3 : STUConfigVarBoolBase {
    }
}
