// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x35FD4032)]
    public class STU_35FD4032 : STUInstance {
        [STUFieldAttribute(0x45B2BAB8, "m_graph", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_A129CB94 m_graph;

        [STUFieldAttribute(0x1D100B51)]
        public teStructuredDataAssetRef<STUIdentifier>[] m_1D100B51;
    }
}
