// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD647DE49)]
    public class STU_D647DE49 : STUInstance {
        [STUFieldAttribute(0xC377A2E3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_1AFE903E[] m_C377A2E3;

        [STUFieldAttribute(0xFC10744B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_1AFE903E[] m_FC10744B;

        [STUFieldAttribute(0x6784F0EF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_1AFE903E[] m_6784F0EF;

        [STUFieldAttribute(0x7B5125B3, "m_states", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_1AFE903E[] m_states;

        [STUFieldAttribute(0x6B05D9D3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_1AFE903E[] m_6B05D9D3;

        [STUFieldAttribute(0x424284B8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_1AFE903E[] m_424284B8;
    }
}
