// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBBD639EE)]
    public class STU_BBD639EE : STUStatescriptStateUXPresenter {
    }
}
