// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xAA8E29F9)]
    public class STU_AA8E29F9 : STUInstance {
        [STUFieldAttribute(0xD38EEAEB, "m_start", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_start;

        [STUFieldAttribute(0xCB53B1B6, "m_end", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_end;
    }
}
