// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC0368123)]
    public class STU_C0368123 : STUInstance {
        [STUFieldAttribute(0x0E27C815, "m_description")]
        public teStructuredDataAssetRef<ulong> m_description;

        [STUFieldAttribute(0x3A1719BD)]
        public teStructuredDataAssetRef<STU_D83702BD>[] m_3A1719BD;

        [STUFieldAttribute(0xA8CF697B)]
        public float m_A8CF697B;

        [STUFieldAttribute(0x84233703)]
        public float m_84233703;
    }
}
