// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x79AC08FD)]
    public class STU_79AC08FD : STU_7FDA291B {
        [STUFieldAttribute(0x2631DB8B, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_0AD175A1 m_2631DB8B;
    }
}
