// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x60AF402E)]
    public class STU_60AF402E : STU_988BCA34 {
        [STUFieldAttribute(0x33F573CB)]
        public teStructuredDataAssetRef<STUAnimation> m_33F573CB;

        [STUFieldAttribute(0xAAFC2271)]
        public teStructuredDataAssetRef<STUAnimation> m_AAFC2271;

        [STUFieldAttribute(0xDDFB12E7)]
        public teStructuredDataAssetRef<STUAnimation> m_DDFB12E7;

        [STUFieldAttribute(0x62FF81C8)]
        public teStructuredDataAssetRef<STUDataFlow> m_62FF81C8;

        [STUFieldAttribute(0xC2F8F7EB)]
        public float m_C2F8F7EB;

        [STUFieldAttribute(0x5BF1A651)]
        public float m_5BF1A651;

        [STUFieldAttribute(0x2CF696C7)]
        public float m_2CF696C7;

        [STUFieldAttribute(0x6D640A54)]
        public byte m_6D640A54;

        [STUFieldAttribute(0x9CA98815)]
        public byte m_9CA98815;
    }
}
