// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x09E7EB88)]
    public class STU_09E7EB88 : STUConfigVarBoolBase {
    }
}
