// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x82451BA1)]
    public class STU_82451BA1 : STU_42851043 {
        [STUFieldAttribute(0x1B6EE2D3, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_F13866FD m_1B6EE2D3;
    }
}
