// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x97BF9643)]
    public class STU_97BF9643 : STUStatescriptAction {
        [STUFieldAttribute(0x02EA850F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_02EA850F;
    }
}
