// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA7E09B2C)]
    public class STU_A7E09B2C : STU_977B1F25 {
        [STUFieldAttribute(0xBE17C500, "m_stat")]
        public teStructuredDataAssetRef<STUStat> m_stat;

        [STUFieldAttribute(0x1D1FDD39, "m_heroes", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_51A83B3C m_heroes;
    }
}
