// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF2227548)]
    public class STU_F2227548 : STUStatescriptState {
        [STUFieldAttribute(0x0A998CD4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar[] m_0A998CD4;
    }
}
