// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA7785237)]
    public class STU_A7785237 : STUInstance {
        [STUFieldAttribute(0xB2CA6977, "m_identifier")]
        public teStructuredDataAssetRef<STUIdentifier> m_identifier;

        [STUFieldAttribute(0x3E43CC3A)]
        public float m_3E43CC3A;
    }
}
