// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xDD39FC80)]
    public class STU_DD39FC80 : STUStatescriptAction {
        [STUFieldAttribute(0x94AAD12F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_94AAD12F;

        [STUFieldAttribute(0x8BD3A14B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8BD3A14B;

        [STUFieldAttribute(0x6F3C3AD1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6F3C3AD1;

        [STUFieldAttribute(0x2D570EDF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2D570EDF;

        [STUFieldAttribute(0xD2DE2080, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D2DE2080;

        [STUFieldAttribute(0xFBE64598, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FBE64598;

        [STUFieldAttribute(0x7F0363C5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7F0363C5;

        [STUFieldAttribute(0x99121BAD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_99121BAD;
    }
}
