// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x44602F47)]
    public class STU_44602F47 : STUConfigVarBoolBase {
        [STUFieldAttribute(0x44BB1696, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;
    }
}
