// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xDD34ADD6)]
    public class STU_DD34ADD6 : STU_D5EE5EA3 {
        [STUFieldAttribute(0xC79A0A34, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_7E47FA6D m_C79A0A34;

        [STUFieldAttribute(0x391C3C37, "m_jump", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_jump;

        [STUFieldAttribute(0x8130B820, "m_additiveFiring", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_additiveFiring;
    }
}
