// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x44CA97D9)]
    public class STU_44CA97D9 : STUInstance {
        [STUFieldAttribute(0x1C263920, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_BF94A5BB[] m_1C263920;
    }
}
