// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD689C470)]
    public class STU_D689C470 : STUStatescriptState {
        [STUFieldAttribute(0x3C9341F5, "m_logicalButton", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_logicalButton;

        [STUFieldAttribute(0xF81224CC, "m_onGoingDownPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onGoingDownPlug;

        [STUFieldAttribute(0xE2E57DE3, "m_onComingUpPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onComingUpPlug;

        [STUFieldAttribute(0x8496114B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_24AB1F0B m_8496114B;

        [STUFieldAttribute(0x29909C7C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_24AB1F0B m_29909C7C;
    }
}
