// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB9763011)]
    public class STU_B9763011 : STU_27C3556F {
        [STUFieldAttribute(0x6B30461C, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_197AA12D m_6B30461C;

        [STUFieldAttribute(0xF23917A6, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_197AA12D m_F23917A6;

        [STUFieldAttribute(0x09657D8A, "m_mode")]
        public Enum_288674B9 m_mode;

        [STUFieldAttribute(0x63658F06)]
        public ushort m_63658F06;

        [STUFieldAttribute(0x27196F53)]
        public byte m_27196F53;

        [STUFieldAttribute(0xB8043C11)]
        public byte m_B8043C11;
    }
}
