// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC2BB77C3)]
    public class STU_C2BB77C3 : STU_7010A7BE {
        [STUFieldAttribute(0xDA82D7D5, "m_clutterModel")]
        public teStructuredDataAssetRef<STUModel> m_clutterModel;

        [STUFieldAttribute(0x51F5E688, "m_clutterLook")]
        public teStructuredDataAssetRef<STUModelLook> m_clutterLook;

        [STUFieldAttribute(0x391AD364, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_7AED4F17[] m_391AD364;

        [STUFieldAttribute(0x8EE62DEE)]
        public teVec3 m_8EE62DEE;

        [STUFieldAttribute(0x0335B498)]
        public teVec2 m_0335B498;

        [STUFieldAttribute(0x53335A4D)]
        public float m_53335A4D;

        [STUFieldAttribute(0x8B679234)]
        public float m_8B679234;

        [STUFieldAttribute(0x65F12A4F)]
        public float m_65F12A4F;
    }
}
