// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x08FD35C5)]
    public class STU_08FD35C5 : STU_0D1DEA1C {
        [STUFieldAttribute(0x000F7058, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_000F7058;

        [STUFieldAttribute(0x8A9D4658, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8A9D4658;
    }
}
