// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD77C154C)]
    public class STU_D77C154C : STU_D5EE5EA3 {
        [STUFieldAttribute(0xDF051A78, "m_animBlendTreeSet")]
        public teStructuredDataAssetRef<STUAnimBlendTreeSet> m_animBlendTreeSet;
    }
}
