// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4D8A2F7C)]
    public class STU_4D8A2F7C : STUStatescriptDataFlowEntity {
        [STUFieldAttribute(0xDB137227, "m_handle", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_handle;
    }
}
