// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xDCFCB3AC)]
    public class STU_DCFCB3AC : STUInstance {
        [STUFieldAttribute(0x6B268BA4, "m_rankedData", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_BDA80C6D m_rankedData;

        [STUFieldAttribute(0xC08C4427, "m_name")]
        public teStructuredDataAssetRef<ulong> m_name;

        [STUFieldAttribute(0xDDD940C4, "m_subName")]
        public teStructuredDataAssetRef<ulong> m_subName;

        [STUFieldAttribute(0x0E27C815, "m_description")]
        public teStructuredDataAssetRef<ulong> m_description;

        [STUFieldAttribute(0xF57EF970, "m_subDescription")]
        public teStructuredDataAssetRef<ulong> m_subDescription;

        [STUFieldAttribute(0x2945A01D)]
        public teStructuredDataAssetRef<ulong>[] m_2945A01D;

        [STUFieldAttribute(0x2AFAD55E)]
        public teStructuredDataAssetRef<ulong> m_2AFAD55E;

        [STUFieldAttribute(0x236F2210)]
        public teStructuredDataAssetRef<ulong> m_236F2210;

        [STUFieldAttribute(0x882B23AB)]
        public teStructuredDataAssetRef<ulong> m_882B23AB;

        [STUFieldAttribute(0xF113AE07)]
        public teStructuredDataAssetRef<ulong>[] m_F113AE07;

        [STUFieldAttribute(0xC3D5D78E)]
        public teStructuredDataAssetRef<STUIdentifier> m_C3D5D78E;

        [STUFieldAttribute(0xF2002AD9)]
        public teStructuredDataAssetRef<STU_4683D781> m_F2002AD9;

        [STUFieldAttribute(0x7020C9E5)]
        public teStructuredDataAssetRef<ulong> m_7020C9E5;

        [STUFieldAttribute(0x9AC9A244)]
        public teStructuredDataAssetRef<ulong> m_9AC9A244;

        [STUFieldAttribute(0xA2E3FEBD)]
        public teStructuredDataAssetRef<ulong> m_A2E3FEBD;

        [STUFieldAttribute(0x41637E0E, "m_catalog")]
        public teStructuredDataAssetRef<STUMapCatalog> m_catalog;

        [STUFieldAttribute(0xA170ADA1, "m_rulesets")]
        public teStructuredDataAssetRef<STUGameRuleset>[] m_rulesets;

        [STUFieldAttribute(0x80E8B547, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_800E6458[] m_80E8B547;

        [STUFieldAttribute(0xB7879DD1)]
        public teStructuredDataAssetRef<STUStat> m_B7879DD1;

        [STUFieldAttribute(0xA949EAC2)]
        public teStructuredDataAssetRef<STUStat>[] m_A949EAC2;

        [STUFieldAttribute(0x40E7ACB4)]
        public teStructuredDataAssetRef<STUIdentifier>[] m_40E7ACB4;

        [STUFieldAttribute(0x0BCDD6FE)]
        public teStructuredDataAssetRef<STUStat>[] m_0BCDD6FE;

        [STUFieldAttribute(0x6063048D)]
        public teStructuredDataAssetRef<STUAchievement>[] m_6063048D;

        [STUFieldAttribute(0xFC46E086)]
        public teStructuredDataAssetRef<STUUnlock>[] m_FC46E086;

        [STUFieldAttribute(0xDE19777A, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_332970A5[] m_DE19777A;

        [STUFieldAttribute(0x5ADFFF49)]
        public teStructuredDataAssetRef<ulong> m_5ADFFF49;

        [STUFieldAttribute(0xAA3BA939)]
        public float m_AA3BA939;

        [STUFieldAttribute(0xB4D0CF73)]
        public float m_B4D0CF73;

        [STUFieldAttribute(0x2DB3257F)]
        public float m_2DB3257F;

        [STUFieldAttribute(0x7D82558F)]
        public float m_7D82558F;

        [STUFieldAttribute(0xFF564932)]
        public byte m_FF564932;

        [STUFieldAttribute(0xC72C9FB4)]
        public byte m_C72C9FB4;

        [STUFieldAttribute(0x71A4B61B)]
        public byte m_71A4B61B;

        [STUFieldAttribute(0xF2D2E604)]
        public byte m_F2D2E604;

        [STUFieldAttribute(0x06B4B49E)]
        public byte m_06B4B49E;

        [STUFieldAttribute(0x03AF99B2)]
        public byte m_03AF99B2;

        [STUFieldAttribute(0x05C4556A)]
        public byte m_05C4556A;

        [STUFieldAttribute(0x61F2E386)]
        public byte m_61F2E386;

        [STUFieldAttribute(0xDAE69C29)]
        public byte m_DAE69C29;

        [STUFieldAttribute(0x3FE2657E)]
        public byte m_3FE2657E;

        [STUFieldAttribute(0x1AA548A1)]
        public byte m_1AA548A1;

        [STUFieldAttribute(0x5D182DBD)]
        public byte m_5D182DBD;
    }
}
