// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF44D0701)]
    public class STU_F44D0701 : STUConfigVarBoolBase {
    }
}
