// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x729C8CA1)]
    public class STU_729C8CA1 : STUConfigVarBoolBase {
    }
}
