// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xCDE26C3E)]
    public class STU_CDE26C3E : STU_D5EE5EA3 {
        [STUFieldAttribute(0xC79A0A34, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_2F9A7ABE m_C79A0A34;

        [STUFieldAttribute(0x8130B820, "m_additiveFiring", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_additiveFiring;
    }
}
