// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x13FCBA1B)]
    public class STU_13FCBA1B : STUStatescriptAction {
        [STUFieldAttribute(0xD28A289B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D28A289B;

        [STUFieldAttribute(0x712BDAF2)]
        public Enum_E6DCF607 m_712BDAF2;
    }
}
