// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x47173B0D)]
    public class STU_47173B0D : STUConfigVarBoolBase {
    }
}
