// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xAD2A3E8B)]
    public class STU_AD2A3E8B : STUConfigVarResource {
        [STUFieldAttribute(0x0CFC7D02, "m_target", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_target;
    }
}
