// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE37D4FC8)]
    public class STU_E37D4FC8 : STU_7010A7BE {
        [STUFieldAttribute(0x44530645)]
        public teStructuredDataAssetRef<STUEmptyAsset> m_44530645;

        [STUFieldAttribute(0xEC99A702)]
        public teStructuredDataAssetRef<STU_B46BFB92> m_EC99A702;

        [STUFieldAttribute(0xC2A17D57, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_2B59F5CF[] m_C2A17D57;

        [STUFieldAttribute(0xEA13E26C, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_8F31BAC5[] m_EA13E26C;

        [STUFieldAttribute(0x847B471E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_CF57702B[] m_847B471E;

        [STUFieldAttribute(0x9501FD16)]
        public teUUID[] m_9501FD16;

        [STUFieldAttribute(0x23476444)]
        public byte m_23476444;
    }
}
