// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFD5393DF)]
    public class STU_FD5393DF : STUConfigVarIntBase {
        [STUFieldAttribute(0x4976528D, "m_position", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_position;
    }
}
