// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB6DADE68)]
    public class STU_B6DADE68 : STUStatescriptState {
        [STUFieldAttribute(0xEDFB51D3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EDFB51D3;

        [STUFieldAttribute(0x08DEDF24, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_08DEDF24;

        [STUFieldAttribute(0x7186DD1C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7186DD1C;

        [STUFieldAttribute(0x076235BA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_8DCB62EA m_076235BA;

        [STUFieldAttribute(0x9C785779, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_9C785779;
    }
}
