// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7BF31629)]
    public class STU_7BF31629 : STUStatescriptState {
        [STUFieldAttribute(0x4AD5330B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4AD5330B;

        [STUFieldAttribute(0xB041C0E8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B041C0E8;

        [STUFieldAttribute(0x53E591A4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_53E591A4;

        [STUFieldAttribute(0xE8F2DC78, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E8F2DC78;
    }
}
