// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3861F7C6)]
    public class STU_3861F7C6 : STU_34493776 {
        [STUFieldAttribute(0x71EF3CA4, "m_radius", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_radius;

        [STUFieldAttribute(0xFCEE9A99, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_FCEE9A99;
    }
}
