// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x35E0D16F)]
    public class STU_35E0D16F : STU_AC312A6D {
        [STUFieldAttribute(0x890536B8, "m_duration", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_duration;

        [STUFieldAttribute(0x2AA1F78D, "m_color", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_color;
    }
}
