// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE8F4D683)]
    public class STU_E8F4D683 : STUStatescriptAction {
        [STUFieldAttribute(0x94983906, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_94983906;

        [STUFieldAttribute(0x7438CA3E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_7438CA3E;
    }
}
