// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9C27CBCE)]
    public class STU_9C27CBCE : STUStatescriptState {
        [STUFieldAttribute(0x12716D08, "m_type")]
        public Enum_30C59457 m_type;
    }
}
