// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9DAD9F92)]
    public class STU_9DAD9F92 : STUStatescriptState {
        [STUFieldAttribute(0xC2E82625)]
        public teStructuredDataAssetRef<STUAnimAlias>[] m_C2E82625;

        [STUFieldAttribute(0x83A073EE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_83A073EE;

        [STUFieldAttribute(0x2336EC26, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2336EC26;

        [STUFieldAttribute(0x07A67AB7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_07A67AB7;
    }
}
