// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB9B2ADCE)]
    public class STU_B9B2ADCE : STU_5A844B17 {
        [STUFieldAttribute(0x5180E750, "m_value")]
        public teStructuredDataAssetRef<STUAnimIdentifier> m_value;
    }
}
