// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xAB86A710)]
    public class STU_AB86A710 : STUStatescriptState {
        [STUFieldAttribute(0x6DFC6A5F, "m_priority", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_priority;

        [STUFieldAttribute(0x0B9168E9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0B9168E9;

        [STUFieldAttribute(0x491557C3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_491557C3;
    }
}
