// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD523EC08)]
    public class STU_D523EC08 : STU_1DA60BE1 {
        [STUFieldAttribute(0x8D6F3F9E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_96B7802F m_8D6F3F9E;
    }
}
