// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xAE8237D3)]
    public class STU_AE8237D3 : STUStatescriptState {
        [STUFieldAttribute(0xA8CF697B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A8CF697B;
    }
}
