// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x66E666E1)]
    public class STU_66E666E1 : STU_E5A0DDB8 {
        [STUFieldAttribute(0xBFDEB7F1, "m_height", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_height;

        [STUFieldAttribute(0xBBF65DEC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_BBF65DEC;

        [STUFieldAttribute(0xB5E3255F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_B5E3255F;

        [STUFieldAttribute(0xE1FF7789, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_E1FF7789;

        [STUFieldAttribute(0xEFEA0F3A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_EFEA0F3A;
    }
}
