// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xED329693)]
    public class STU_ED329693 : STU_F1C8D756 {
        [STUFieldAttribute(0xFCDFD33B, "m_baseEntity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_baseEntity;

        [STUFieldAttribute(0xAF17327B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_AF17327B;

        [STUFieldAttribute(0xCDD23137, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_CDD23137;
    }
}
