// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC3800CEB)]
    public class STU_C3800CEB : STU_D5EE5EA3 {
        [STUFieldAttribute(0xC79A0A34, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_90169B44 m_C79A0A34;

        [STUFieldAttribute(0xABB06A4A, "m_death", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_death;

        [STUFieldAttribute(0x09C9B3FF, "m_locomotion", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_locomotion;

        [STUFieldAttribute(0x63CD3165, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_63CD3165;

        [STUFieldAttribute(0x2EED3876, "m_globalAdditive", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_globalAdditive;

        [STUFieldAttribute(0x4AD5FD9A, "m_globalOverride", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_globalOverride;
    }
}
