// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x16FB7084)]
    public class STU_16FB7084 : STU_AF2D57CA {
        [STUFieldAttribute(0x9B62CDBD, "m_model", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_04BEFB8D m_model;

        [STUFieldAttribute(0x6D4304BF, "m_modelLook", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_66AE5BD3 m_modelLook;

        [STUFieldAttribute(0xD3832764, "m_animation", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_C2BF346D m_animation;

        [STUFieldAttribute(0xF8BFFC1C, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_F8BFFC1C;
    }
}
