// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA67BCA58)]
    public class STU_A67BCA58 : STU_FD502CD8 {
        [STUFieldAttribute(0x7F72C64E, "m_resourceData")]
        public byte[] m_resourceData;

        [STUFieldAttribute(0xB5C0F593, "m_guid")]
        public ulong m_guid;

        [STUFieldAttribute(0xEEB61C52)]
        public ulong m_EEB61C52;

        [STUFieldAttribute(0x47F2FEDE, "m_flags")]
        public uint m_flags;
    }
}
