// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7AED4F17)]
    public class STU_7AED4F17 : STUInstance {
        [STUFieldAttribute(0x26262E89, "m_rotation")]
        public teQuat m_rotation;

        [STUFieldAttribute(0x4976528D, "m_position")]
        public teVec3 m_position;

        [STUFieldAttribute(0xA0B19AE0)]
        public teVec3 m_A0B19AE0;

        [STUFieldAttribute(0xF68E6023)]
        public float m_F68E6023;
    }
}
