// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x163B937C)]
    public class STU_163B937C : STU_F0900F0C {
        [STUFieldAttribute(0x829EB29E)]
        public byte m_829EB29E;

        [STUFieldAttribute(0x92DE15A0)]
        public byte m_92DE15A0;
    }
}
