// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x83AC03F8)]
    public class STU_83AC03F8 : STUStatescriptAction {
        [STUFieldAttribute(0x3F919D33, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3F919D33;
    }
}
