// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFEDF6743)]
    public class STU_FEDF6743 : STUConfigVarBoolBase {
    }
}
