// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5720B660)]
    public class STU_5720B660 : STUStatescriptCondition {
        [STUFieldAttribute(0xEDFB51D3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EDFB51D3;

        [STUFieldAttribute(0x413F29AE, "m_key", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_key;

        [STUFieldAttribute(0x5180E750, "m_value", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_value;
    }
}
