// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x83CC0FE5)]
    public class STU_83CC0FE5 : STU_3F7D2DCF {
        [STUFieldAttribute(0xFBB95E89)]
        public Enum_85EA39F8 m_FBB95E89;
    }
}
