// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x1751EBD0)]
    public class STU_1751EBD0 : STUConfigVarBoolBase {
        [STUFieldAttribute(0x33073533, "m_possessor", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_possessor;
    }
}
