// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF64AC4C3)]
    public class STU_F64AC4C3 : STU_988BCA34 {
        [STUFieldAttribute(0x7F2B4698)]
        public teStructuredDataAssetRef<STUAnimation> m_7F2B4698;

        [STUFieldAttribute(0xE8F99F10)]
        public teStructuredDataAssetRef<STUAnimation> m_E8F99F10;

        [STUFieldAttribute(0x1C2D2A41)]
        public teStructuredDataAssetRef<STUAnimation> m_1C2D2A41;

        [STUFieldAttribute(0x1B40EE58)]
        public teStructuredDataAssetRef<STUAnimation> m_1B40EE58;

        [STUFieldAttribute(0xF54E8F74)]
        public teStructuredDataAssetRef<STUAnimation> m_F54E8F74;

        [STUFieldAttribute(0xC08C1AE1)]
        public teStructuredDataAssetRef<STUAnimation> m_C08C1AE1;

        [STUFieldAttribute(0x575EC369)]
        public teStructuredDataAssetRef<STUAnimation> m_575EC369;

        [STUFieldAttribute(0xA38A7638)]
        public teStructuredDataAssetRef<STUAnimation> m_A38A7638;

        [STUFieldAttribute(0xA4E7B221)]
        public teStructuredDataAssetRef<STUAnimation> m_A4E7B221;

        [STUFieldAttribute(0x4AE9D30D)]
        public teStructuredDataAssetRef<STUAnimation> m_4AE9D30D;

        [STUFieldAttribute(0xD50F3BFA)]
        public teStructuredDataAssetRef<STUAnimation> m_D50F3BFA;

        [STUFieldAttribute(0x42DDE272)]
        public teStructuredDataAssetRef<STUAnimation> m_42DDE272;

        [STUFieldAttribute(0xB6095723)]
        public teStructuredDataAssetRef<STUAnimation> m_B6095723;

        [STUFieldAttribute(0xB164933A)]
        public teStructuredDataAssetRef<STUAnimation> m_B164933A;

        [STUFieldAttribute(0x5F6AF216)]
        public teStructuredDataAssetRef<STUAnimation> m_5F6AF216;

        [STUFieldAttribute(0x9F2A57F0)]
        public teStructuredDataAssetRef<STUAnimation> m_9F2A57F0;

        [STUFieldAttribute(0x08F88E78)]
        public teStructuredDataAssetRef<STUAnimation> m_08F88E78;

        [STUFieldAttribute(0xFC2C3B29)]
        public teStructuredDataAssetRef<STUAnimation> m_FC2C3B29;

        [STUFieldAttribute(0xFB41FF30)]
        public teStructuredDataAssetRef<STUAnimation> m_FB41FF30;

        [STUFieldAttribute(0x154F9E1C)]
        public teStructuredDataAssetRef<STUAnimation> m_154F9E1C;

        [STUFieldAttribute(0x54161545, "m_globalWeightMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalWeightMultipliers m_globalWeightMultipliers;

        [STUFieldAttribute(0xE57007D5, "m_userWeights", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimUserWeights m_userWeights;

        [STUFieldAttribute(0x94166C37, "m_globalLayerMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalLayerMultipliers m_globalLayerMultipliers;

        [STUFieldAttribute(0x553C811C)]
        public float m_553C811C;

        [STUFieldAttribute(0xD1854934)]
        public float m_D1854934;

        [STUFieldAttribute(0xCC8149B8)]
        public float m_CC8149B8;

        [STUFieldAttribute(0x9A702D02)]
        public float m_9A702D02;

        [STUFieldAttribute(0xA978D468)]
        public byte m_A978D468;

        [STUFieldAttribute(0x35EA4648)]
        public byte m_35EA4648;

        [STUFieldAttribute(0x8C6A9ADF)]
        public byte m_8C6A9ADF;
    }
}
