// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE83B890E)]
    public class STU_E83B890E : STU_632FE08F {
        [STUFieldAttribute(0x2AA1F78D, "m_color", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_color;

        [STUFieldAttribute(0x06269FAE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_06269FAE;

        [STUFieldAttribute(0x355E91F8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_355E91F8;

        [STUFieldAttribute(0x6B163A1A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_6B163A1A;

        [STUFieldAttribute(0xF3AA9A1C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_F3AA9A1C;

        [STUFieldAttribute(0xFAC55962, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_FAC55962;

        [STUFieldAttribute(0x2E03BF60, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_2E03BF60;

        [STUFieldAttribute(0x19B2212F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_19B2212F;

        [STUFieldAttribute(0xDC1E3375, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_DC1E3375;

        [STUFieldAttribute(0x0E0F5835, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_0E0F5835;
    }
}
