// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7DFB33C5)]
    public class STU_7DFB33C5 : STU_D5EE5EA3 {
        [STUFieldAttribute(0xC79A0A34, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_8806C982 m_C79A0A34;
    }
}
