// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFCF6F7FD)]
    public class STU_FCF6F7FD : STUConfigVarNumeric {
    }
}
