// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC054B256)]
    public class STU_C054B256 : STUConfigVarResource {
        [STUFieldAttribute(0x33073533, "m_possessor", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_possessor;
    }
}
