// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF536A60F)]
    public class STU_F536A60F : STU_F1C8D756 {
        [STUFieldAttribute(0xDFA07E24, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_DFA07E24;

        [STUFieldAttribute(0xBF6D8F58, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BF6D8F58;

        [STUFieldAttribute(0x8E3D03B5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUAnimCurve m_8E3D03B5;
    }
}
