// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD48D1551)]
    public class STU_D48D1551 : STU_57FB0E59 {
        [STUFieldAttribute(0xD829413B, "m_texture")]
        public teStructuredDataAssetRef<STUTexture> m_texture;

        [STUFieldAttribute(0x474DEA4D)]
        public byte m_474DEA4D;
    }
}
