// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xEB945F6A)]
    public class STU_EB945F6A : STU_076F907E {
        [STUFieldAttribute(0x51FD1AA5)]
        public Enum_64D2D157 m_51FD1AA5;
    }
}
