// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x770008C3)]
    public class STU_770008C3 : STU_D7AA5B79 {
        [STUFieldAttribute(0xEF646D9F, "m_state")]
        public teStructuredDataAssetRef<STUSoundState> m_state;
    }
}
