// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xCEABCD77)]
    public class STU_CEABCD77 : STUStatescriptAction {
        [STUFieldAttribute(0xB3A827A6, "m_queueEntity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_queueEntity;
    }
}
