// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x40887286)]
    public class STU_40887286 : STU_9E8DF6A9 {
        [STUFieldAttribute(0x4003FE34, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_91DBD6E2 m_4003FE34;

        [STUFieldAttribute(0x6B163A1A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_6B163A1A;

        [STUFieldAttribute(0xD9E357A0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_D9E357A0;

        [STUFieldAttribute(0xC24F9BE3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_C24F9BE3;
    }
}
