// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x90ABE1E6)]
    public class STU_90ABE1E6 : STU_FFBBD692 {
        [STUFieldAttribute(0x9FA1D797)]
        public float m_9FA1D797;

        [STUFieldAttribute(0x941EC7BE)]
        public float m_941EC7BE;

        [STUFieldAttribute(0x353BBECD)]
        public float m_353BBECD;

        [STUFieldAttribute(0x0E0638B1)]
        public float m_0E0638B1;

        [STUFieldAttribute(0xAA423214)]
        public float m_AA423214;
    }
}
