// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xDF838DC1)]
    public class STU_DF838DC1 : STU_EE48F03A {
        [STUFieldAttribute(0x6AD49FD7, "m_min")]
        public teVec4 m_min;

        [STUFieldAttribute(0x56D9A08E, "m_max")]
        public teVec4 m_max;

        [STUFieldAttribute(0xB304867E)]
        public byte m_B304867E;
    }
}
