// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD19ED09D)]
    public class STU_D19ED09D : STU_8168B961 {
        [STUFieldAttribute(0x641A2291)]
        public teStructuredDataAssetRef<STUTexture> m_641A2291;
    }
}
