// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x36AEFD6A)]
    public class STU_36AEFD6A : STU_16151658 {
        [STUFieldAttribute(0xB331FCEC, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_7EA9A81B m_B331FCEC;

        [STUFieldAttribute(0x5180E750, "m_value")]
        public teStructuredDataAssetRef<STUAnimation> m_value;

        [STUFieldAttribute(0x0F99F7EB)]
        public byte m_0F99F7EB;
    }
}
