// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x09BE14DE)]
    public class STU_09BE14DE : STUStatescriptStateUXPresenter {
    }
}
