// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x38F63436)]
    public class STU_38F63436 : STUConfigVarResource {
    }
}
