// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFD9566D2)]
    public class STU_FD9566D2 : STU_B553DA1C {
        [STUFieldAttribute(0x17CF450F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_17CF450F;

        [STUFieldAttribute(0x5819C2C1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5819C2C1;

        [STUFieldAttribute(0xFCA8A7F1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FCA8A7F1;

        [STUFieldAttribute(0xBCE7DF87, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BCE7DF87;

        [STUFieldAttribute(0x623E960B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_623E960B;
    }
}
