// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x240DBF22)]
    public class STU_240DBF22 : STUInstance {
        [STUFieldAttribute(0x342FAC7E, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5A7A6127[] m_342FAC7E;

        [STUFieldAttribute(0x54A0B215)]
        public teStructuredDataAssetRef<STUIdentifier>[] m_54A0B215;

        [STUFieldAttribute(0x886B118B)]
        public teStructuredDataAssetRef<STU_98B439CA> m_886B118B;

        [STUFieldAttribute(0x1BC75F9A)]
        public teStructuredDataAssetRef<STU_240DBF22> m_1BC75F9A;

        [STUFieldAttribute(0x06AE9D8D)]
        public float m_06AE9D8D;

        [STUFieldAttribute(0xB12BC9E0)]
        public float m_B12BC9E0;

        [STUFieldAttribute(0xDC9131AE)]
        public float m_DC9131AE;
    }
}
