// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3120EBAC)]
    public class STU_3120EBAC : STU_9D2A65BE {
        [STUFieldAttribute(0x87089166, "m_targetEntity", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_targetEntity;

        [STUFieldAttribute(0x420FFF0A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_420FFF0A;
    }
}
