// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x72D96307)]
    public class STU_72D96307 : STUConfigVarIntBase {
    }
}
