// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x21C69C9F)]
    public class STU_21C69C9F : STUStatescriptAction {
        [STUFieldAttribute(0x15931831, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_15931831;

        [STUFieldAttribute(0xA5249DE6, "m_text", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_text;

        [STUFieldAttribute(0x1CA0CBED, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1CA0CBED;
    }
}
