// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x001E61E7)]
    public class STU_001E61E7 : STUConfigVarBoolBase {
        [STUFieldAttribute(0x0CFC7D02, "m_target", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_target;

        [STUFieldAttribute(0xC4E6BD4E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C4E6BD4E;
    }
}
