// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7005CB1D)]
    public class STU_7005CB1D : STUInstance {
        [STUFieldAttribute(0xC08C4427, "m_name")]
        public teString m_name;

        [STUFieldAttribute(0x94DF8DB3, "m_input", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_input;

        [STUFieldAttribute(0x8A63191E)]
        public Enum_F74DB503 m_8A63191E;
    }
}
