// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5218CED1)]
    public class STU_5218CED1 : STU_AA172924 {
        [STUFieldAttribute(0xADE95629, "m_items", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimNode_AdjustBoneTransformParams_ScalePositionPSItem[] m_items;
    }
}
