// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9F67C194)]
    public class STU_9F67C194 : STUStatescriptStateUXBase {
        [STUFieldAttribute(0x10E31D91, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_10E31D91;
    }
}
