// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x75895443)]
    public class STU_75895443 : STU_BB5480D2 {
        [STUFieldAttribute(0x99C85425, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_4D3338E7 m_99C85425;
    }
}
