// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xDEE2C427)]
    public class STU_DEE2C427 : STU_45DA868C {
        [STUFieldAttribute(0xBE6442BC)]
        public byte m_BE6442BC;

        [STUFieldAttribute(0x870C52E5)]
        public byte m_870C52E5;

        [STUFieldAttribute(0x84E14A67)]
        public byte m_84E14A67;
    }
}
