// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB740FD14)]
    public class STU_B740FD14 : STUInstance {
        [STUFieldAttribute(0x5DB5FE78)]
        public byte m_5DB5FE78;
    }
}
