// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x83873B7C)]
    public class STU_83873B7C : STUStatescriptAction {
        [STUFieldAttribute(0x3F06DEC0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3F06DEC0;

        [STUFieldAttribute(0xADD23553, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_ADD23553;

        [STUFieldAttribute(0x41090CE8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_41090CE8;
    }
}
