// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8F31BAC5)]
    public class STU_8F31BAC5 : STUInstance {
        [STUFieldAttribute(0xAF4F8EB4)]
        public teUUID m_AF4F8EB4;

        [STUFieldAttribute(0x132317B9)]
        public teUUID m_132317B9;

        [STUFieldAttribute(0x666FA60D)]
        public teString m_666FA60D;
    }
}
