// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x1CB2245C)]
    public class STU_1CB2245C : STUStatescriptState {
        [STUFieldAttribute(0x3A96C10C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3A96C10C;
    }
}
