// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xDD8ADABD)]
    public class STU_DD8ADABD : STUConfigVarBoolBase {
    }
}
