// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE2082D80)]
    public class STU_E2082D80 : STUStatescriptState {
        [STUFieldAttribute(0x9C37DAA0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9C37DAA0;
    }
}
