// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE68DB2C2)]
    public class STU_E68DB2C2 : STUConfigVarBoolBase {
        [STUFieldAttribute(0x5A4F9C3E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5A4F9C3E;
    }
}
