// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC402D6BB)]
    public class STU_C402D6BB : STU_988BCA34 {
        [STUFieldAttribute(0xA8413101)]
        public teStructuredDataAssetRef<STUAnimation> m_A8413101;

        [STUFieldAttribute(0x391C3C37, "m_jump")]
        public teStructuredDataAssetRef<STUAnimation> m_jump;

        [STUFieldAttribute(0x31E3F1C6)]
        public float m_31E3F1C6;

        [STUFieldAttribute(0x553C811C)]
        public float m_553C811C;

        [STUFieldAttribute(0x9A702D02)]
        public float m_9A702D02;

        [STUFieldAttribute(0xA978D468)]
        public byte m_A978D468;
    }
}
