// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA742FC5A)]
    public class STU_A742FC5A : STU_CD4F440C {
        [STUFieldAttribute(0x242A820B, "m_loadout")]
        public teStructuredDataAssetRef<STULoadout> m_loadout;
    }
}
