// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x83DE0C58)]
    public class STU_83DE0C58 : STUConfigVarNumeric {
        [STUFieldAttribute(0x4D901272, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4D901272;
    }
}
