// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x87476D32)]
    public class STU_87476D32 : STU_9E8DF6A9 {
        [STUFieldAttribute(0x55D93761, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_55D93761;
    }
}
