// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x23F17FCB)]
    public class STU_23F17FCB : STU_988BCA34 {
        [STUFieldAttribute(0xABB06A4A, "m_death")]
        public teStructuredDataAssetRef<STUAnimation> m_death;
    }
}
