// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB4DD308C)]
    public class STU_B4DD308C : STUConfigVarStringBase {
        [STUFieldAttribute(0xEED526BC, "m_strings", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar[] m_strings;

        [STUFieldAttribute(0x0F5F7A8A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0F5F7A8A;
    }
}
