// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBCAFFA62)]
    public class STU_BCAFFA62 : STUStatescriptState {
        [STUFieldAttribute(0x0A63B9DA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0A63B9DA;

        [STUFieldAttribute(0x71EF3CA4, "m_radius", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_radius;

        [STUFieldAttribute(0x2AA1F78D, "m_color", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_color;
    }
}
