// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8B134EEA)]
    public class STU_8B134EEA : STUConfigVarResource {
        [STUFieldAttribute(0xCF6154A7, "m_hero", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_hero;
    }
}
