// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0640286F)]
    public class STU_0640286F : STUEntityComponent {
        [STUFieldAttribute(0xECEE4320)]
        public teVec3A m_ECEE4320;

        [STUFieldAttribute(0x2D2B6746)]
        public teVec3A m_2D2B6746;

        [STUFieldAttribute(0x0C1FC38C)]
        public float m_0C1FC38C;

        [STUFieldAttribute(0x13D97F64)]
        public float m_13D97F64;

        [STUFieldAttribute(0x06AD73A7)]
        public float m_06AD73A7;

        [STUFieldAttribute(0xBD9896CB)]
        public float m_BD9896CB;

        [STUFieldAttribute(0xB7E0B25A)]
        public float m_B7E0B25A;

        [STUFieldAttribute(0xEEA420C1)]
        public float m_EEA420C1;
    }
}
