// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD5384F53)]
    public class STU_D5384F53 : STUConfigVarEntityID {
    }
}
