// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x36DE9B6E)]
    public class STU_36DE9B6E : STUConfigVarStringBase {
        [STUFieldAttribute(0xFD2C111F, "m_productId", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_productId;

        [STUFieldAttribute(0x12716D08, "m_type")]
        public Enum_9D6E2F51 m_type;
    }
}
