// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC852F362)]
    public class STU_C852F362 : STU_988BCA34 {
        [STUFieldAttribute(0x4BFA7167)]
        public teStructuredDataAssetRef<STUAnimation> m_4BFA7167;

        [STUFieldAttribute(0x14C56DAD)]
        public teVec2 m_14C56DAD;

        [STUFieldAttribute(0xE1D00983)]
        public float m_E1D00983;

        [STUFieldAttribute(0x96D73915)]
        public float m_96D73915;

        [STUFieldAttribute(0x81D481DE)]
        public float m_81D481DE;

        [STUFieldAttribute(0x51956F34)]
        public float m_51956F34;
    }
}
