// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x07722A23)]
    public class STU_07722A23 : STUStatescriptCondition {
        [STUFieldAttribute(0xC4630712, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C4630712;
    }
}
