// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7A27F0BD)]
    public class STU_7A27F0BD : STUInstance {
        [STUFieldAttribute(0xC5622F19, "m_geoSet")]
        public teStructuredDataAssetRef<STU_875E571C> m_geoSet;

        [STUFieldAttribute(0xB9339ACC, "m_enable")]
        public byte m_enable;
    }
}
