// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x43A1D25F)]
    public class STU_43A1D25F : STUConfigVarBoolBase {
    }
}
