// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xCE2A781A)]
    public class STU_CE2A781A : STU_988BCA34 {
        [STUFieldAttribute(0xC67133EE)]
        public teStructuredDataAssetRef<STUAnimation> m_C67133EE;

        [STUFieldAttribute(0xE82B9CAB)]
        public teStructuredDataAssetRef<STUAnimation> m_E82B9CAB;

        [STUFieldAttribute(0x74BED7D5)]
        public teStructuredDataAssetRef<STUDataFlow> m_74BED7D5;

        [STUFieldAttribute(0x779A62D6)]
        public float m_779A62D6;

        [STUFieldAttribute(0x2999FD0A)]
        public float m_2999FD0A;

        [STUFieldAttribute(0xB6F39DE4)]
        public float m_B6F39DE4;
    }
}
