// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5BEA9B4B)]
    public class STU_5BEA9B4B : STUStatescriptAction {
        [STUFieldAttribute(0xC55D5C0D, "m_params", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A51F99C5[] m_params;

        [STUFieldAttribute(0xE3072BFB, "m_condition", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_condition;

        [STUFieldAttribute(0x5178F207, "m_gameMessage", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_gameMessage;
    }
}
