// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB1FAFF9C)]
    public class STU_B1FAFF9C : STUConfigVarBoolBase {
    }
}
