// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x501D4413)]
    public class STU_501D4413 : STU_988BCA34 {
        [STUFieldAttribute(0xFEF5E174)]
        public float m_FEF5E174;

        [STUFieldAttribute(0x7F70847D)]
        public float m_7F70847D;

        [STUFieldAttribute(0x04FADC17)]
        public float m_04FADC17;

        [STUFieldAttribute(0x857FB91E)]
        public float m_857FB91E;

        [STUFieldAttribute(0xC450BCEE)]
        public float m_C450BCEE;

        [STUFieldAttribute(0xDA85CAA9)]
        public float m_DA85CAA9;
    }
}
