// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x35892256)]
    public class STU_35892256 : STU_988BCA34 {
        [STUFieldAttribute(0xF9691E41, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimCurve m_F9691E41;

        [STUFieldAttribute(0x0FC9C76B)]
        public teStructuredDataAssetRef<STUAnimation> m_0FC9C76B;

        [STUFieldAttribute(0x0CA66BFD)]
        public teStructuredDataAssetRef<STUAnimation> m_0CA66BFD;

        [STUFieldAttribute(0x1BC89B24)]
        public teStructuredDataAssetRef<STUDataFlow> m_1BC89B24;

        [STUFieldAttribute(0x54161545, "m_globalWeightMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalWeightMultipliers m_globalWeightMultipliers;

        [STUFieldAttribute(0xE347529B, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigAimWeightSet m_E347529B;

        [STUFieldAttribute(0x66E2743D, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigAimWeightSet m_66E2743D;

        [STUFieldAttribute(0x90E7F607, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigAimWeightSet m_90E7F607;

        [STUFieldAttribute(0x2F6A890C, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigAimWeightSet m_2F6A890C;

        [STUFieldAttribute(0xEB6B5CD5, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigAimWeightSet m_EB6B5CD5;

        [STUFieldAttribute(0xFE40DD3B, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigAimWeightSet m_FE40DD3B;

        [STUFieldAttribute(0x7FD9DC4D, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigAimWeightSet m_7FD9DC4D;

        [STUFieldAttribute(0x49F2FE5F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigAimWeightSet m_49F2FE5F;

        [STUFieldAttribute(0xFFCB1F68, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigAimWeightSet m_FFCB1F68;

        [STUFieldAttribute(0xE57007D5, "m_userWeights", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimUserWeights m_userWeights;

        [STUFieldAttribute(0x94166C37, "m_globalLayerMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalLayerMultipliers m_globalLayerMultipliers;

        [STUFieldAttribute(0x4573D30C)]
        public float m_4573D30C;

        [STUFieldAttribute(0xCF87A9F9)]
        public float m_CF87A9F9;

        [STUFieldAttribute(0x9A702D02)]
        public float m_9A702D02;

        [STUFieldAttribute(0x6D640A54)]
        public byte m_6D640A54;

        [STUFieldAttribute(0x8C6A9ADF)]
        public byte m_8C6A9ADF;
    }
}
