// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0FB8C2F5)]
    public class STU_0FB8C2F5 : STUConfigVarEntityID {
        [STUFieldAttribute(0xFCFC654D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FCFC654D;

        [STUFieldAttribute(0x35570DE3, "m_filter", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarFilter m_filter;
    }
}
