// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9960EBA6)]
    public class STU_9960EBA6 : STUConfigVarNumeric {
        [STUFieldAttribute(0x59B47EDB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_59B47EDB;
    }
}
