// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x223ACAC1)]
    public class STU_223ACAC1 : STUStatescriptState {
    }
}
