// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7522A54D)]
    public class STU_7522A54D : STU_632FE08F {
        [STUFieldAttribute(0x4003FE34, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_91DBD6E2 m_4003FE34;

        [STUFieldAttribute(0xAD401645, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_AD401645;

        [STUFieldAttribute(0xC24F9BE3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_C24F9BE3;

        [STUFieldAttribute(0xF3AA9A1C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_F3AA9A1C;

        [STUFieldAttribute(0x6B163A1A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_6B163A1A;

        [STUFieldAttribute(0x66918FBA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_66918FBA;

        [STUFieldAttribute(0xA492410E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_A492410E;

        [STUFieldAttribute(0x2B1E722D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_2B1E722D;
    }
}
