// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x534FAE4D)]
    public class STU_534FAE4D : STUStatescriptAction {
        [STUFieldAttribute(0xEF646D9F, "m_state")]
        public Enum_902BE2E4 m_state;

        [STUFieldAttribute(0x642BF611)]
        public Enum_61FC7C1B m_642BF611;
    }
}
