// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xEF277C2F)]
    public class STU_EF277C2F : STUConfigVarVecBase {
        [STUFieldAttribute(0x120DDD57, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_120DDD57;

        [STUFieldAttribute(0x556D3F86, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_556D3F86;

        [STUFieldAttribute(0x5898CAE1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5898CAE1;

        [STUFieldAttribute(0xBA5686AD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BA5686AD;
    }
}
