// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA07B181C)]
    public class STU_A07B181C : STUConfigVarVecBase {
        [STUFieldAttribute(0x44BB1696, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;

        [STUFieldAttribute(0x89F6C2A7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_89F6C2A7;

        [STUFieldAttribute(0x4736F464, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4736F464;

        [STUFieldAttribute(0xDC87B407, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_DC87B407;

        [STUFieldAttribute(0xBD02981E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BD02981E;

        [STUFieldAttribute(0xB8458BE9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B8458BE9;
    }
}
