// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC0AC0A1F)]
    public class STU_C0AC0A1F : STUConfigVarIntBase {
        [STUFieldAttribute(0x4976528D, "m_position", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_position;

        [STUFieldAttribute(0x8832C5CE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8832C5CE;

        [STUFieldAttribute(0xE916D883, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E916D883;

        [STUFieldAttribute(0x547FDB39, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_547FDB39;

        [STUFieldAttribute(0x17CF450F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_17CF450F;

        [STUFieldAttribute(0x964EF67E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_964EF67E;

        [STUFieldAttribute(0xC7B74D23, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C7B74D23;

        [STUFieldAttribute(0x5B6700C0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5B6700C0;

        [STUFieldAttribute(0x4EECD432, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4EECD432;

        [STUFieldAttribute(0xF7B3D3EE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F7B3D3EE;

        [STUFieldAttribute(0xA64A68B3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A64A68B3;

        [STUFieldAttribute(0x07ADA678, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_07ADA678;
    }
}
