// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x1FAD5515)]
    public class STU_1FAD5515 : STUMirroredEntityComponent {
    }
}
