// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xCD93896E)]
    public class STU_CD93896E : STUStatescriptAction {
        [STUFieldAttribute(0x5FB6D29D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5FB6D29D;
    }
}
