// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3B52E9E4)]
    public class STU_3B52E9E4 : STUConfigVarVecBase {
        [STUFieldAttribute(0xA8A3E0F7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A8A3E0F7;

        [STUFieldAttribute(0x85DAF782, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_85DAF782;

        [STUFieldAttribute(0x955D10CD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_955D10CD;

        [STUFieldAttribute(0x365E1278)]
        public Enum_66D23672 m_365E1278;
    }
}
