// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE25FA5BF)]
    public class STU_E25FA5BF : STU_BB5480D2 {
        [STUFieldAttribute(0xB15E294D, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_9122D8E3 m_B15E294D;
    }
}
