// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9B042EB7)]
    public class STU_9B042EB7 : STUConfigVarBoolBase {
    }
}
