// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x37AA1F65)]
    public class STU_37AA1F65 : STU_1359915D {
        [STUFieldAttribute(0x841B307C, "m_blendTime", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimBlendTimeParams m_blendTime;

        [STUFieldAttribute(0x6B9BD86E, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_7059BA29 m_6B9BD86E;

        [STUFieldAttribute(0xE4E3B77F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_7059BA29 m_E4E3B77F;

        [STUFieldAttribute(0xE2931663, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_F0900F0C m_E2931663;

        [STUFieldAttribute(0x504E15E4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_16151658 m_504E15E4;

        [STUFieldAttribute(0x8B1E545D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_16151658 m_8B1E545D;
    }
}
