// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD6DC4580)]
    public class STU_D6DC4580 : STUConfigVarIntBase {
        [STUFieldAttribute(0x4976528D, "m_position", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_position;

        [STUFieldAttribute(0x5A4F9C3E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5A4F9C3E;
    }
}
