// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4AE38763)]
    public class STU_4AE38763 : STUInstance {
        [STUFieldAttribute(0x23B0B148)]
        public teStructuredDataAssetRef<STU_46F1EF57>[] m_23B0B148;

        [STUFieldAttribute(0xBD3AA397)]
        public teStructuredDataAssetRef<STU_46F1EF57>[] m_BD3AA397;
    }
}
