// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x746F502B)]
    public class STU_746F502B : STU_6E363AA3 {
        [STUFieldAttribute(0x71EF3CA4, "m_radius", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_radius;

        [STUFieldAttribute(0xBE45168F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_BE45168F;
    }
}
