// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8299ECD7)]
    public class STU_8299ECD7 : STU_D5EE5EA3 {
        [STUFieldAttribute(0xC79A0A34, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_A79D7325 m_C79A0A34;

        [STUFieldAttribute(0x598703EA, "m_primaryFire", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_primaryFire;

        [STUFieldAttribute(0x601AA474, "m_secondaryFire", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_secondaryFire;
    }
}
