// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7246786D)]
    public class STU_7246786D : STUStatescriptStateUXPresenter {
    }
}
