// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x197AA12D)]
    public class STU_197AA12D : STU_5A844B17 {
        [STUFieldAttribute(0x5180E750, "m_value")]
        public teStructuredDataAssetRef<STUDataFlow> m_value;
    }
}
