// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x705A94D0)]
    public class STU_705A94D0 : STU_8E6EF5E8 {
        [STUFieldAttribute(0x94DF8DB3, "m_input", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_input;
    }
}
