// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x653419D9)]
    public class STU_653419D9 : STUInstance {
        [STUFieldAttribute(0xE4FC89FC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E4FC89FC;

        [STUFieldAttribute(0x5A315069, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5A315069;

        [STUFieldAttribute(0xFFF57D9E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FFF57D9E;

        [STUFieldAttribute(0x6549E059, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6549E059;

        [STUFieldAttribute(0x36EFF8BD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_36EFF8BD;

        [STUFieldAttribute(0x10DC309E)]
        public Enum_42875FE5 m_10DC309E;
    }
}
