// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD943B534)]
    public class STU_D943B534 : STUConfigVarBoolBase {
    }
}
