// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA71A5B5B)]
    public class STU_A71A5B5B : STU_7010A7BE {
        [STUFieldAttribute(0xFCF3C30C, "m_effect")]
        public teStructuredDataAssetRef<STUEffect> m_effect;

        [STUFieldAttribute(0x24873BB5)]
        public float m_24873BB5;

        [STUFieldAttribute(0x59EF1E79)]
        public float m_59EF1E79;

        [STUFieldAttribute(0x500B190C)]
        public byte m_500B190C;

        [STUFieldAttribute(0xF5253751)]
        public byte m_F5253751;
    }
}
