// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3D3BF505)]
    public class STU_3D3BF505 : STU_5A844B17 {
        [STUFieldAttribute(0x5180E750, "m_value")]
        public teVec2 m_value;
    }
}
