// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC43F6A1B)]
    public class STU_C43F6A1B : STUStatescriptAction {
        [STUFieldAttribute(0xCF6154A7, "m_hero", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_hero;

        [STUFieldAttribute(0x8530B547, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8530B547;

        [STUFieldAttribute(0x34F116C8, "m_behavior")]
        public Enum_0E6C0EE2 m_behavior;
    }
}
