// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE1953161)]
    public class STU_E1953161 : STU_09FB0449 {
        [STUFieldAttribute(0x8F782357, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8F782357;

        [STUFieldAttribute(0x69188CB6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_69188CB6;

        [STUFieldAttribute(0xF9FD7B2B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F9FD7B2B;

        [STUFieldAttribute(0x1F9DD4CA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1F9DD4CA;

        [STUFieldAttribute(0x7DD41E3E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7DD41E3E;

        [STUFieldAttribute(0xF3E24B26, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F3E24B26;
    }
}
