// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8CCDFB8F)]
    public class STU_8CCDFB8F : STU_3444FBD1 {
        [STUFieldAttribute(0xC277ACC0)]
        public int m_C277ACC0;
    }
}
