// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x77A6DF8F)]
    public class STU_77A6DF8F : STUInstance {
        [STUFieldAttribute(0xC9160636)]
        public teString m_C9160636;

        [STUFieldAttribute(0x61D9A0CC)]
        public teString m_61D9A0CC;

        [STUFieldAttribute(0x90A4BBD0)]
        public teStructuredDataAssetRef<STUUXDisplayText> m_90A4BBD0;

        [STUFieldAttribute(0xFFA4E821)]
        public teStructuredDataAssetRef<STUUnlock> m_FFA4E821;

        [STUFieldAttribute(0xC3210176, "m_celebrationGUID")]
        public teStructuredDataAssetRef<STUCelebration> m_celebrationGUID;

        [STUFieldAttribute(0xE47DDEB5)]
        public teStructuredDataAssetRef<STUTexture> m_E47DDEB5;

        [STUFieldAttribute(0x31F960E7)]
        public int m_31F960E7;

        [STUFieldAttribute(0x6FC3F2CC)]
        public byte m_6FC3F2CC;
    }
}
