// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3FCCF8CB)]
    public class STU_3FCCF8CB : STUStatescriptAction {
        [STUFieldAttribute(0xB5C0F593, "m_guid", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_guid;
    }
}
