// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x740935B9)]
    public class STU_740935B9 : STUConfigVarBoolBase {
    }
}
