// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4E32637F)]
    public class STU_4E32637F : STUGenericSettings_Base {
        [STUFieldAttribute(0xFC460754)]
        public float m_FC460754;

        [STUFieldAttribute(0x4864A849)]
        public float m_4864A849;

        [STUFieldAttribute(0x9C79F130)]
        public float m_9C79F130;

        [STUFieldAttribute(0x6D32C633)]
        public float m_6D32C633;
    }
}
