// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0AC02FC6)]
    public class STU_0AC02FC6 : STU_AF2D57CA {
        [STUFieldAttribute(0x3506060F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_465A29EF m_3506060F;
    }
}
