// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD9806F01)]
    public class STU_D9806F01 : STUStatescriptState {
        [STUFieldAttribute(0x1FA8EC7E, "m_spawnEntities", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_spawnEntities;
    }
}
