// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBF960171)]
    public class STU_BF960171 : STU_988BCA34 {
        [STUFieldAttribute(0x547D9847, "m_dataFlow")]
        public teStructuredDataAssetRef<STUDataFlow> m_dataFlow;

        [STUFieldAttribute(0x3168F230)]
        public teStructuredDataAssetRef<STUAnimCategory> m_3168F230;

        [STUFieldAttribute(0x709A3F7A)]
        public float m_709A3F7A;

        [STUFieldAttribute(0x8487F31F)]
        public float m_8487F31F;

        [STUFieldAttribute(0xC91BE4D4)]
        public float m_C91BE4D4;

        [STUFieldAttribute(0x09CF1D87)]
        public float m_09CF1D87;

        [STUFieldAttribute(0xEF03219E)]
        public byte m_EF03219E;

        [STUFieldAttribute(0x99611934)]
        public byte m_99611934;
    }
}
