// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5903254B)]
    public class STU_5903254B : STUInstance {
        [STUFieldAttribute(0x9A08B8D3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_500EFDAC m_9A08B8D3;

        [STUFieldAttribute(0x637A3764, "m_geoSetFlags")]
        public ulong m_geoSetFlags;

        [STUFieldAttribute(0x897E6DDA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_1F272995 m_897E6DDA;

        [STUFieldAttribute(0x9C1CE114)]
        public Enum_E46F485F m_9C1CE114;

        [STUFieldAttribute(0x2610F171)]
        public Enum_78F97CE0 m_2610F171;

        [STUFieldAttribute(0xCE0A41C4)]
        public int m_CE0A41C4;

        [STUFieldAttribute(0x56840A1F)]
        public ushort m_56840A1F;
    }
}
