// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x80ED54AC)]
    public class STU_80ED54AC : STU_2679D4F3 {
        [STUFieldAttribute(0xA67F0501, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_08B59E00 m_A67F0501;
    }
}
