// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x69A9A0BA)]
    public class STU_69A9A0BA : STUInstance {
        [STUFieldAttribute(0x1D1FDD39, "m_heroes", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_D931F491[] m_heroes;

        [STUFieldAttribute(0xADF43464, "m_skins", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUSkinLink[] m_skins;

        [STUFieldAttribute(0x7F168734, "m_licenseUnlocks", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STULicenseUnlock[] m_licenseUnlocks;

        [STUFieldAttribute(0xEDDA419E, "m_lootboxes", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STULootBoxLink[] m_lootboxes;

        [STUFieldAttribute(0x4B1A5D8C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STULootBoxLink[] m_4B1A5D8C;

        [STUFieldAttribute(0xBD9F8A28, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_7D120A88[] m_BD9F8A28;

        [STUFieldAttribute(0xDB5F397C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_77A6DF8F[] m_DB5F397C;

        [STUFieldAttribute(0xA1DCB83E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_7D120A88[] m_A1DCB83E;

        [STUFieldAttribute(0xF6FFBF5B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_77A6DF8F[] m_F6FFBF5B;

        [STUFieldAttribute(0x8C7C3E19, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_7D120A88[] m_8C7C3E19;

        [STUFieldAttribute(0xEED3C77A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_0522176D[] m_EED3C77A;
    }
}
