// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA526B6EA)]
    public class STU_A526B6EA : STUInstance {
        [STUFieldAttribute(0x92209289)]
        public float m_92209289;
    }
}
