// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x20569E48)]
    public class STU_20569E48 : STUStatescriptState {
        [STUFieldAttribute(0x3D6C3A68, "m_forWeapon")]
        public teStructuredDataAssetRef<STUIdentifier> m_forWeapon;

        [STUFieldAttribute(0x7104F817, "m_dir", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_dir;

        [STUFieldAttribute(0x07D00975, "m_onEntity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_onEntity;

        [STUFieldAttribute(0x51DBF288, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_51DBF288;

        [STUFieldAttribute(0x11D07D13, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_11D07D13;

        [STUFieldAttribute(0xCED2CF74, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_CED2CF74;

        [STUFieldAttribute(0xA0ECE9E4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A0ECE9E4;

        [STUFieldAttribute(0xC97F2482)]
        public uint m_C97F2482;
    }
}
