// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0ACA861C)]
    public class STU_0ACA861C : STUInstance {
        [STUFieldAttribute(0x1F2500C6, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_1F2500C6;

        [STUFieldAttribute(0x68223050, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_68223050;

        [STUFieldAttribute(0xF12B61EA, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_F12B61EA;

        [STUFieldAttribute(0x862C517C, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_862C517C;

        [STUFieldAttribute(0x1848C4DF, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_1848C4DF;

        [STUFieldAttribute(0x6F4FF449, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_6F4FF449;

        [STUFieldAttribute(0xF646A5F3, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_F646A5F3;

        [STUFieldAttribute(0x81419565, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_81419565;

        [STUFieldAttribute(0x11FE88F4, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_11FE88F4;

        [STUFieldAttribute(0x66F9B862, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_66F9B862;

        [STUFieldAttribute(0x9FD8ACE5, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_9FD8ACE5;

        [STUFieldAttribute(0xE8DF9C73, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_E8DF9C73;

        [STUFieldAttribute(0x71D6CDC9, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_71D6CDC9;

        [STUFieldAttribute(0x06D1FD5F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_06D1FD5F;

        [STUFieldAttribute(0x98B568FC, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_98B568FC;

        [STUFieldAttribute(0xEFB2586A, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_EFB2586A;
    }
}
