// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA3AF90A7)]
    public class STU_A3AF90A7 : STU_60FFF7EE {
        [STUFieldAttribute(0x8D6F3F9E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_AEF9FC5F m_8D6F3F9E;
    }
}
