// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x6F8A55BB)]
    public class STU_6F8A55BB : STUInstance {
        [STUFieldAttribute(0x2A217ECD, "m_keys", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_89F0DBB0[] m_keys;
    }
}
