// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF536688A)]
    public class STU_F536688A : STU_27C3556F {
        [STUFieldAttribute(0x576A1360, "m_synchGroup", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5C12D7D9 m_synchGroup;

        [STUFieldAttribute(0x63658F06)]
        public ushort m_63658F06;
    }
}
