// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x10F82AA5)]
    public class STU_10F82AA5 : STU_7010A7BE {
        [STUFieldAttribute(0x335CC942, "m_data", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUModelHardpoint m_data;
    }
}
