// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x28C6A962)]
    public class STU_28C6A962 : STUAnimNode_ToTargetDirectionIK {
    }
}
