// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3AD121CD)]
    public class STU_3AD121CD : STUStatescriptAction {
        [STUFieldAttribute(0x5180E750, "m_value")]
        public Enum_09136C4C m_value;
    }
}
