// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x63F584B6)]
    public class STU_63F584B6 : STUConfigVarBoolBase {
    }
}
