// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC5B97032)]
    public class STU_C5B97032 : STUConfigVarNumeric {
        [STUFieldAttribute(0xE21D15D7, "m_controllerEntity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_controllerEntity;
    }
}
