// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x85F3A535)]
    public class STU_85F3A535 : STU_0D1DEA1C {
        [STUFieldAttribute(0xE77DBEC4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E77DBEC4;
    }
}
