// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3D58754F)]
    public class STU_3D58754F : STU_C2A01675 {
        [STUFieldAttribute(0x112A0315, "m_error", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_error;
    }
}
