// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x12FB8FAF)]
    public class STU_12FB8FAF : STU_16151658 {
        [STUFieldAttribute(0x547D9847, "m_dataFlow", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_197AA12D m_dataFlow;

        [STUFieldAttribute(0x6C95EA69)]
        public Enum_2B1F7FBB m_6C95EA69;
    }
}
