// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x350E207D)]
    public class STU_350E207D : STUStatescriptAction {
        [STUFieldAttribute(0xEEFEEC53, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EEFEEC53;

        [STUFieldAttribute(0xB5477441, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_B5477441;
    }
}
