// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x594109E1)]
    public class STU_594109E1 : STUStatescriptAction {
    }
}
