// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4B28FA23)]
    public class STU_4B28FA23 : STUStatescriptAction {
        [STUFieldAttribute(0xF50C525A, "m_targets", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_targets;

        [STUFieldAttribute(0x47B1B21F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_47B1B21F;

        [STUFieldAttribute(0x2D5B443E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2D5B443E;
    }
}
