// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x535EC683)]
    public class STU_535EC683 : STU_3F7D2DCF {
        [STUFieldAttribute(0xFBB95E89)]
        public Enum_9218D95E m_FBB95E89;
    }
}
