// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x15E1A1B9)]
    public class STU_15E1A1B9 : STUStatescriptAction {
        [STUFieldAttribute(0x93C5771D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_93C5771D;

        [STUFieldAttribute(0x652FA432, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_652FA432;

        [STUFieldAttribute(0xB0519DCB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B0519DCB;
    }
}
