// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD48DD4A6)]
    public class STU_D48DD4A6 : STU_AB86A710 {
        [STUFieldAttribute(0xFA59757D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FA59757D;

        [STUFieldAttribute(0xC0EDFA4B, "m_width", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_width;

        [STUFieldAttribute(0x4D5E07BF, "m_weight", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_weight;

        [STUFieldAttribute(0x280BF748, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_280BF748;

        [STUFieldAttribute(0x8004B1BD)]
        public Enum_1D9236F2 m_8004B1BD;
    }
}
