// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x00FCEDF7)]
    public class STU_00FCEDF7 : STU_FB8C57B1 {
        [STUFieldAttribute(0x9A1447C2)]
        public teStructuredDataAssetRef<STUEffectTrackDecal> m_9A1447C2;
    }
}
