// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x321DE7F5)]
    public class STU_321DE7F5 : STUStatescriptWeaponProjectileMotion {
        [STUFieldAttribute(0xEF2F8D70, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EF2F8D70;

        [STUFieldAttribute(0x56997212, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_56997212;
    }
}
