// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x72D70512)]
    public class STU_72D70512 : STUConfigVarBoolBase {
        [STUFieldAttribute(0x33073533, "m_possessor", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_possessor;
    }
}
