// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5E686D50)]
    public class STU_5E686D50 : STUInstance {
        [STUFieldAttribute(0x5DAE9927)]
        public teStructuredDataAssetRef<STU_5E686D50> m_5DAE9927;

        [STUFieldAttribute(0x9F64786E, "m_valMap")]
        public teStructuredDataHashMap<STU_8ED45263> m_valMap;
    }
}
