// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3C94680B)]
    public class STU_3C94680B : STU_F917340C {
        [STUFieldAttribute(0xE75BEDA5, "m_heroGUID")]
        public ulong m_heroGUID;
    }
}
