// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0C6C7A67)]
    public class STU_0C6C7A67 : STU_B553DA1C {
        [STUFieldAttribute(0x224D0677, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_224D0677;

        [STUFieldAttribute(0xB3574C63, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B3574C63;

        [STUFieldAttribute(0x9B6CD7C7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9B6CD7C7;

        [STUFieldAttribute(0x623E960B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_623E960B;
    }
}
