// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE4DF3861)]
    public class STU_E4DF3861 : STU_7010A7BE {
        [STUFieldAttribute(0x0C7B4E74)]
        public teStructuredDataAssetRef<STUEmptyAsset> m_0C7B4E74;

        [STUFieldAttribute(0x2AA1F78D, "m_color")]
        public teColorRGB m_color;

        [STUFieldAttribute(0x06BD003A)]
        public teColorRGB m_06BD003A;

        [STUFieldAttribute(0xB7631B2A)]
        public float m_B7631B2A;

        [STUFieldAttribute(0xFCA57CD2)]
        public float m_FCA57CD2;

        [STUFieldAttribute(0x2FE0F3E8)]
        public float m_2FE0F3E8;

        [STUFieldAttribute(0xF96A2001)]
        public float m_F96A2001;

        [STUFieldAttribute(0x490D86E2)]
        public float m_490D86E2;

        [STUFieldAttribute(0x9CF860A7)]
        public float m_9CF860A7;

        [STUFieldAttribute(0xBCDBAEBF)]
        public Enum_7D627D5F m_BCDBAEBF;

        [STUFieldAttribute(0xE19B14B5)]
        public byte m_E19B14B5;

        [STUFieldAttribute(0xEE4CC0A8)]
        public byte m_EE4CC0A8;

        [STUFieldAttribute(0x289E6D48)]
        public byte m_289E6D48;

        [STUFieldAttribute(0x969ADCC6)]
        public byte m_969ADCC6;

        [STUFieldAttribute(0x2E638108)]
        public byte m_2E638108;

        [STUFieldAttribute(0x93674006)]
        public byte m_93674006;
    }
}
