// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xCA21A14F)]
    public class STU_CA21A14F : STUConfigVarResource {
    }
}
