// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x05B12A1A)]
    public class STU_05B12A1A : STUConfigVarBoolBase {
        [STUFieldAttribute(0x1506E063)]
        public teStructuredDataAssetRef<STUTargetTag> m_1506E063;

        [STUFieldAttribute(0x2077E211, "m_unlock", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_unlock;
    }
}
