// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xDB1C2A69)]
    public class STU_DB1C2A69 : STU_8168B961 {
        [STUFieldAttribute(0xD829413B, "m_texture")]
        public teStructuredDataAssetRef<STUTexture> m_texture;

        [STUFieldAttribute(0xB7631B2A)]
        public float m_B7631B2A;
    }
}
