// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8F76A28C)]
    public class STU_8F76A28C : STUStatescriptAction {
        [STUFieldAttribute(0x695C8004, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_695C8004;

        [STUFieldAttribute(0x0CFC7D02, "m_target", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_target;

        [STUFieldAttribute(0x34F116C8, "m_behavior")]
        public Enum_72A04DB8 m_behavior;
    }
}
