// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFEBB0DB6)]
    public class STU_FEBB0DB6 : STUInstance {
        [STUFieldAttribute(0x7AACB98B)]
        public byte[] m_7AACB98B;

        [STUFieldAttribute(0xD3DF533D, "m_sourcePlatform")]
        public uint m_sourcePlatform;
    }
}
