// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5EFAE015)]
    public class STU_5EFAE015 : STUStatescriptAction {
        [STUFieldAttribute(0xDE466214, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_DE466214;

        [STUFieldAttribute(0x783169A0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_783169A0;
    }
}
