// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x07167219)]
    public class STU_07167219 : STUStatescriptState {
        [STUFieldAttribute(0x0C7B4E74, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0C7B4E74;
    }
}
