// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x26571E59)]
    public class STU_26571E59 : STUStatescriptStateUXScreen {
    }
}
