// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC2D1284D)]
    public class STU_C2D1284D : STU_A320B236 {
        [STUFieldAttribute(0xC96FBC4D)]
        public teEntityID[] m_C96FBC4D;

        [STUFieldAttribute(0xEF9AFD2D)]
        public ulong[] m_EF9AFD2D;

        [STUFieldAttribute(0x1D13928C, "m_mapGUID")]
        public ulong m_mapGUID;

        [STUFieldAttribute(0xCEA0E259)]
        public teEntityID m_CEA0E259;
    }
}
