// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x82972D9D)]
    public class STU_82972D9D : STUConfigVarResource {
    }
}
