// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x63C25B10)]
    public class STU_63C25B10 : STUConfigVarResource {
    }
}
