// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x62918E37)]
    public class STU_62918E37 : STU_EE48F03A {
        [STUFieldAttribute(0x91C740BC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUGraphPlug m_91C740BC;

        [STUFieldAttribute(0x12716D08, "m_type")]
        public Enum_3FB25082 m_type;
    }
}
