// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC3836610)]
    public class STU_C3836610 : STUStatescriptStateUXPresenter {
        [STUFieldAttribute(0x0978DD95, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0978DD95;
    }
}
