// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x04476E5C)]
    public class STU_04476E5C : STUStatescriptState {
        [STUFieldAttribute(0xFD6F6D19, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FD6F6D19;
    }
}
