// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x2785FBDD)]
    public class STU_2785FBDD : STUStatescriptState {
        [STUFieldAttribute(0x2AA1F78D, "m_color", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_color;

        [STUFieldAttribute(0x78970EF2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_78970EF2;

        [STUFieldAttribute(0x70562E7C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_70562E7C;

        [STUFieldAttribute(0xEF1C0E48, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EF1C0E48;

        [STUFieldAttribute(0x2F50D884, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2F50D884;

        [STUFieldAttribute(0x7A7C9915, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7A7C9915;

        [STUFieldAttribute(0x3FA1152E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3FA1152E;
    }
}
