// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x25F0C049)]
    public class STU_25F0C049 : STUConfigVarNumeric {
        [STUFieldAttribute(0x0043FC65, "m_payloadEntity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_payloadEntity;

        [STUFieldAttribute(0xB0519DCB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B0519DCB;
    }
}
