// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x09FB0449)]
    public class STU_09FB0449 : STUStatescriptState {
        [STUFieldAttribute(0xC97F2482)]
        public uint m_C97F2482;
    }
}
