// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x02AC92B2)]
    public class STU_02AC92B2 : STU_F0900F0C {
        [STUFieldAttribute(0xDF482E2D, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_7059BA29 m_DF482E2D;

        [STUFieldAttribute(0xE3072BFB, "m_condition", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_16151658 m_condition;
    }
}
