// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA257245A)]
    public class STU_A257245A : STUStatescriptAction {
        [STUFieldAttribute(0xF50C525A, "m_targets", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_targets;

        [STUFieldAttribute(0x526640D9, "m_teamIndex", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_teamIndex;
    }
}
