// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x221F6FB0)]
    public class STU_221F6FB0 : STUConfigVarBoolBase {
    }
}
