// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x17712B95)]
    public class STU_17712B95 : STU_EE48F03A {
        [STUFieldAttribute(0xDA37BCF8, "m_hardPoint", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_680F51B4 m_hardPoint;

        [STUFieldAttribute(0xBF236513, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_354E9F5F m_BF236513;

        [STUFieldAttribute(0x12716D08, "m_type", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_076F907E m_type;
    }
}
