// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7067FCEE)]
    public class STU_7067FCEE : STU_2CAA4AFB {
        [STUFieldAttribute(0xF072EAAB)]
        public teStructuredDataAssetRef<STUIdentifier> m_F072EAAB;
    }
}
