// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF9E400EC)]
    public class STU_F9E400EC : STUConfigVarNumeric {
        [STUFieldAttribute(0x0CFC7D02, "m_target", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_target;

        [STUFieldAttribute(0xCAB08616, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_CAB08616;

        [STUFieldAttribute(0xF1AD8CC3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F1AD8CC3;
    }
}
