// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD824C72B)]
    public class STU_D824C72B : STUConfigVarVecBase {
        [STUFieldAttribute(0x7108ECE0, "m_id", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_id;
    }
}
