// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC2E4A7F7)]
    public class STU_C2E4A7F7 : STUStatescriptAction {
    }
}
