// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD83702BD)]
    public class STU_D83702BD : STUInstance {
        [STUFieldAttribute(0xCBEF5AF9)]
        public teStructuredDataAssetRef<STU_4B034326>[] m_CBEF5AF9;

        [STUFieldAttribute(0x7CAAB050, "m_publicSchema", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptSchema m_publicSchema;
    }
}
