// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x991F8EB1)]
    public class STU_991F8EB1 : STUStatescriptAction {
        [STUFieldAttribute(0x441190F0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_441190F0;

        [STUFieldAttribute(0x0CFC7D02, "m_target", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_target;
    }
}
