// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBAB6A1E6)]
    public class STU_BAB6A1E6 : STU_9E8DF6A9 {
        [STUFieldAttribute(0x9AE726B3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_9AE726B3;
    }
}
