// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE53CE4BA)]
    public class STU_E53CE4BA : STU_8168B961 {
        [STUFieldAttribute(0xD829413B, "m_texture")]
        public teStructuredDataAssetRef<STUTexture> m_texture;
    }
}
