// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9320731B)]
    public class STU_9320731B : STUStatescriptAction {
    }
}
