// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x941811C7)]
    public class STU_941811C7 : STUStatescriptStateUXPresenter {
    }
}
