// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xCD396790)]
    public class STU_CD396790 : STUStatescriptState {
        [STUFieldAttribute(0x6B7C7D86, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6B7C7D86;

        [STUFieldAttribute(0xB4FE98D8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B4FE98D8;

        [STUFieldAttribute(0x9D9D030F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_9D9D030F;

        [STUFieldAttribute(0x69AFA3BE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_69AFA3BE;

        [STUFieldAttribute(0x3ECDFC9F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_3ECDFC9F;

        [STUFieldAttribute(0x41BA609A, "m_onAbortPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onAbortPlug;

        [STUFieldAttribute(0xFE841C79, "m_onFinishedPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onFinishedPlug;

        [STUFieldAttribute(0x47E1781C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_24AB1F0B m_47E1781C;
    }
}
