// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC238FBC7)]
    public class STU_C238FBC7 : STUConfigVarStringBase {
        [STUFieldAttribute(0x5180E750, "m_value")]
        public teString m_value;
    }
}
