// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB31B9696)]
    public class STU_B31B9696 : STUInstance {
        [STUFieldAttribute(0xCECBEA34)]
        public teStructuredDataAssetRef<STUSound> m_CECBEA34;

        [STUFieldAttribute(0x20F548DF)]
        public teStructuredDataAssetRef<STUSound> m_20F548DF;

        [STUFieldAttribute(0x49ED9C29)]
        public teStructuredDataAssetRef<STUSound> m_49ED9C29;
    }
}
