// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x2137EED1)]
    public class STU_2137EED1 : STU_8B07626D {
        [STUFieldAttribute(0x1BC89B24, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimBlendDriverParam m_1BC89B24;

        [STUFieldAttribute(0x10EAE00D, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_CFB183E4 m_10EAE00D;

        [STUFieldAttribute(0x63658F06)]
        public ushort m_63658F06;

        [STUFieldAttribute(0x27196F53)]
        public byte m_27196F53;

        [STUFieldAttribute(0xB8043C11)]
        public byte m_B8043C11;
    }
}
