// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD7F0E8E2)]
    public class STU_D7F0E8E2 : STU_C3836610 {
        [STUFieldAttribute(0x21C9D8B7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_21C9D8B7;

        [STUFieldAttribute(0xA1B263E1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A1B263E1;

        [STUFieldAttribute(0x12AA58B2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_12AA58B2;
    }
}
