// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB90243CD)]
    public class STU_B90243CD : STUStatescriptAction {
        [STUFieldAttribute(0x8F57256D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8F57256D;

        [STUFieldAttribute(0x6790B0BD, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6790B0BD;
    }
}
