// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x78610A60)]
    public class STU_78610A60 : STU_425A5849 {
        [STUFieldAttribute(0x2437B941, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_68B8A85E[] m_2437B941;

        [STUFieldAttribute(0x414BF5CB)]
        public byte m_414BF5CB;
    }
}
