// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF8B27EC4)]
    public class STU_F8B27EC4 : STUStatescriptAction {
    }
}
