// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x34828B2A)]
    public class STU_34828B2A : STU_34493776 {
        [STUFieldAttribute(0xF9EFF706, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarVec2 m_F9EFF706;

        [STUFieldAttribute(0x1399982E, "m_offset", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarVec2 m_offset;
    }
}
