// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x19D76AFA)]
    public class STU_19D76AFA : STU_B553DA1C {
        [STUFieldAttribute(0x7BA13C20, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7BA13C20;

        [STUFieldAttribute(0x82FA1A25, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_82FA1A25;

        [STUFieldAttribute(0x36EFFC73, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_36EFFC73;

        [STUFieldAttribute(0x623E960B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_623E960B;
    }
}
