// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7C137342)]
    public class STU_7C137342 : STUConfigVarBoolBase {
        [STUFieldAttribute(0x71F08422, "m_breakableEntity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_breakableEntity;
    }
}
