// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x127D9492)]
    public class STU_127D9492 : STU_AC2D7ABE {
        [STUFieldAttribute(0x4B82BE57, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4B82BE57;

        [STUFieldAttribute(0xF0F5DA3A, "m_weaponID", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_weaponID;

        [STUFieldAttribute(0xC4DD2493, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C4DD2493;
    }
}
