// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x35D1CEBB)]
    public class STU_35D1CEBB : STU_7010A7BE {
        [STUFieldAttribute(0xA5249DE6, "m_text")]
        public teStructuredDataAssetRef<ulong> m_text;

        [STUFieldAttribute(0x4E3B32F3, "m_font")]
        public teStructuredDataAssetRef<ulong> m_font;

        [STUFieldAttribute(0x73E4C3ED, "m_material")]
        public teStructuredDataAssetRef<ulong> m_material;
    }
}
