// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x398F75A6)]
    public class STU_398F75A6 : STUGenericSettings_Base {
        [STUFieldAttribute(0x6DB997F5, "m_graphData")]
        public teStructuredDataHashMap<STU_B6A897FA> m_graphData;
    }
}
