// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA82DEB0A)]
    public class STU_A82DEB0A : STU_82C74C1D {
        [STUFieldAttribute(0xC08C4427, "m_name")]
        public teString m_name;

        [STUFieldAttribute(0x9A1447C2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_86A2F05D m_9A1447C2;
    }
}
