// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF8A5E077)]
    public class STU_F8A5E077 : STUInstance {
        [STUFieldAttribute(0x5AFAC781)]
        public teStructuredDataAssetRef<STU_4B034326>[] m_5AFAC781;

        [STUFieldAttribute(0x4D5979CC)]
        public ulong m_4D5979CC;

        [STUFieldAttribute(0x3A5E495A)]
        public ulong m_3A5E495A;

        [STUFieldAttribute(0x9AB20571, "m_fileSize")]
        public uint m_fileSize;

        [STUFieldAttribute(0x302B9796)]
        public uint m_302B9796;
    }
}
