// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xCBA6F4E5)]
    public class STU_CBA6F4E5 : STU_2CAA4AFB {
        [STUFieldAttribute(0xF072EAAB)]
        public teStructuredDataAssetRef<STUEffectTemplateCondition> m_F072EAAB;

        [STUFieldAttribute(0xAC716351)]
        public teStructuredDataAssetRef<STUIdentifier> m_AC716351;

        [STUFieldAttribute(0xB64ECFF9)]
        public teStructuredDataAssetRef<STUIdentifier>[] m_B64ECFF9;

        [STUFieldAttribute(0x2FC537D0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A1DF5CE6[] m_2FC537D0;

        [STUFieldAttribute(0x34661125)]
        public byte m_34661125;

        [STUFieldAttribute(0xD23242C7)]
        public byte m_D23242C7;

        [STUFieldAttribute(0x553F6E9A)]
        public byte m_553F6E9A;
    }
}
