// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0C28FBEB)]
    public class STU_0C28FBEB : STUConfigVarNumeric {
    }
}
