// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x1AD9ADE2)]
    public class STU_1AD9ADE2 : STUGameModeLegacy {
    }
}
