// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x62A0012F)]
    public class STU_62A0012F : STUStatescriptState {
        [STUFieldAttribute(0x48382539, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_653419D9[] m_48382539;

        [STUFieldAttribute(0x5C967329, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar[] m_5C967329;

        [STUFieldAttribute(0x48CEBBB6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_48CEBBB6;

        [STUFieldAttribute(0xC4B22E85, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C4B22E85;

        [STUFieldAttribute(0x0C330621, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0C330621;

        [STUFieldAttribute(0x261852A2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_24AB1F0B m_261852A2;

        [STUFieldAttribute(0xB0368640, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_B0368640;
    }
}
