// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA88E00D8)]
    public class STU_A88E00D8 : STUConfigVarBoolBase {
        [STUFieldAttribute(0xA23431E3)]
        public Enum_26629D7F m_A23431E3;
    }
}
