// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9F5C2321)]
    public class STU_9F5C2321 : STU_C2A01675 {
        [STUFieldAttribute(0xB206AAFE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_B206AAFE;

        [STUFieldAttribute(0x093BF2B2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_093BF2B2;
    }
}
