// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x2E7352B8)]
    public class STU_2E7352B8 : STUInstance {
        [STUFieldAttribute(0x60FA1506, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_BF897040 m_60FA1506;

        [STUFieldAttribute(0xF9F344BC, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_BF897040 m_F9F344BC;

        [STUFieldAttribute(0x8EF4742A, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_BF897040 m_8EF4742A;

        [STUFieldAttribute(0x1090E189, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_BF897040 m_1090E189;

        [STUFieldAttribute(0x6797D11F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_BF897040 m_6797D11F;

        [STUFieldAttribute(0xFE9E80A5, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_BF897040 m_FE9E80A5;

        [STUFieldAttribute(0x8999B033, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_BF897040 m_8999B033;

        [STUFieldAttribute(0x1926ADA2, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_BF897040 m_1926ADA2;

        [STUFieldAttribute(0xB326500E, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_BF897040 m_B326500E;

        [STUFieldAttribute(0xDC85042F)]
        public teColorRGB m_DC85042F;

        [STUFieldAttribute(0x4A72D8A6)]
        public teColorRGB m_4A72D8A6;

        [STUFieldAttribute(0xF54DB0DD)]
        public teColorRGB m_F54DB0DD;

        [STUFieldAttribute(0xA14563A5)]
        public teColorRGB m_A14563A5;

        [STUFieldAttribute(0x5B25214C)]
        public teColorRGB m_5B25214C;

        [STUFieldAttribute(0x4E87089B)]
        public teColorRGB m_4E87089B;

        [STUFieldAttribute(0xA6DCD939)]
        public teColorRGB m_A6DCD939;

        [STUFieldAttribute(0xAC5B13E2)]
        public teColorRGB m_AC5B13E2;

        [STUFieldAttribute(0x08B448A8)]
        public teColorRGB m_08B448A8;

        [STUFieldAttribute(0x439978DC)]
        public teColorRGB m_439978DC;

        [STUFieldAttribute(0x217CFC5A)]
        public teColorRGB m_217CFC5A;

        [STUFieldAttribute(0xA8AEC3DF)]
        public teColorRGB m_A8AEC3DF;

        [STUFieldAttribute(0x8F146DCB)]
        public teColorRGB m_8F146DCB;

        [STUFieldAttribute(0x476CA8E1)]
        public teColorRGB m_476CA8E1;

        [STUFieldAttribute(0x01FE0AF1)]
        public teColorRGB m_01FE0AF1;

        [STUFieldAttribute(0xB667F36C)]
        public teColorRGB m_B667F36C;

        [STUFieldAttribute(0xE806BB00)]
        public teColorRGB m_E806BB00;

        [STUFieldAttribute(0x38C4DAFF)]
        public teColorRGB m_38C4DAFF;

        [STUFieldAttribute(0xFD05393B)]
        public float m_FD05393B;
    }
}
