// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8AC8926D)]
    public class STU_8AC8926D : STU_988BCA34 {
        [STUFieldAttribute(0xF718EB97)]
        public teStructuredDataAssetRef<STUAnimation> m_F718EB97;

        [STUFieldAttribute(0xD1FBEB15)]
        public float m_D1FBEB15;

        [STUFieldAttribute(0x81D481DE)]
        public float m_81D481DE;

        [STUFieldAttribute(0x51956F34)]
        public float m_51956F34;

        [STUFieldAttribute(0x625946AA)]
        public byte m_625946AA;
    }
}
