// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0623796F)]
    public class STU_0623796F : STU_FFBBD692 {
        [STUFieldAttribute(0x1D56AE73)]
        public float m_1D56AE73;

        [STUFieldAttribute(0xCBE50973)]
        public float m_CBE50973;

        [STUFieldAttribute(0x2D85A692)]
        public float m_2D85A692;

        [STUFieldAttribute(0xC826015D)]
        public Enum_06644C8D m_C826015D;

        [STUFieldAttribute(0xBBC7A362)]
        public float m_BBC7A362;

        [STUFieldAttribute(0xC169C7E3)]
        public float m_C169C7E3;

        [STUFieldAttribute(0x92A4A242)]
        public byte m_92A4A242;
    }
}
