// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x67C71938)]
    public class STU_67C71938 : STU_D5EE5EA3 {
        [STUFieldAttribute(0xC79A0A34, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_3BD7006B m_C79A0A34;

        [STUFieldAttribute(0x003CEE5C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_003CEE5C;

        [STUFieldAttribute(0x320A8CDE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_320A8CDE;
    }
}
