// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3774E4F8)]
    public class STU_3774E4F8 : STU_90C195E7 {
        [STUFieldAttribute(0x94DF8DB3, "m_input", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_input;

        [STUFieldAttribute(0x426DC447, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_426DC447;

        [STUFieldAttribute(0x22A860F8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_22A860F8;
    }
}
