// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4A77E7A0)]
    public class STU_4A77E7A0 : STUStatescriptState {
        [STUFieldAttribute(0xF9045E7A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F9045E7A;
    }
}
