// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xDE8C8AAB)]
    public class STU_DE8C8AAB : STU_1F272995 {
        [STUFieldAttribute(0x84CB13D8)]
        public float m_84CB13D8;

        [STUFieldAttribute(0x710E027F)]
        public float m_710E027F;

        [STUFieldAttribute(0x1D56AE73)]
        public float m_1D56AE73;

        [STUFieldAttribute(0xC8AFA6A7)]
        public float m_C8AFA6A7;

        [STUFieldAttribute(0x98520DF9)]
        public float m_98520DF9;

        [STUFieldAttribute(0x52B41E6D)]
        public float m_52B41E6D;

        [STUFieldAttribute(0xDA112434)]
        public float m_DA112434;

        [STUFieldAttribute(0xF66AD146)]
        public float m_F66AD146;

        [STUFieldAttribute(0x4F2C41CD)]
        public float m_4F2C41CD;

        [STUFieldAttribute(0xA4617625)]
        public float m_A4617625;

        [STUFieldAttribute(0x4EF3D9E1)]
        public float m_4EF3D9E1;

        [STUFieldAttribute(0x7158EE8B)]
        public float m_7158EE8B;

        [STUFieldAttribute(0xD8FD19EB)]
        public Enum_6CDCFA6B m_D8FD19EB;

        [STUFieldAttribute(0x8E8B0406)]
        public Enum_6CDCFA6B m_8E8B0406;

        [STUFieldAttribute(0xB9C0D00A, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_CC74541B m_B9C0D00A;

        [STUFieldAttribute(0x10FE8708, "m_server")]
        public byte m_server;

        [STUFieldAttribute(0x01F05DB3)]
        public byte m_01F05DB3;

        [STUFieldAttribute(0x246BBC05)]
        public byte m_246BBC05;
    }
}
