// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8E78F3D3)]
    public class STU_8E78F3D3 : STU_054BC7E8 {
        [STUFieldAttribute(0xCEFDC1B2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_CEFDC1B2;
    }
}
