// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB553DA1C)]
    public class STU_B553DA1C : STU_F778EA2F {
        [STUFieldAttribute(0x1856BAB7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1856BAB7;
    }
}
