// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xEC5E5B8E)]
    public class STU_EC5E5B8E : STU_B553DA1C {
        [STUFieldAttribute(0x511FEC01, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_511FEC01;

        [STUFieldAttribute(0x8BA08651, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8BA08651;

        [STUFieldAttribute(0x92E298EF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_92E298EF;

        [STUFieldAttribute(0xC51825EA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C51825EA;

        [STUFieldAttribute(0xC6EBC5A5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C6EBC5A5;

        [STUFieldAttribute(0x5819C2C1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5819C2C1;

        [STUFieldAttribute(0xFCC5993E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FCC5993E;

        [STUFieldAttribute(0x4C36BCC3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4C36BCC3;
    }
}
