// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4EE9DD1B)]
    public class STU_4EE9DD1B : STUEntityComponent {
        [STUFieldAttribute(0xB4D30E27)]
        public byte m_B4D30E27;
    }
}
