// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8BC81CD7)]
    public class STU_8BC81CD7 : STUGenericSettings_Base {
        [STUFieldAttribute(0xEA69C274)]
        public teStructuredDataAssetRef<ulong>[] m_EA69C274;
    }
}
