// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE9AC5B41)]
    public class STU_E9AC5B41 : STUStatescriptState {
    }
}
