// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x670CF926)]
    public class STU_670CF926 : STUStatescriptAction {
        [STUFieldAttribute(0xF13BA264, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F13BA264;

        [STUFieldAttribute(0x7F0DDBB5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7F0DDBB5;
    }
}
