// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x11A76BFE)]
    public class STU_11A76BFE : STUWaterType {
        [STUFieldAttribute(0xCC6FEC51)]
        public teStructuredDataAssetRef<STUTexture> m_CC6FEC51;

        [STUFieldAttribute(0x6B163A1A)]
        public teStructuredDataAssetRef<STUTexture> m_6B163A1A;

        [STUFieldAttribute(0xC95372A1)]
        public teStructuredDataAssetRef<STUTexture> m_C95372A1;

        [STUFieldAttribute(0x14D037D7)]
        public teColorRGBA m_14D037D7;

        [STUFieldAttribute(0xFA1249DC)]
        public teColorRGBA m_FA1249DC;

        [STUFieldAttribute(0x43D14192, "m_speed")]
        public float m_speed;

        [STUFieldAttribute(0xD3215CD6)]
        public float m_D3215CD6;

        [STUFieldAttribute(0xA3E01FAE)]
        public Enum_5ED1EED9 m_A3E01FAE;

        [STUFieldAttribute(0x26DBE9C9)]
        public Enum_5ED1EED9 m_26DBE9C9;

        [STUFieldAttribute(0x3B5449FF)]
        public float m_3B5449FF;

        [STUFieldAttribute(0xD0E2D9FA)]
        public float m_D0E2D9FA;

        [STUFieldAttribute(0x6030C531)]
        public float m_6030C531;

        [STUFieldAttribute(0x700224B1)]
        public float m_700224B1;

        [STUFieldAttribute(0x82C16513)]
        public float m_82C16513;
    }
}
