// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x27984FC9)]
    public class STU_27984FC9 : STUStatescriptState {
        [STUFieldAttribute(0xEDFB51D3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EDFB51D3;

        [STUFieldAttribute(0x5180E750, "m_value", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_value;

        [STUFieldAttribute(0xB9C3741E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_B9C3741E;

        [STUFieldAttribute(0x6F5B7AA1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6F5B7AA1;
    }
}
