// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x359C04F0)]
    public class STU_359C04F0 : STU_529F45C0 {
        [STUFieldAttribute(0xD120D20C, "m_input1", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_input1;

        [STUFieldAttribute(0x482983B6, "m_input2", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_input2;

        [STUFieldAttribute(0xA7ABBEFE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_A7ABBEFE;
    }
}
