// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x459D085A)]
    public class STU_459D085A : STU_F910F2BE {
        [STUFieldAttribute(0x71EF3CA4, "m_radius", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_radius;
    }
}
