// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xDC590ECB)]
    public class STU_DC590ECB : STUStatescriptAction {
    }
}
