// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x92F7915F)]
    public class STU_92F7915F : STUStatescriptState {
        [STUFieldAttribute(0xD6E55AD9, "m_logicalButtons")]
        public STULogicalButton[] m_logicalButtons;
    }
}
