// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x46513A83)]
    public class STU_46513A83 : STUInstance {
        [STUFieldAttribute(0xC08C4427, "m_name")]
        public teStructuredDataAssetRef<STUIdentifier> m_name;

        [STUFieldAttribute(0x94DF8DB3, "m_input", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_input;
    }
}
