// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA068B364)]
    public class STU_A068B364 : STUStatescriptAction {
        [STUFieldAttribute(0x3C644A89, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3C644A89;
    }
}
