// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7C10B7D5)]
    public class STU_7C10B7D5 : STUConfigVarBoolBase {
        [STUFieldAttribute(0xBD052C19, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BD052C19;

        [STUFieldAttribute(0x9CD6523F, "m_skin", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_skin;
    }
}
