// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x23E6F020)]
    public class STU_23E6F020 : STUConfigVarVecBase {
        [STUFieldAttribute(0x4A0D3E2E, "m_volumeID", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_volumeID;
    }
}
