// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB433EB4E)]
    public class STU_B433EB4E : STUConfigVarBoolBase {
    }
}
