// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x6385FC4C)]
    public class STU_6385FC4C : STUConfigVarResource {
        [STUFieldAttribute(0x62363E46, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_62363E46;
    }
}
