// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x830CC992)]
    public class STU_830CC992 : STUStatescriptStateUXPresenter {
        [STUFieldAttribute(0xCECF1833, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_CECF1833;
    }
}
