// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0E2B24D8)]
    public class STU_0E2B24D8 : STUAnimNode_Base {
        [STUFieldAttribute(0x4C37B035, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5C12D7D9 m_4C37B035;

        [STUFieldAttribute(0xAECD07C2, "m_children", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_1359915D[] m_children;
    }
}
