// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xDD38DCB5)]
    public class STU_DD38DCB5 : STU_16151658 {
        [STUFieldAttribute(0x547D9847, "m_dataFlow", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_197AA12D m_dataFlow;

        [STUFieldAttribute(0x0916AFB9, "m_category", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_AE8E14DB m_category;

        [STUFieldAttribute(0x2637641F)]
        public byte m_2637641F;

        [STUFieldAttribute(0x30BA5982)]
        public byte m_30BA5982;
    }
}
