// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA931A82F)]
    public class STU_A931A82F : STU_E4CC91FE {
        [STUFieldAttribute(0x5180E750, "m_value")]
        public float m_value;
    }
}
