// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA54C33C3)]
    public class STU_A54C33C3 : STU_AC312A6D {
        [STUFieldAttribute(0x43D14192, "m_speed", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_speed;

        [STUFieldAttribute(0xA7D21004, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A7D21004;

        [STUFieldAttribute(0x9214D627, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9214D627;

        [STUFieldAttribute(0x2AA1F78D, "m_color", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_color;
    }
}
