// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x241069EF)]
    public class STU_241069EF : STUStatescriptState {
        [STUFieldAttribute(0x87089166, "m_targetEntity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_targetEntity;

        [STUFieldAttribute(0x0DB9C634, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_0DB9C634;

        [STUFieldAttribute(0x2C75F177, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2C75F177;

        [STUFieldAttribute(0x20623CAB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_20623CAB;

        [STUFieldAttribute(0xC99C08F2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C99C08F2;

        [STUFieldAttribute(0x5D56BF0C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5D56BF0C;
    }
}
