// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8F0A313A)]
    public class STU_8F0A313A : STU_52D8FB50 {
        [STUFieldAttribute(0x635376AC)]
        public byte m_635376AC;
    }
}
