// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x721C3966)]
    public class STU_721C3966 : STUConfigVarIntBase {
        [STUFieldAttribute(0xF8B6C20E)]
        public Enum_142DBE75 m_F8B6C20E;
    }
}
