// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE625E875)]
    public class STU_E625E875 : STU_49DE045A {
        [STUFieldAttribute(0x94DF8DB3, "m_input", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_17C5B4F7 m_input;
    }
}
