// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x19F7669C)]
    public class STU_19F7669C : STUInstance {
        [STUFieldAttribute(0x51639597, ReaderType = typeof(InlineInstanceFieldReader))]
        public LineupOverrideCharacter[] m_51639597;

        [STUFieldAttribute(0xB0B7ADD2)]
        public teStructuredDataAssetRef<STUIdentifier> m_B0B7ADD2;
    }
}
