// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8D5EA778)]
    public class STU_8D5EA778 : STU_BB5480D2 {
        [STUFieldAttribute(0x29632215, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5CDD7AE5 m_29632215;
    }
}
