// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x45861759)]
    public class STU_45861759 : STUConfigVarBoolBase {
    }
}
