// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x79285394)]
    public class STU_79285394 : STU_988BCA34 {
        [STUFieldAttribute(0x4E215304)]
        public teStructuredDataAssetRef<STUAnimation> m_4E215304;

        [STUFieldAttribute(0x391C3C37, "m_jump")]
        public teStructuredDataAssetRef<STUAnimation> m_jump;

        [STUFieldAttribute(0x60106E6A)]
        public teStructuredDataAssetRef<STUAnimation> m_60106E6A;

        [STUFieldAttribute(0x9AD9250E)]
        public teStructuredDataAssetRef<STUAnimation> m_9AD9250E;

        [STUFieldAttribute(0x54161545, "m_globalWeightMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalWeightMultipliers m_globalWeightMultipliers;

        [STUFieldAttribute(0xE57007D5, "m_userWeights", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimUserWeights m_userWeights;

        [STUFieldAttribute(0x94166C37, "m_globalLayerMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGlobalLayerMultipliers m_globalLayerMultipliers;

        [STUFieldAttribute(0x553C811C)]
        public float m_553C811C;

        [STUFieldAttribute(0xD1854934)]
        public float m_D1854934;

        [STUFieldAttribute(0xCC8149B8)]
        public float m_CC8149B8;

        [STUFieldAttribute(0x9A702D02)]
        public float m_9A702D02;

        [STUFieldAttribute(0xA978D468)]
        public byte m_A978D468;

        [STUFieldAttribute(0x956C6B18)]
        public byte m_956C6B18;

        [STUFieldAttribute(0x8C6A9ADF)]
        public byte m_8C6A9ADF;
    }
}
