// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x84D75206)]
    public class STU_84D75206 : STU_5CCBDE61 {
        [STUFieldAttribute(0xD9813284, "m_maps")]
        public teStructuredDataAssetRef<STUMap>[] m_maps;
    }
}
