// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xEEB8A2B1)]
    public class STU_EEB8A2B1 : STU_8EF1C54B {
        [STUFieldAttribute(0x44BB1696, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;

        [STUFieldAttribute(0xDA37BCF8, "m_hardPoint", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_hardPoint;

        [STUFieldAttribute(0x1399982E, "m_offset", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_offset;

        [STUFieldAttribute(0xF76EB21B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F76EB21B;
    }
}
