// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5179B279)]
    public class STU_5179B279 : STUStatescriptAction {
        [STUFieldAttribute(0x5D633127, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_5D633127;
    }
}
