// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x2DDCA413)]
    public class STU_2DDCA413 : STUAILevelPlacedMetaData {
    }
}
