// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x370DA9D6)]
    public class STU_370DA9D6 : STUConfigVarStringBase {
        [STUFieldAttribute(0x7095FEC3)]
        public Enum_420ADBDC m_7095FEC3;
    }
}
