// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x2C03638E)]
    public class STU_2C03638E : STUInstance {
        [STUFieldAttribute(0xC08C4427, "m_name")]
        public teStructuredDataAssetRef<ulong> m_name;

        [STUFieldAttribute(0x89CABB3B)]
        public teStructuredDataAssetRef<ulong> m_89CABB3B;

        [STUFieldAttribute(0xA170ADA1, "m_rulesets")]
        public teStructuredDataAssetRef<STUGameRuleset>[] m_rulesets;
    }
}
