// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7ECEFF3A)]
    public class STU_7ECEFF3A : STUStatescriptState {
        [STUFieldAttribute(0x87089166, "m_targetEntity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_targetEntity;

        [STUFieldAttribute(0x8F7D5784)]
        public Enum_214AE238 m_8F7D5784;
    }
}
