// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD879ED22)]
    public class STU_D879ED22 : STUConfigVarBoolBase {
    }
}
