// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x1E0F81B5)]
    public class STU_1E0F81B5 : STUStatescriptAction {
        [STUFieldAttribute(0x354F93FB, "m_success", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_success;

        [STUFieldAttribute(0x7BD44F88, "m_failure", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_failure;
    }
}
