// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7083B59F)]
    public class STU_7083B59F : STUConfigVarIterable {
        [STUFieldAttribute(0x65CE2851, "m_configVars", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar[] m_configVars;
    }
}
