// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBEE9571D)]
    public class STU_BEE9571D : STU_B553DA1C {
        [STUFieldAttribute(0x57BA0190, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_57BA0190;

        [STUFieldAttribute(0xE3FF9BC4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E3FF9BC4;

        [STUFieldAttribute(0xDFF2A49D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_DFF2A49D;

        [STUFieldAttribute(0x5819C2C1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5819C2C1;

        [STUFieldAttribute(0xFC08B907, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FC08B907;

        [STUFieldAttribute(0x879D7882, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_879D7882;

        [STUFieldAttribute(0xBFFA64F6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_BFFA64F6;

        [STUFieldAttribute(0x028FABC5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_97BC16DA m_028FABC5;

        [STUFieldAttribute(0x265FF2A5)]
        public Enum_36617F65 m_265FF2A5;
    }
}
