// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x63905843)]
    public class STU_63905843 : STUMirroredEntityComponent {
    }
}
