// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x954B6D02)]
    public class STU_954B6D02 : STU_D5EE5EA3 {
        [STUFieldAttribute(0xC79A0A34, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_771B5A3F m_C79A0A34;

        [STUFieldAttribute(0xB5921B80, "m_crouchMovement", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_crouchMovement;

        [STUFieldAttribute(0xCAE5A1E6, "m_crouch", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_crouch;

        [STUFieldAttribute(0xFB87238F, "m_movement", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_movement;

        [STUFieldAttribute(0xB9114C96, "m_default", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_382582B6 m_default;
    }
}
