// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD73B4FD6)]
    public class STU_D73B4FD6 : STU_01B57CB8 {
        [STUFieldAttribute(0x0DF06BF9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_60FFF7EE m_0DF06BF9;
    }
}
