// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x70922D2A, "STUAIPointFinderComponent")]
    public class STUAIPointFinderComponent : STUEntityComponent {
    }
}
