// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x41066CD6, "STUAutomationWaypointComponent")]
    public class STUAutomationWaypointComponent : STUEntityComponent {
    }
}
