// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3A52E271, "STUAnimBlendTree_PlayAnimCancelCategory")]
    public class STUAnimBlendTree_PlayAnimCancelCategory : STUInstance {
        [STUFieldAttribute(0x0916AFB9, "m_category")]
        public teStructuredDataAssetRef<STUAnimCategory> m_category;

        [STUFieldAttribute(0xD00EA700)]
        public byte m_D00EA700;
    }
}
