// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x2207633B, "STUAreaInstanceData")]
    public class STUAreaInstanceData : STUComponentInstanceData {
        [STUFieldAttribute(0x493B0749)]
        public teUUID m_493B0749;
    }
}
