// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF1BACBD3, "STUAILevelPlacedMetaDataInstanceData")]
    public class STUAILevelPlacedMetaDataInstanceData : STUComponentInstanceData {
        [STUFieldAttribute(0x404E826C, "m_metaData", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUAILevelPlacedMetaData m_metaData;
    }
}
