// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC60F5243, "STUAnimCategory")]
    public class STUAnimCategory : STUInstance {
        [STUFieldAttribute(0x4A96655A)]
        public uint[] m_4A96655A;
    }
}
