// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x985AC62C, "STUAnimUserWeights")]
    public class STUAnimUserWeights : STUInstance {
        [STUFieldAttribute(0x7DA22769)]
        public float m_7DA22769;

        [STUFieldAttribute(0xE4AB76D3)]
        public float m_E4AB76D3;

        [STUFieldAttribute(0x93AC4645)]
        public float m_93AC4645;

        [STUFieldAttribute(0x0DC8D3E6)]
        public float m_0DC8D3E6;
    }
}
