// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x56CB768B, "STUAnimOverrideBlendTime")]
    public class STUAnimOverrideBlendTime : STUInstance {
        [STUFieldAttribute(0x428B9FC4, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_7059BA29 m_428B9FC4;
    }
}
