// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x34669456, "STUAnimBlendTreeSet_HardcodedAnimCategoryRefs")]
    public class STUAnimBlendTreeSet_HardcodedAnimCategoryRefs : STUInstance {
        [STUFieldAttribute(0xE569F683)]
        public teStructuredDataAssetRef<STUAnimCategory> m_E569F683;

        [STUFieldAttribute(0xF4DFBA8F)]
        public teStructuredDataAssetRef<STUAnimCategory> m_F4DFBA8F;

        [STUFieldAttribute(0x3D2BB79F)]
        public teStructuredDataAssetRef<STUAnimCategory> m_3D2BB79F;

        [STUFieldAttribute(0x8621386A)]
        public teStructuredDataAssetRef<STUAnimCategory> m_8621386A;

        [STUFieldAttribute(0xDC2C5110)]
        public teStructuredDataAssetRef<STUAnimCategory> m_DC2C5110;

        [STUFieldAttribute(0xC29DF9DB)]
        public teStructuredDataAssetRef<STUAnimCategory> m_C29DF9DB;

        [STUFieldAttribute(0x6C613E91)]
        public teStructuredDataAssetRef<STUAnimCategory> m_6C613E91;

        [STUFieldAttribute(0x88051108)]
        public teStructuredDataAssetRef<STUAnimCategory> m_88051108;

        [STUFieldAttribute(0x0D2CB484)]
        public teStructuredDataAssetRef<STUAnimCategory> m_0D2CB484;

        [STUFieldAttribute(0xC7ED6C93)]
        public teStructuredDataAssetRef<STUAnimCategory> m_C7ED6C93;

        [STUFieldAttribute(0x9E18D40B)]
        public teStructuredDataAssetRef<STUAnimCategory> m_9E18D40B;
    }
}
