// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA7ED92FB, "STUAnimNode_ToTargetDirectionIKItem")]
    public class STUAnimNode_ToTargetDirectionIKItem : STUInstance {
        [STUFieldAttribute(0xD058C690, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_25992DF8 m_D058C690;

        [STUFieldAttribute(0xCB53B1B6, "m_end", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_25992DF8 m_end;

        [STUFieldAttribute(0x2CBF1AFF, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_4A3CC593 m_2CBF1AFF;

        [STUFieldAttribute(0xC0F3B00A, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_7059BA29 m_C0F3B00A;

        [STUFieldAttribute(0xE995B1A9)]
        public teStructuredDataAssetRef<STU_46F1EF57> m_E995B1A9;

        [STUFieldAttribute(0x54E32FB9)]
        public teStructuredDataAssetRef<STU_46F1EF57> m_54E32FB9;
    }
}
