// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x1DBCE829, "STUAnimNode_AdjustBoneTransformParams_ScalePositionPSItem")]
    public class STUAnimNode_AdjustBoneTransformParams_ScalePositionPSItem : STUInstance {
        [STUFieldAttribute(0x0CC20819, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_25992DF8 m_0CC20819;

        [STUFieldAttribute(0xE94E6288, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_4A3CC593 m_E94E6288;

        [STUFieldAttribute(0xABE98556, "m_bone")]
        public teStructuredDataAssetRef<STU_46F1EF57> m_bone;
    }
}
