// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3555B365, "STUAnimConfigWeightSet")]
    public class STUAnimConfigWeightSet : STUInstance {
        [STUFieldAttribute(0xFF53F1FC)]
        public float m_FF53F1FC;

        [STUFieldAttribute(0x055CCC9F)]
        public float m_055CCC9F;

        [STUFieldAttribute(0xBDCBF43F)]
        public float m_BDCBF43F;

        [STUFieldAttribute(0x47C4C95C)]
        public float m_47C4C95C;

        [STUFieldAttribute(0xDE3851AB)]
        public float m_DE3851AB;

        [STUFieldAttribute(0x395CCCBD)]
        public float m_395CCCBD;

        [STUFieldAttribute(0x885BC37A, "m_root")]
        public float m_root;
    }
}
