// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x679C8174, "STUAITacticalMetaData")]
    public class STUAITacticalMetaData : STUInstance {
        [STUFieldAttribute(0x1E31577B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_2DDCA413[] m_1E31577B;
    }
}
