// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4EC8D398, "STUAnimCurveCompiled")]
    public class STUAnimCurveCompiled : STUInstance {
        [STUFieldAttribute(0xF4C17442, "m_valueKeys")]
        public float[] m_valueKeys;

        [STUFieldAttribute(0x2C3E8004, "m_timeKeys")]
        public float[] m_timeKeys;
    }
}
