// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7DABA1B6, "STUAnimParamUpdater_SnapTurnScriptedAnimAlias")]
    public class STUAnimParamUpdater_SnapTurnScriptedAnimAlias : STUInstance {
        [STUFieldAttribute(0xBBAB1943, "m_animAlias")]
        public teStructuredDataAssetRef<STUAnimAlias> m_animAlias;

        [STUFieldAttribute(0x7D46B46B)]
        public teVec2 m_7D46B46B;

        [STUFieldAttribute(0xEC35A969)]
        public float m_EC35A969;
    }
}
