// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x6C0BBD69, "STUAnimNode_LayerChild")]
    public class STUAnimNode_LayerChild : STU_1359915D {
        [STUFieldAttribute(0xD1DC98E2, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_C05D84A5 m_D1DC98E2;

        [STUFieldAttribute(0x118F5508, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUAnimNode_LayerBase m_118F5508;

        [STUFieldAttribute(0xE6CAEA04, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_FF128724 m_E6CAEA04;

        [STUFieldAttribute(0x1B4A676B, "m_weightDriver", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_27C3556F m_weightDriver;

        [STUFieldAttribute(0xB686846F)]
        public Enum_B5CBD1F4 m_B686846F;

        [STUFieldAttribute(0x298B40D3)]
        public Enum_F563AADF m_298B40D3;

        [STUFieldAttribute(0x4CA5E9BB)]
        public ushort m_4CA5E9BB;
    }
}
