// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFEC0F75B, "STUAIWeaponFireControlInfo")]
    public class STUAIWeaponFireControlInfo : STUInstance {
        [STUFieldAttribute(0xF0F5DA3A, "m_weaponID")]
        public teStructuredDataAssetRef<STUIdentifier> m_weaponID;

        [STUFieldAttribute(0x1AFE6805, "m_aimHardpoint")]
        public teStructuredDataAssetRef<STUHardPoint> m_aimHardpoint;

        [STUFieldAttribute(0x841A8DFF)]
        public STULogicalButton m_841A8DFF;

        [STUFieldAttribute(0x2181CFFA)]
        public uint m_2181CFFA;

        [STUFieldAttribute(0xC97F2482)]
        public uint m_C97F2482;
    }
}
