// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9BF7B74F, "STUAIBodyPartDamageGroupDamageTagScalar")]
    public class STUAIBodyPartDamageGroupDamageTagScalar : STUInstance {
        [STUFieldAttribute(0xD98ECD58, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D98ECD58;

        [STUFieldAttribute(0x4157309F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4157309F;
    }
}
