// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB89FF870, "STUAnimNode_LayerOverride")]
    public class STUAnimNode_LayerOverride : STUAnimNode_LayerBase {
        [STUFieldAttribute(0x8CB63231, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_A074A01F m_8CB63231;

        [STUFieldAttribute(0x26FDE02D, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_CFB183E4 m_26FDE02D;

        [STUFieldAttribute(0xDAAA01F7, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_CFB183E4 m_DAAA01F7;

        [STUFieldAttribute(0xDDDAADA5, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigBoneWeight_Item[] m_DDDAADA5;

        [STUFieldAttribute(0x196AD293, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_27C3556F m_196AD293;
    }
}
