// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x572A12DE, "STUAnimGameData_LayerInfo")]
    public class STUAnimGameData_LayerInfo : STUInstance {
        [STUFieldAttribute(0x1B4A676B, "m_weightDriver", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimGameData_WeightDriver m_weightDriver;

        [STUFieldAttribute(0x9AE76570)]
        public float m_9AE76570;

        [STUFieldAttribute(0x44233934)]
        public ushort m_44233934;

        [STUFieldAttribute(0x0FA29E55)]
        public byte m_0FA29E55;

        [STUFieldAttribute(0x69465A96)]
        public byte m_69465A96;
    }
}
