// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x37C0CAAE, "STUAnimationPermutation")]
    public class STUAnimationPermutation : STUInstance {
        [STUFieldAttribute(0xD3832764, "m_animation")]
        public teStructuredDataAssetRef<STUAnimation> m_animation;

        [STUFieldAttribute(0xBD6DE678)]
        public float m_BD6DE678;
    }
}
