// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE5C2396A, "STUAIBodyPartDamageGroup")]
    public class STUAIBodyPartDamageGroup : STUInstance {
        [STUFieldAttribute(0x099639B3, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAIBodyPartDamageGroupDamageTagScalar[] m_099639B3;

        [STUFieldAttribute(0x2B2DCACF)]
        public teStructuredDataAssetRef<STUIdentifier> m_2B2DCACF;

        [STUFieldAttribute(0x697E5373, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_697E5373;

        [STUFieldAttribute(0x770D6CDB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_770D6CDB;

        [STUFieldAttribute(0xABC9E4C6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_ABC9E4C6;
    }
}
