// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x67CE6761, "STUAIDifficultyProfile")]
    public class STUAIDifficultyProfile : STUInstance {
        [STUFieldAttribute(0x0461ED4F)]
        public teStructuredDataAssetRef<STUIdentifier> m_0461ED4F;

        [STUFieldAttribute(0xEE871178)]
        public teStructuredDataAssetRef<ulong> m_EE871178;
    }
}
