// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xCE80D4BE, "STUAnimLayerMask_Blend2d_Item")]
    public class STUAnimLayerMask_Blend2d_Item : STUInstance {
        [STUFieldAttribute(0xE1C0F911, "m_mask", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAnimConfigBoneWeightMask m_mask;

        [STUFieldAttribute(0x0147E069)]
        public teVec2 m_0147E069;
    }
}
