// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC09707BD, "STUAnimBlendDriverParam")]
    public class STUAnimBlendDriverParam : STUInstance {
        [STUFieldAttribute(0xA4E56F85, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_C05D84A5 m_A4E56F85;

        [STUFieldAttribute(0x625946AA, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_CFB183E4 m_625946AA;

        [STUFieldAttribute(0x15192D8D, "m_source", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_27C3556F m_source;

        [STUFieldAttribute(0x09657D8A, "m_mode")]
        public Enum_D8F91904 m_mode;
    }
}
