// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x19F77CFE, "STUAnimBlendTimeParams")]
    public class STUAnimBlendTimeParams : STUInstance {
        [STUFieldAttribute(0x428B9FC4, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_7059BA29 m_428B9FC4;

        [STUFieldAttribute(0x0829A9A6, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_7059BA29 m_0829A9A6;

        [STUFieldAttribute(0x0BF0BF60, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_CFB183E4 m_0BF0BF60;

        [STUFieldAttribute(0x6B75C3C1, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_CFB183E4 m_6B75C3C1;
    }
}
