// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4E84DF64, "STUAIBehaviorComponent")]
    public class STUAIBehaviorComponent : STUMirroredEntityComponent {
        [STUFieldAttribute(0x7F2FE530, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUGameModeSpecificBehaviorScripts m_7F2FE530;

        [STUFieldAttribute(0x3D9201B4, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUGameModeSpecificBehaviorScripts m_3D9201B4;

        [STUFieldAttribute(0x05A1F8A9, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUGameModeSpecificBehaviorScripts m_05A1F8A9;

        [STUFieldAttribute(0xBEF1C6CA, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUGameModeSpecificBehaviorScripts m_BEF1C6CA;

        [STUFieldAttribute(0xE08E0293, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUGameModeSpecificBehaviorScripts m_E08E0293;

        [STUFieldAttribute(0x671C3316, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUGameModeSpecificBehaviorScripts m_671C3316;

        [STUFieldAttribute(0x0EE279D1, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUGameModeSpecificBehaviorScripts m_0EE279D1;

        [STUFieldAttribute(0x4554ABF1, "m_difficultyProfiles", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAIDifficultyProfile[] m_difficultyProfiles;

        [STUFieldAttribute(0x8BAC4D5F)]
        public float m_8BAC4D5F;
    }
}
