// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x102951B4, "STUAnimBlendTreeSet_Graph")]
    public class STUAnimBlendTreeSet_Graph : STUGraph {
    }
}
