// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x37AE888C, "STUAITacticalVolumeMap")]
    public class STUAITacticalVolumeMap : STUInstance {
        [STUFieldAttribute(0x8457A37E, "m_dynamicTreeDef", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUDynamicTreeDef m_dynamicTreeDef;

        [STUFieldAttribute(0x2093E65C, "m_volumes", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAITacticalVolume[] m_volumes;

        [STUFieldAttribute(0x2A32CED5, "m_chokes", ReaderType = typeof(InlineInstanceFieldReader))]
        public AITacticalChoke[] m_chokes;

        [STUFieldAttribute(0x469FC14A)]
        public int[] m_469FC14A;

        [STUFieldAttribute(0x404E826C, "m_metaData", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUAITacticalMetaData m_metaData;

        [STUFieldAttribute(0xDE8E9124)]
        public int m_DE8E9124;
    }
}
