// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9F9521F8, "STUAnimIdentifier")]
    public class STUAnimIdentifier : STUInstance {
    }
}
