// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x862AB849, "STUAnimNode_StrafeProfileOverride")]
    public class STUAnimNode_StrafeProfileOverride : STUInstance {
        [STUFieldAttribute(0xDB18E646, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_2B64BE64 m_DB18E646;

        [STUFieldAttribute(0xE3072BFB, "m_condition", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_16151658 m_condition;
    }
}
