// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x60F9ACB1, "STUAnimGameData_BoneWeightMask")]
    public class STUAnimGameData_BoneWeightMask : STUInstance {
        [STUFieldAttribute(0xAB041114, "m_boneWeights")]
        public float[] m_boneWeights;

        [STUFieldAttribute(0xB7CD05FA, "m_crc")]
        public uint m_crc;
    }
}
