// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD226D58A, "STUAnimNode_Root")]
    public class STUAnimNode_Root : STU_62116F39 {
        [STUFieldAttribute(0x6E44EB4D, "m_child", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_1359915D m_child;
    }
}
