// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB323441D, "STUBreakableConfig")]
    public class STUBreakableConfig : STUInstance {
        [STUFieldAttribute(0x4FF25313, "m_clientOnly")]
        public byte m_clientOnly;

        [STUFieldAttribute(0x49D56325, "m_spawnSleeping")]
        public byte m_spawnSleeping;

        [STUFieldAttribute(0xFF198FD2)]
        public byte m_FF198FD2;
    }
}
