// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4DB01428, "STUBlendMaterial")]
    public class STUBlendMaterial : STUMaterialType {
        [STUFieldAttribute(0x034C1CDB, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_1317D85E m_034C1CDB;

        [STUFieldAttribute(0x24BF30B9, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_F189210D m_24BF30B9;

        [STUFieldAttribute(0x581598A7, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_520110FD m_581598A7;
    }
}
