// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD4E0B6A8, "STUConfigVarColor")]
    public class STUConfigVarColor : STUConfigVarColorBase {
        [STUFieldAttribute(0x5180E750, "m_value")]
        public teColorRGBA m_value;
    }
}
