// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFAB38435, "STUChatCommand")]
    public class STUChatCommand : STUInstance {
        [STUFieldAttribute(0x73E6B245, "m_chatCommand")]
        public teStructuredDataAssetRef<ulong> m_chatCommand;

        [STUFieldAttribute(0x75B4BB05, "m_commandDescription")]
        public teStructuredDataAssetRef<ulong> m_commandDescription;

        [STUFieldAttribute(0xC03D6E94, "m_chatCommandAliases")]
        public teStructuredDataAssetRef<ulong>[] m_chatCommandAliases;

        [STUFieldAttribute(0x27E6A1B4, "m_chatCommandType")]
        public STUChatCommandType m_chatCommandType;

        [STUFieldAttribute(0xA01D085D)]
        public byte m_A01D085D;
    }
}
