// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB709560A, "STUConfigVarEffect")]
    public class STUConfigVarEffect : STU_82972D9D {
        [STUFieldAttribute(0xFCF3C30C, "m_effect")]
        public teStructuredDataAssetRef<ulong> m_effect;
    }
}
