// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA08D3C3B, "STUConfigVarGetEntityVelocityVector")]
    public class STUConfigVarGetEntityVelocityVector : STUConfigVarVecBase {
        [STUFieldAttribute(0x44BB1696, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;

        [STUFieldAttribute(0x2CBC19E1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2CBC19E1;
    }
}
