// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE5E40E59, "STUConfigVarGetAIFacingVector")]
    public class STUConfigVarGetAIFacingVector : STUConfigVarVecBase {
        [STUFieldAttribute(0xFBDAFEF2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FBDAFEF2;
    }
}
