// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9D40E5A8, "STUConfigVarUInt")]
    public class STUConfigVarUInt : STUConfigVarUIntBase {
        [STUFieldAttribute(0x5180E750, "m_value")]
        public uint m_value;
    }
}
