// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x13BA10F6, "STUConfigVarArray")]
    public class STUConfigVarArray : STUConfigVar {
        [STUFieldAttribute(0x65CE2851, "m_configVars", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar[] m_configVars;
    }
}
