// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE6FF05BA, "STUContactEffect")]
    public class STUContactEffect : STUInstance {
    }
}
