// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x189E705B, "STUConfigVarGameMode")]
    public class STUConfigVarGameMode : STU_82972D9D {
        [STUFieldAttribute(0xCEA1FBEC, "m_gamemode")]
        public teStructuredDataAssetRef<STUGameMode> m_gamemode;
    }
}
