// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4FF6E110, "STUConfigVarStringBase")]
    public class STUConfigVarStringBase : STUConfigVar {
    }
}
