// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x266CA3BC, "STUConfigVarAnimationBase")]
    public class STUConfigVarAnimationBase : STU_82972D9D {
    }
}
