// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBABC78AD, "STUConfigVarGetFPS")]
    public class STUConfigVarGetFPS : STUConfigVarString {
    }
}
