// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE4BE1517, "STUConfigVarGetHeroResponsible")]
    public class STUConfigVarGetHeroResponsible : STUConfigVarEntityID {
        [STUFieldAttribute(0x44BB1696, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;
    }
}
