// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0BADB906, "STUConfigVarGetEntityYaw")]
    public class STUConfigVarGetEntityYaw : STUConfigVarNumeric {
        [STUFieldAttribute(0x44BB1696, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;
    }
}
