// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x04E83493, "STUConfigVarStatescriptGraph")]
    public class STUConfigVarStatescriptGraph : STU_82972D9D {
        [STUFieldAttribute(0x45B2BAB8, "m_graph")]
        public teStructuredDataAssetRef<STU_D83702BD> m_graph;
    }
}
