// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x65F4C9D9, "STUConfigVarResource")]
    public class STUConfigVarResource : STUConfigVar {
        [STUFieldAttribute(0x06207B8F, "m_resourceKey")]
        public teStructuredDataAssetRef<STUResourceKey> m_resourceKey;
    }
}
