// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x098C01A7, "STUConfigVarSkin")]
    public class STUConfigVarSkin : STUConfigVarSkinBase {
        [STUFieldAttribute(0x9CD6523F, "m_skin")]
        public teStructuredDataAssetRef<STUSkin> m_skin;
    }
}
