// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB40FA21B, "STUConfigVarGetHeroRole")]
    public class STUConfigVarGetHeroRole : STU_054BC7E8 {
        [STUFieldAttribute(0xCF6154A7, "m_hero", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_hero;
    }
}
