// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xEB8548ED, "STUConfigVarGetRegion")]
    public class STUConfigVarGetRegion : STUConfigVarIntBase {
    }
}
