// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3AE7427E, "STUConfigVarInt")]
    public class STUConfigVarInt : STUConfigVarIntBase {
        [STUFieldAttribute(0x5180E750, "m_value")]
        public int m_value;
    }
}
