// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF52D462A, "STUClothConfig")]
    public class STUClothConfig : STUInstance {
        [STUFieldAttribute(0x7DD29343)]
        public int m_7DD29343;

        [STUFieldAttribute(0x4B159291)]
        public byte m_4B159291;

        [STUFieldAttribute(0x8B40320A)]
        public byte m_8B40320A;
    }
}
