// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5BFB7C03, "STUConfigVarGetLootBoxAsset")]
    public class STUConfigVarGetLootBoxAsset : STUConfigVar {
        [STUFieldAttribute(0xFFA4E821, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FFA4E821;

        [STUFieldAttribute(0x581570BA, "m_lootboxType", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_lootboxType;

        [STUFieldAttribute(0x12716D08, "m_type")]
        public Enum_6B07725D m_type;
    }
}
