// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x16C264E9, "STUConfigVarFloatBase")]
    public class STUConfigVarFloatBase : STUConfigVarNumeric {
    }
}
