// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5E745F2B, "STUConfigVarBool")]
    public class STUConfigVarBool : STUConfigVarBoolBase {
        [STUFieldAttribute(0x5180E750, "m_value")]
        public byte m_value;
    }
}
