// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC01F391C, "STUConfigVarInt64")]
    public class STUConfigVarInt64 : STUConfigVarInt64Base {
        [STUFieldAttribute(0x5180E750, "m_value")]
        public long m_value;
    }
}
