// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xAD14D29A, "STUConfigVarUInt64Base")]
    public class STUConfigVarUInt64Base : STUConfigVarNumeric {
    }
}
