// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9FD77551, "STUConfigVarString")]
    public class STUConfigVarString : STUConfigVarStringBase {
        [STUFieldAttribute(0x5180E750, "m_value")]
        public teString m_value;
    }
}
