// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA928FEF4, "STUChatReplacementInfo")]
    public class STUChatReplacementInfo : STUInstance {
        [STUFieldAttribute(0x4863E63C)]
        public teStructuredDataAssetRef<ulong> m_4863E63C;

        [STUFieldAttribute(0x3262FBF0, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUChatCapturedReplacementInfo[] m_3262FBF0;

        [STUFieldAttribute(0xADDB76A9)]
        public teStructuredDataAssetRef<ulong>[] m_ADDB76A9;

        [STUFieldAttribute(0xACA3AD45, "m_duringCelebration")]
        public teStructuredDataAssetRef<STUCelebration> m_duringCelebration;

        [STUFieldAttribute(0xFD0FFD4A)]
        public teStructuredDataAssetRef<STUHero>[] m_FD0FFD4A;

        [STUFieldAttribute(0xCF491577)]
        public teStructuredDataAssetRef<ulong>[] m_CF491577;

        [STUFieldAttribute(0xC4F54D40, "m_resourceKeyId")]
        public ulong m_resourceKeyId;
    }
}
