// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8F28BD45, "STUChatCapturedReplacementInfo")]
    public class STUChatCapturedReplacementInfo : STUInstance {
        [STUFieldAttribute(0xFD544E62)]
        public teString m_FD544E62;

        [STUFieldAttribute(0x69D55ACC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_D4FD7005[] m_69D55ACC;
    }
}
