// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x26C11174, "STUCameraInstanceData")]
    public class STUCameraInstanceData : STUComponentInstanceData {
        [STUFieldAttribute(0xC08C4427, "m_name")]
        public teString m_name;

        [STUFieldAttribute(0x23B74FE6)]
        public float m_23B74FE6;

        [STUFieldAttribute(0x6BEE9D55)]
        public int m_6BEE9D55;
    }
}
