// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBD455677, "STUConfigVarGetHeroName")]
    public class STUConfigVarGetHeroName : STUConfigVarStringBase {
        [STUFieldAttribute(0xCF6154A7, "m_hero", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_hero;
    }
}
