// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF062BA36, "STUConfigVarGetPetMaster")]
    public class STUConfigVarGetPetMaster : STUConfigVarEntityID {
        [STUFieldAttribute(0x77BDCBEF, "m_petEntity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_petEntity;
    }
}
