// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB37CB75A, "STUContactMaterial")]
    public class STUContactMaterial : STUInstance {
        [STUFieldAttribute(0x771D32B1, "m_parent")]
        public teStructuredDataAssetRef<STUContactMaterial> m_parent;

        [STUFieldAttribute(0x718D3AD6)]
        public teColorRGBA m_718D3AD6;
    }
}
