// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x805D512E, "STUConfigVarGetGameModeName")]
    public class STUConfigVarGetGameModeName : STUConfigVarStringBase {
        [STUFieldAttribute(0xCEA1FBEC, "m_gamemode", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_gamemode;
    }
}
