// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD7AA244A, "STUConfigVarGetEntityBoundsCenter")]
    public class STUConfigVarGetEntityBoundsCenter : STUConfigVarVecBase {
        [STUFieldAttribute(0x44BB1696, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;
    }
}
