// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7C39E5E6, "STUConfigVarGetMap")]
    public class STUConfigVarGetMap : STUConfigVarResource {
    }
}
