// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5A8B9055, "STUConfigVarGetEntityAtSlot")]
    public class STUConfigVarGetEntityAtSlot : STUConfigVarEntityID {
        [STUFieldAttribute(0x32A11A46, "m_slot", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_slot;

        [STUFieldAttribute(0x5A4F9C3E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5A4F9C3E;
    }
}
