// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x66665893, "STUConfigVarGetEntityCollisionRadius")]
    public class STUConfigVarGetEntityCollisionRadius : STUConfigVarEntityID {
        [STUFieldAttribute(0x44BB1696, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;
    }
}
