// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x6F450DEB, "STUConfigVarCelebration")]
    public class STUConfigVarCelebration : STU_82972D9D {
        [STUFieldAttribute(0xC1458915, "m_celebration")]
        public teStructuredDataAssetRef<STUCelebration> m_celebration;
    }
}
