// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xDBF9195C, "STUConfigVarVec3")]
    public class STUConfigVarVec3 : STUConfigVarVecBase {
        [STUFieldAttribute(0x5180E750, "m_value")]
        public teVec3 m_value;
    }
}
