// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x57C0835F, "STUComponentInstanceData")]
    public class STUComponentInstanceData : STUInstance {
    }
}
