// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFF20DA09, "STUConfigVarSkinBase")]
    public class STUConfigVarSkinBase : STU_82972D9D {
    }
}
