// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5AB8D974, "STUCaptureAreaComponent")]
    public class STUCaptureAreaComponent : STUMirroredEntityComponent {
        [STUFieldAttribute(0xD75420DA, "m_residencyMultipliers", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUCaptureAreaResidencyMultiplier[] m_residencyMultipliers;

        [STUFieldAttribute(0x29946D51, "m_segments", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUCaptureAreaSegment[] m_segments;

        [STUFieldAttribute(0xB5A9FFFF)]
        public float m_B5A9FFFF;
    }
}
