// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0E2552E2, "STUEscortComponent")]
    public class STUEscortComponent : STUEntityComponent {
        [STUFieldAttribute(0x0E5D6C4F, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUEscortRadius m_0E5D6C4F;

        [STUFieldAttribute(0x424B44FA, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUEscortRadius m_424B44FA;

        [STUFieldAttribute(0xAB75FA5D)]
        public uint m_AB75FA5D;

        [STUFieldAttribute(0xF5A65FED)]
        public float m_F5A65FED;
    }
}
