// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFF82DF73, "STUEffectLook")]
    public class STUEffectLook : STUInstance {
        [STUFieldAttribute(0x3738F718)]
        public ulong[] m_3738F718;

        [STUFieldAttribute(0xE91154F1, "m_materialData")]
        public teStructuredDataAssetRef<ulong>[] m_materialData;
    }
}
