// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x590BD5D4, "STUECHintPointInstanceData")]
    public class STUECHintPointInstanceData : STUComponentInstanceData {
        [STUFieldAttribute(0xB2CA6977, "m_identifier")]
        public teStructuredDataAssetRef<STUIdentifier> m_identifier;
    }
}
