// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0BFF1CB3, "STUEffectTemplateState")]
    public class STUEffectTemplateState : STU_35FD4032 {
        [STUFieldAttribute(0x20623CAB)]
        public float m_20623CAB;

        [STUFieldAttribute(0xC99C08F2)]
        public float m_C99C08F2;
    }
}
