// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF1350107, "STUEffectTrack")]
    public class STUEffectTrack : STUInstance {
        [STUFieldAttribute(0x983AA9FB, "m_template")]
        public teStructuredDataAssetRef<STUEffectTemplate> m_template;

        [STUFieldAttribute(0x5D96917B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A1DF5CE6[] m_5D96917B;

        [STUFieldAttribute(0x7B5125B3, "m_states")]
        public teStructuredDataAssetRef<STUEffectTemplateState>[] m_states;
    }
}
