// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x66462FD5, "STUEmptyAsset")]
    public class STUEmptyAsset : STUInstance {
    }
}
