// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA1B2CA3B, "STUEntitlementUnlock")]
    public class STUEntitlementUnlock : STUInstance {
        [STUFieldAttribute(0xA48A7CE0)]
        public teString[] m_A48A7CE0;

        [STUFieldAttribute(0x719E981B, "m_unlocks")]
        public teStructuredDataAssetRef<STUUnlock>[] m_unlocks;
    }
}
