// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x277A8C89, "STUGenericSettings_SprayReplacement")]
    public class STUGenericSettings_SprayReplacement : STUGenericSettings_Base {
        [STUFieldAttribute(0x78596A82, ReaderType = typeof(InlineInstanceFieldReader))]
        public SprayReplacement[] m_78596A82;
    }
}
