// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD9D4847A, "STUGenericSettings_LootBoxes")]
    public class STUGenericSettings_LootBoxes : STUGenericSettings_Base {
        [STUFieldAttribute(0xEDDA419E, "m_lootboxes", ReaderType = typeof(InlineInstanceFieldReader))]
        public STULootBoxRules[] m_lootboxes;
    }
}
