// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC16FA5C0, "STUGenericSettings_Nameplates")]
    public class STUGenericSettings_Nameplates : STUGenericSettings_Base {
        [STUFieldAttribute(0xB6BBCACB)]
        public teStructuredDataAssetRef<ulong> m_B6BBCACB;

        [STUFieldAttribute(0xEBFDCC5D)]
        public teStructuredDataAssetRef<ulong> m_EBFDCC5D;

        [STUFieldAttribute(0xB02F7E60, "m_fontFamily", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_FAA3F9A2 m_fontFamily;

        [STUFieldAttribute(0xFB358CDB, "m_backgroundColor")]
        public teColorRGBA m_backgroundColor;

        [STUFieldAttribute(0x7B32776E)]
        public teColorRGB m_7B32776E;

        [STUFieldAttribute(0x62030719)]
        public teColorRGB m_62030719;

        [STUFieldAttribute(0x3F9BD46D)]
        public float m_3F9BD46D;

        [STUFieldAttribute(0x3C683422)]
        public float m_3C683422;

        [STUFieldAttribute(0xA4B72D47)]
        public float m_A4B72D47;

        [STUFieldAttribute(0x42D782A6)]
        public float m_42D782A6;

        [STUFieldAttribute(0x49192F73)]
        public float m_49192F73;

        [STUFieldAttribute(0x7514102A)]
        public float m_7514102A;

        [STUFieldAttribute(0x904D692B)]
        public float m_904D692B;

        [STUFieldAttribute(0xAC405672)]
        public float m_AC405672;

        [STUFieldAttribute(0x20CFCA37, "m_fontStyle")]
        public Enum_EE8D87E7 m_fontStyle;

        [STUFieldAttribute(0x12040A7A, "m_fontWeight")]
        public int m_fontWeight;

        [STUFieldAttribute(0xB0EADF78, "m_fontStretch")]
        public int m_fontStretch;

        [STUFieldAttribute(0x4018BD42)]
        public float m_4018BD42;

        [STUFieldAttribute(0x666BD325)]
        public float m_666BD325;

        [STUFieldAttribute(0xC15F535C)]
        public float m_C15F535C;

        [STUFieldAttribute(0xE4D3260E)]
        public float m_E4D3260E;

        [STUFieldAttribute(0x489409D1)]
        public float m_489409D1;

        [STUFieldAttribute(0x35FC91A6)]
        public float m_35FC91A6;

        [STUFieldAttribute(0x20774554)]
        public float m_20774554;

        [STUFieldAttribute(0xCB10AF9B)]
        public uint m_CB10AF9B;

        [STUFieldAttribute(0x14907775)]
        public uint m_14907775;

        [STUFieldAttribute(0x3ABC3437)]
        public uint m_3ABC3437;

        [STUFieldAttribute(0x78E06512)]
        public byte m_78E06512;

        [STUFieldAttribute(0x16D50755)]
        public byte m_16D50755;
    }
}
