// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE99EA206, "STUGenericSettings_GamePad")]
    public class STUGenericSettings_GamePad : STUGenericSettings_Base {
        [STUFieldAttribute(0xF82835BA, "m_regions", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUGamePadMoveRegion[] m_regions;

        [STUFieldAttribute(0x639A4997, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUAnimCurve m_639A4997;

        [STUFieldAttribute(0x0957AE74, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUAnimCurve m_0957AE74;

        [STUFieldAttribute(0x030578C1)]
        public float m_030578C1;

        [STUFieldAttribute(0x3DB0B049)]
        public float m_3DB0B049;

        [STUFieldAttribute(0x4099EC8D)]
        public float m_4099EC8D;

        [STUFieldAttribute(0xA3C45257)]
        public float m_A3C45257;

        [STUFieldAttribute(0xAE738DFB)]
        public float m_AE738DFB;

        [STUFieldAttribute(0xFDD5951F)]
        public float m_FDD5951F;

        [STUFieldAttribute(0xED970F81)]
        public float m_ED970F81;
    }
}
