// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4728057A, "STUGenericSettings_TeamColoring")]
    public class STUGenericSettings_TeamColoring : STUGenericSettings_Base {
        [STUFieldAttribute(0x46A984E4, "m_UISettings", ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_F3560D1C m_UISettings;
    }
}
