// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x84201DCA, "STUGraphPlug")]
    public class STUGraphPlug : STUInstance {
        [STUFieldAttribute(0x9D751E7C, "m_links", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUGraphLink[] m_links;

        [STUFieldAttribute(0x365378C7, "m_parentNode", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUGraphNode m_parentNode;
    }
}
