// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8091AD10, "STUGenericSettings_DefaultInput")]
    public class STUGenericSettings_DefaultInput : STUGenericSettings_Base {
        [STUFieldAttribute(0x5F03FB03, "m_bindings", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUInputButtonBinding[] m_bindings;
    }
}
