// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x240149C8, "STUGameRulesetSchemaValueEnumChoice")]
    public class STUGameRulesetSchemaValueEnumChoice : STUInstance {
        [STUFieldAttribute(0xC1769D54, "m_displayText")]
        public teStructuredDataAssetRef<ulong> m_displayText;

        [STUFieldAttribute(0xB2CA6977, "m_identifier")]
        public teStructuredDataAssetRef<STUIdentifier> m_identifier;
    }
}
