// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD82DC477, "STUGameMessage")]
    public class STUGameMessage : STUInstance {
        [STUFieldAttribute(0x8D34FFDF)]
        public teStructuredDataAssetRef<STU_1031153D>[] m_8D34FFDF;
    }
}
