// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x778E5AD9, "STUGenericSettings_Profile")]
    public class STUGenericSettings_Profile : STUGenericSettings_Base {
        [STUFieldAttribute(0x1CE69F8F, "m_statWins")]
        public teStructuredDataAssetRef<STUStat> m_statWins;

        [STUFieldAttribute(0x08D63396, "m_statLosses")]
        public teStructuredDataAssetRef<STUStat> m_statLosses;

        [STUFieldAttribute(0x8CAE1FDC)]
        public teStructuredDataAssetRef<STUStat> m_8CAE1FDC;

        [STUFieldAttribute(0x57E3881C)]
        public teStructuredDataAssetRef<STUStat> m_57E3881C;

        [STUFieldAttribute(0x4D12A50E, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUProfileOverviewGeneralStat[] m_4D12A50E;

        [STUFieldAttribute(0x792778EE)]
        public teStructuredDataAssetRef<STUStat>[] m_792778EE;

        [STUFieldAttribute(0xCE970CA0, "m_statCategories", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUProfileStatCategory[] m_statCategories;
    }
}
