// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5DBBDD70, "STUGraphContainer")]
    public class STUGraphContainer : STUGraphItem {
        [STUFieldAttribute(0xCCEED0B9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUGraphItem[] m_CCEED0B9;

        [STUFieldAttribute(0xF82045F2)]
        public teString m_F82045F2;

        [STUFieldAttribute(0x1C40CE8E)]
        public teColorRGBA m_1C40CE8E;

        [STUFieldAttribute(0xFB358CDB, "m_backgroundColor")]
        public teColorRGBA m_backgroundColor;
    }
}
