// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x558D80F8, "STUHeroSettingBool")]
    public class STUHeroSettingBool : STUHeroSettingBase {
        [STUFieldAttribute(0xB9114C96, "m_default")]
        public byte m_default;
    }
}
