// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x1475F128, "STUHardPoint")]
    public class STUHardPoint : STUInstance {
    }
}
