// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xEA405E0D, "STUHighlightMaterial")]
    public class STUHighlightMaterial : STUMaterialType {
        [STUFieldAttribute(0x2CF5ED8B, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_A5F858B2 m_2CF5ED8B;
    }
}
