// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC0B8480B, "STUHeroSettingBase")]
    public class STUHeroSettingBase : STUInstance {
        [STUFieldAttribute(0xB2CA6977, "m_identifier")]
        public teStructuredDataAssetRef<STUIdentifier> m_identifier;

        [STUFieldAttribute(0xC08C4427, "m_name")]
        public teStructuredDataAssetRef<ulong> m_name;

        [STUFieldAttribute(0x0916AFB9, "m_category")]
        public teStructuredDataAssetRef<STUIdentifier> m_category;

        [STUFieldAttribute(0x946AA91D)]
        public Enum_2DB02D30 m_946AA91D;

        [STUFieldAttribute(0xC6DB3ED7)]
        public byte m_C6DB3ED7;

        [STUFieldAttribute(0xB3D4DE09)]
        public byte m_B3D4DE09;
    }
}
