// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3C74FB3A, "STUIdlePathdataInvalidateComponent")]
    public class STUIdlePathdataInvalidateComponent : STUMirroredEntityComponent {
    }
}
