// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD13AB3AA, "STULocalIdleAnimComponent")]
    public class STULocalIdleAnimComponent : STUEntityComponent {
        [STUFieldAttribute(0xBC15971B, "m_idleAnimation")]
        public teStructuredDataAssetRef<STUAnimation> m_idleAnimation;

        [STUFieldAttribute(0xD82EC091)]
        public float m_D82EC091;

        [STUFieldAttribute(0x5259B322)]
        public byte m_5259B322;
    }
}
