// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9A8AE734, "STULocalPersistedGameplaySettings")]
    public class STULocalPersistedGameplaySettings : STUInstance {
        [STUFieldAttribute(0xE938E6B8)]
        public byte m_E938E6B8;

        [STUFieldAttribute(0xC7DEC7AD)]
        public byte m_C7DEC7AD;

        [STUFieldAttribute(0x0A6C368B)]
        public byte m_0A6C368B;

        [STUFieldAttribute(0x03AF99B2)]
        public byte m_03AF99B2;

        [STUFieldAttribute(0xA72D1F19)]
        public byte m_A72D1F19;

        [STUFieldAttribute(0x4EC3BA42)]
        public byte m_4EC3BA42;

        [STUFieldAttribute(0xFEBB3B21)]
        public byte m_FEBB3B21;
    }
}
