// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xAECA23C1, "STULocalPersistedSettings")]
    public class STULocalPersistedSettings : STUInstance {
        [STUFieldAttribute(0x5F03FB03, "m_bindings", ReaderType = typeof(InlineInstanceFieldReader))]
        public STULocalPersistedBinding[] m_bindings;

        [STUFieldAttribute(0xEA1F16BD, "m_settings", ReaderType = typeof(InlineInstanceFieldReader))]
        public STULocalPersistedHeroSetting[] m_settings;

        [STUFieldAttribute(0x74AE9A0B, "m_gameplaySettings", ReaderType = typeof(InlineInstanceFieldReader))]
        public STULocalPersistedGameplaySettings m_gameplaySettings;

        [STUFieldAttribute(0xE12F0237, "m_voiceChatSettings", ReaderType = typeof(InlineInstanceFieldReader))]
        public STULocalPersistedVoiceChatSettings m_voiceChatSettings;
    }
}
