// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC075BCD1, "STULocalIdleAnimComponentInstanceData")]
    public class STULocalIdleAnimComponentInstanceData : STUComponentInstanceData {
        [STUFieldAttribute(0xF9E2C020)]
        public float m_F9E2C020;

        [STUFieldAttribute(0x1280CB09)]
        public int m_1280CB09;
    }
}
