// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x162BA6A1, "STULineupPoseVariant")]
    public class STULineupPoseVariant : STUInstance {
        [STUFieldAttribute(0xF9045E7A)]
        public teStructuredDataAssetRef<ulong> m_F9045E7A;

        [STUFieldAttribute(0x6B4D9ACA)]
        public teVec3 m_6B4D9ACA;

        [STUFieldAttribute(0x0594F3D8)]
        public teVec3 m_0594F3D8;

        [STUFieldAttribute(0xB4C4CB55)]
        public teVec3 m_B4C4CB55;

        [STUFieldAttribute(0xEC2AAF74)]
        public teVec3 m_EC2AAF74;

        [STUFieldAttribute(0xFD98E85A)]
        public teVec3 m_FD98E85A;

        [STUFieldAttribute(0xD94EED92)]
        public teVec3 m_D94EED92;
    }
}
