// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD8017400, "STULocalPersistedBinding")]
    public class STULocalPersistedBinding : STUInstance {
        [STUFieldAttribute(0xF5928F34)]
        public ulong m_F5928F34;

        [STUFieldAttribute(0x3C9341F5, "m_logicalButton")]
        public ulong m_logicalButton;

        [STUFieldAttribute(0xCF6154A7, "m_hero")]
        public ulong m_hero;

        [STUFieldAttribute(0x37898BCE, "m_modeCRC")]
        public uint m_modeCRC;

        [STUFieldAttribute(0xFD8F51DB)]
        public byte m_FD8F51DB;

        [STUFieldAttribute(0x699CDB36)]
        public byte m_699CDB36;

        [STUFieldAttribute(0xDA0A8854)]
        public byte m_DA0A8854;
    }
}
