// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xECFE2B4E, "STULightingLayer")]
    public class STULightingLayer : STUMapLayer {
    }
}
