// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB99D70FB, "STUMaterialData")]
    public class STUMaterialData : STUInstance {
        [STUFieldAttribute(0x9633F663, "m_sourceMaterial")]
        public teStructuredDataAssetRef<STU_504D8C9A> m_sourceMaterial;

        [STUFieldAttribute(0xC83CF0BB, "m_materialType", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUMaterialType m_materialType;
    }
}
