// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9C66F308, "STUModelComponentInstanceData")]
    public class STUModelComponentInstanceData : STUComponentInstanceData {
        [STUFieldAttribute(0xB595EE23, "m_look")]
        public teStructuredDataAssetRef<STUModelLook> m_look;
    }
}
