// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x2104D0F9, "STUMaterialDataFlow")]
    public class STUMaterialDataFlow : STUInstance {
    }
}
