// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x6DBF6015, "STUMirroredBreakableComponent")]
    public class STUMirroredBreakableComponent : STUMirroredEntityComponent {
    }
}
