// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xDF492422, "STUMovie")]
    public class STUMovie : STUInstance {
        [STUFieldAttribute(0x7B807670)]
        public teStructuredDataAssetRef<STU_CF2809A0> m_7B807670;

        [STUFieldAttribute(0x27BCDE52, "m_externalSound")]
        public teStructuredDataAssetRef<STUSound> m_externalSound;

        [STUFieldAttribute(0xC8253A18)]
        public float m_C8253A18;

        [STUFieldAttribute(0xC0EDFA4B, "m_width")]
        public uint m_width;

        [STUFieldAttribute(0xBFDEB7F1, "m_height")]
        public uint m_height;
    }
}
