// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF3FEC5A2, "STUMapFontKerningPair")]
    public class STUMapFontKerningPair : STUInstance {
        [STUFieldAttribute(0x91A94426)]
        public uint m_91A94426;

        [STUFieldAttribute(0xF86B5AE3)]
        public uint m_F86B5AE3;

        [STUFieldAttribute(0x6C04CC8B)]
        public short m_6C04CC8B;
    }
}
