// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x285EF524, "STUModelLighting")]
    public class STUModelLighting : STUInstance {
        [STUFieldAttribute(0x7058DF23)]
        public teStructuredDataAssetRef<STUEmptyAsset> m_7058DF23;

        [STUFieldAttribute(0x3814CCF0)]
        public Enum_CF6ADB35 m_3814CCF0;

        [STUFieldAttribute(0x26FD4759)]
        public Enum_42B0727B m_26FD4759;

        [STUFieldAttribute(0xDAB2780D)]
        public int m_DAB2780D;

        [STUFieldAttribute(0x3C49BD03)]
        public Enum_63AE4068 m_3C49BD03;

        [STUFieldAttribute(0x18E946F9)]
        public float m_18E946F9;

        [STUFieldAttribute(0x1556669B)]
        public float m_1556669B;

        [STUFieldAttribute(0x69527CF6)]
        public float m_69527CF6;

        [STUFieldAttribute(0x0A9CB954)]
        public float m_0A9CB954;

        [STUFieldAttribute(0x62E80014)]
        public float m_62E80014;

        [STUFieldAttribute(0x4CD7A44A)]
        public Enum_A3A99E0E m_4CD7A44A;

        [STUFieldAttribute(0x35C6F38A)]
        public byte m_35C6F38A;

        [STUFieldAttribute(0x5FE91223, "m_detailOnly")]
        public byte m_detailOnly;

        [STUFieldAttribute(0xA0553E74)]
        public byte m_A0553E74;

        [STUFieldAttribute(0x85966B46)]
        public byte m_85966B46;

        [STUFieldAttribute(0x2A3C767A)]
        public byte m_2A3C767A;

        [STUFieldAttribute(0x88F2DB75)]
        public byte m_88F2DB75;

        [STUFieldAttribute(0x0720B2D8)]
        public byte m_0720B2D8;

        [STUFieldAttribute(0x88F29D84)]
        public byte m_88F29D84;

        [STUFieldAttribute(0xCDE0DF1C)]
        public byte m_CDE0DF1C;

        [STUFieldAttribute(0x5256B9C6)]
        public byte m_5256B9C6;
    }
}
