// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD25DA2BC, "STUMovementStateComponent")]
    public class STUMovementStateComponent : STUMirroredEntityComponent {
    }
}
