// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF769F319, "STUNumberSettings")]
    public class STUNumberSettings : STUInstance {
        [STUFieldAttribute(0xD858FC19)]
        public teString m_D858FC19;

        [STUFieldAttribute(0x877A5E40)]
        public teString m_877A5E40;

        [STUFieldAttribute(0x9971B297)]
        public teString m_9971B297;

        [STUFieldAttribute(0xBF70B3C7)]
        public teString m_BF70B3C7;

        [STUFieldAttribute(0x185F6DBE)]
        public teString m_185F6DBE;

        [STUFieldAttribute(0x4358FD65)]
        public teString m_4358FD65;

        [STUFieldAttribute(0x5A7E1542)]
        public teString m_5A7E1542;

        [STUFieldAttribute(0xD199969F)]
        public teString m_D199969F;

        [STUFieldAttribute(0x4E775882)]
        public teString m_4E775882;

        [STUFieldAttribute(0x0FC7FA02)]
        public teString m_0FC7FA02;

        [STUFieldAttribute(0x010B12DA)]
        public teString m_010B12DA;

        [STUFieldAttribute(0x270A138A)]
        public teString m_270A138A;

        [STUFieldAttribute(0xF353261C)]
        public int m_F353261C;
    }
}
