// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x08B7BDBC, "STUOverlayMaterial")]
    public class STUOverlayMaterial : STUMaterialType {
        [STUFieldAttribute(0x9256B839, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_BE6BEB9A m_9256B839;

        [STUFieldAttribute(0x24BF30B9, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_F189210D m_24BF30B9;

        [STUFieldAttribute(0x581598A7, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_520110FD m_581598A7;
    }
}
