// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4B100F3F, "STUPublishEntry")]
    public class STUPublishEntry : STUInstance {
        [STUFieldAttribute(0x413F29AE, "m_key")]
        public teStructuredDataAssetRef<STUIdentifier> m_key;

        [STUFieldAttribute(0x5180E750, "m_value", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_value;
    }
}
