// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC7FB5A29, "STUPrefabLayer")]
    public class STUPrefabLayer : STULayer {
    }
}
