// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xEEE5D3CC, "STUPresenceIdentifier")]
    public class STUPresenceIdentifier : STUInstance {
        [STUFieldAttribute(0xB2CA6977, "m_identifier")]
        public uint m_identifier;
    }
}
