// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x188218B4, "STURayCastReceiverOverride")]
    public class STURayCastReceiverOverride : STUInstance {
        [STUFieldAttribute(0xD8FA2EC6)]
        public teStructuredDataAssetRef<STURaycastType>[] m_D8FA2EC6;

        [STUFieldAttribute(0xFE00DF29, ReaderType = typeof(InlineInstanceFieldReader))]
        public STURayCastReceiverResult m_FE00DF29;

        [STUFieldAttribute(0x60ABB3AF, ReaderType = typeof(InlineInstanceFieldReader))]
        public STURayCastReceiverResult m_60ABB3AF;
    }
}
