// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFD609E58, "STURankedTierDefinition")]
    public class STURankedTierDefinition : STUInstance {
        [STUFieldAttribute(0x518E8069)]
        public uint m_518E8069;

        [STUFieldAttribute(0xB7EE2F88)]
        public uint m_B7EE2F88;

        [STUFieldAttribute(0xBA31ADAB)]
        public Enum_64567FD4 m_BA31ADAB;
    }
}
