// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8F754DFF, "STUResourceKey")]
    public class STUResourceKey : STUInstance {
        [STUFieldAttribute(0xCA4483CD, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_957B577D m_CA4483CD;

        [STUFieldAttribute(0xCD0F2F64, "m_keyID")]
        public teString m_keyID;

        [STUFieldAttribute(0x413F29AE, "m_key")]
        public byte[] m_key;

        [STUFieldAttribute(0x5A48F10A)]
        public int m_5A48F10A;

        [STUFieldAttribute(0x47F2FEDE, "m_flags")]
        public uint m_flags;
    }
}
