// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7A0D01F1, "STURankedSeason")]
    public class STURankedSeason : STURankedData {
        [STUFieldAttribute(0x2A8125FB, "m_rankedSeason")]
        public int m_rankedSeason;
    }
}
