// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4EF1DD7E, "STUStatescriptWeaponProjectileImpact")]
    public class STUStatescriptWeaponProjectileImpact : STUInstance {
        [STUFieldAttribute(0xA69D9D21, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A69D9D21;

        [STUFieldAttribute(0xF2BDDBC9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F2BDDBC9;

        [STUFieldAttribute(0xE8196308, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E8196308;

        [STUFieldAttribute(0xD5AF23DE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D5AF23DE;

        [STUFieldAttribute(0x3AE00A37, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3AE00A37;

        [STUFieldAttribute(0x65164B3E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_65164B3E;

        [STUFieldAttribute(0x7BAEBA18, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7BAEBA18;

        [STUFieldAttribute(0x368CE398, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_368CE398;

        [STUFieldAttribute(0x05196183, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_05196183;

        [STUFieldAttribute(0x8D26F06A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8D26F06A;

        [STUFieldAttribute(0x8ED51025, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8ED51025;

        [STUFieldAttribute(0x354EE119, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_354EE119;

        [STUFieldAttribute(0x89174668, "m_modifyHealth", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptModifyHealth m_modifyHealth;

        [STUFieldAttribute(0x95D502C6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_95D502C6;

        [STUFieldAttribute(0xD016F302, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D016F302;

        [STUFieldAttribute(0xDBA78459, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_DBA78459;

        [STUFieldAttribute(0x245FDD8B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_245FDD8B;

        [STUFieldAttribute(0x4723E094)]
        public byte m_4723E094;

        [STUFieldAttribute(0x5BCB13EE)]
        public byte m_5BCB13EE;

        [STUFieldAttribute(0x5D7497C6)]
        public byte m_5D7497C6;

        [STUFieldAttribute(0xD9E68F97)]
        public byte m_D9E68F97;

        [STUFieldAttribute(0xE0383051)]
        public byte m_E0383051;

        [STUFieldAttribute(0x6029A8EF)]
        public byte m_6029A8EF;

        [STUFieldAttribute(0xCCD7C414)]
        public byte m_CCD7C414;
    }
}
