// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0459C53D, "STUStatescriptStateUIInWorld")]
    public class STUStatescriptStateUIInWorld : STUStatescriptStateUXBase {
        [STUFieldAttribute(0xF82835BA, "m_regions", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_34493776[] m_regions;

        [STUFieldAttribute(0x35570DE3, "m_filter", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarFilter m_filter;

        [STUFieldAttribute(0xD1D8C2E6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D1D8C2E6;

        [STUFieldAttribute(0x802179BB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_802179BB;

        [STUFieldAttribute(0x272269FE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_272269FE;

        [STUFieldAttribute(0xC142C61F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C142C61F;

        [STUFieldAttribute(0xEF1C0E48, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EF1C0E48;

        [STUFieldAttribute(0x74F86711, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_74F86711;

        [STUFieldAttribute(0x95A1A656, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_95A1A656;

        [STUFieldAttribute(0xE2A696C0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E2A696C0;

        [STUFieldAttribute(0x1CB0801B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1CB0801B;

        [STUFieldAttribute(0xD469BB7F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D469BB7F;

        [STUFieldAttribute(0x7ED72B91, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7ED72B91;

        [STUFieldAttribute(0x5DDC3711, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5DDC3711;

        [STUFieldAttribute(0xCCA87998, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_CCA87998;

        [STUFieldAttribute(0x978D2DA1)]
        public Enum_A989B3A1 m_978D2DA1;

        [STUFieldAttribute(0x68CEF10F)]
        public Enum_8B290AC4 m_68CEF10F;
    }
}
