// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3C997D56, "STUStatescriptSchemaEntry")]
    public class STUStatescriptSchemaEntry : STUInstance {
        [STUFieldAttribute(0x4F6799B5)]
        public teStructuredDataAssetRef<STUIdentifier> m_4F6799B5;

        [STUFieldAttribute(0x5180E750, "m_value", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_value;
    }
}
