// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xCDA846FE, "STUStatescriptDeflectProjectileBox")]
    public class STUStatescriptDeflectProjectileBox : STUInstance {
        [STUFieldAttribute(0xB594082E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B594082E;

        [STUFieldAttribute(0x2C9D5994, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2C9D5994;
    }
}
