// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x67471C66, "STUStatescriptStateDeflectProjectiles")]
    public class STUStatescriptStateDeflectProjectiles : STUStatescriptState {
        [STUFieldAttribute(0x81060D8D, "m_boxes", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUStatescriptDeflectProjectileBox[] m_boxes;

        [STUFieldAttribute(0x08F9CB86, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarFilter m_08F9CB86;

        [STUFieldAttribute(0x00454CC6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_00454CC6;

        [STUFieldAttribute(0x3C48739F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3C48739F;

        [STUFieldAttribute(0xA8A412C8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A8A412C8;

        [STUFieldAttribute(0xD6BFCE3F, "m_deflectorEntity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_deflectorEntity;

        [STUFieldAttribute(0x35570DE3, "m_filter", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarFilter m_filter;

        [STUFieldAttribute(0x8D177DBA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_8D177DBA;

        [STUFieldAttribute(0xCF120A8F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_CF120A8F;

        [STUFieldAttribute(0xA794A473, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_A794A473;

        [STUFieldAttribute(0x64759FD1, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_64759FD1;

        [STUFieldAttribute(0x61768D14, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_61768D14;

        [STUFieldAttribute(0x16E7E1C6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_496BF68C m_16E7E1C6;

        [STUFieldAttribute(0x70AF54E6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_70AF54E6;

        [STUFieldAttribute(0xEF073057, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EF073057;

        [STUFieldAttribute(0x56532D66, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_56532D66;

        [STUFieldAttribute(0x9D927EAE, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9D927EAE;

        [STUFieldAttribute(0xA19F41F7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A19F41F7;

        [STUFieldAttribute(0xD05ADFA5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D05ADFA5;

        [STUFieldAttribute(0xEC57E0FC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EC57E0FC;

        [STUFieldAttribute(0xECDC6FD3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_ECDC6FD3;

        [STUFieldAttribute(0x4DE15273)]
        public byte m_4DE15273;

        [STUFieldAttribute(0x13CBBA73)]
        public byte m_13CBBA73;

        [STUFieldAttribute(0xFCB972E3)]
        public byte m_FCB972E3;

        [STUFieldAttribute(0xA6260FE4)]
        public byte m_A6260FE4;

        [STUFieldAttribute(0x94106D66)]
        public byte m_94106D66;
    }
}
