// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD6AFF88F, "STUStatescriptStateUXHealth")]
    public class STUStatescriptStateUXHealth : STUStatescriptStateUXPresenter {
        [STUFieldAttribute(0xA5E0221B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A5E0221B;
    }
}
