// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x87A2EDD1, "STUStatescriptStateSequencer")]
    public class STUStatescriptStateSequencer : STUStatescriptState {
        [STUFieldAttribute(0xEB2A1736, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug[] m_EB2A1736;

        [STUFieldAttribute(0x3FF027CF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_3FF027CF;

        [STUFieldAttribute(0x69B11538, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_69B11538;

        [STUFieldAttribute(0x41BA609A, "m_onAbortPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onAbortPlug;

        [STUFieldAttribute(0xFE841C79, "m_onFinishedPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onFinishedPlug;
    }
}
