// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7DDBB13B, "STUSoundSpace")]
    public class STUSoundSpace : STUInstance {
        [STUFieldAttribute(0x70FF13D4)]
        public teStructuredDataAssetRef<STUSound> m_70FF13D4;

        [STUFieldAttribute(0x71273263, "m_soundState")]
        public teStructuredDataAssetRef<STUSoundState> m_soundState;

        [STUFieldAttribute(0x91EFE48E, "m_soundSwitch")]
        public teStructuredDataAssetRef<STUSoundSwitch> m_soundSwitch;

        [STUFieldAttribute(0x77577A15)]
        public teStructuredDataAssetRef<STU_4A97B10D> m_77577A15;

        [STUFieldAttribute(0x2F7ADEB2)]
        public teStructuredDataAssetRef<STU_4A97B10D> m_2F7ADEB2;

        [STUFieldAttribute(0x7DCD1027)]
        public float m_7DCD1027;

        [STUFieldAttribute(0x48BB6EE2)]
        public float m_48BB6EE2;

        [STUFieldAttribute(0xF5548641)]
        public float m_F5548641;

        [STUFieldAttribute(0x1B96F84A)]
        public float m_1B96F84A;
    }
}
