// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x860EE5FC, "STUStatescriptStateWeaponVolley")]
    public class STUStatescriptStateWeaponVolley : STUStatescriptState {
        [STUFieldAttribute(0xB5D34136, "m_projectileMotions", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptWeaponProjectileMotion[] m_projectileMotions;

        [STUFieldAttribute(0xF7329268, "m_projectileEntity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptWeaponProjectileEntity m_projectileEntity;

        [STUFieldAttribute(0x12D35E1F, "m_projectileVisual", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptWeaponProjectileVisual m_projectileVisual;

        [STUFieldAttribute(0xD64683D1, "m_aimID", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_aimID;

        [STUFieldAttribute(0x5257BE73, "m_projectileLifetime", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_projectileLifetime;

        [STUFieldAttribute(0x308E35D5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_308E35D5;

        [STUFieldAttribute(0x4F7EBB93, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptWeaponProjectileRicochet m_4F7EBB93;

        [STUFieldAttribute(0xAC2F916A, "m_projectileSpeed", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_projectileSpeed;

        [STUFieldAttribute(0x6A53F8C7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptWeaponProjectileSticky m_6A53F8C7;

        [STUFieldAttribute(0xD789B6CA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptWeaponProjectileSettle m_D789B6CA;

        [STUFieldAttribute(0x93F49971, "m_raycastType", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_raycastType;

        [STUFieldAttribute(0x5B97FA06, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptWeaponProjectileExplosion m_5B97FA06;

        [STUFieldAttribute(0x3D131607, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptWeaponProjectileImpact m_3D131607;

        [STUFieldAttribute(0x3307A07B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptWeaponProjectileSpawn m_3307A07B;

        [STUFieldAttribute(0x3AC99059, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_07E34E24 m_3AC99059;

        [STUFieldAttribute(0xA4E081C9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A4E081C9;

        [STUFieldAttribute(0x472BEC0C, "m_numProjectilesPerShot", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_numProjectilesPerShot;

        [STUFieldAttribute(0x120FD2F8, "m_numShotsPerSecond", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_numShotsPerSecond;

        [STUFieldAttribute(0x64389377, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_64389377;

        [STUFieldAttribute(0xA835E878, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A835E878;

        [STUFieldAttribute(0x8BC9D90B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_312E3316 m_8BC9D90B;

        [STUFieldAttribute(0x764A8EC7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_F9AE352D m_764A8EC7;

        [STUFieldAttribute(0x203488D6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_203488D6;

        [STUFieldAttribute(0x80AD81F5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptWeaponVolleyLaunch m_80AD81F5;

        [STUFieldAttribute(0x08D03DB7, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_08D03DB7;

        [STUFieldAttribute(0x39D89271, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_39D89271;

        [STUFieldAttribute(0xA2A6D6A4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_A2A6D6A4;

        [STUFieldAttribute(0x663CE7E5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_663CE7E5;

        [STUFieldAttribute(0x2CCAFFB8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_2CCAFFB8;

        [STUFieldAttribute(0x48C4F9C7, "m_onMinShotsPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onMinShotsPlug;

        [STUFieldAttribute(0x41BA609A, "m_onAbortPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onAbortPlug;

        [STUFieldAttribute(0xFE841C79, "m_onFinishedPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onFinishedPlug;

        [STUFieldAttribute(0xB3276522)]
        public Enum_6F445C05 m_B3276522;

        [STUFieldAttribute(0xBC36E891)]
        public byte m_BC36E891;
    }
}
