// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x74CB0002, "STUStatescriptStatePossessControl")]
    public class STUStatescriptStatePossessControl : STUStatescriptState {
        [STUFieldAttribute(0x33073533, "m_possessor", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_possessor;

        [STUFieldAttribute(0x743B15A6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_743B15A6;

        [STUFieldAttribute(0x54D710EB)]
        public byte m_54D710EB;
    }
}
