// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC739BAAC, "STUStatescriptStateUXScreen")]
    public class STUStatescriptStateUXScreen : STUStatescriptStateUXBase {
    }
}
