// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x181FD429, "STUStatescriptActionMovementModOp")]
    public class STUStatescriptActionMovementModOp : STUInstance {
        [STUFieldAttribute(0x6DFC6A5F, "m_priority", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_priority;
    }
}
