// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE091159D, "STUStat")]
    public class STUStat : STUInstance {
        [STUFieldAttribute(0xC08C4427, "m_name")]
        public teStructuredDataAssetRef<ulong> m_name;

        [STUFieldAttribute(0xB4AFBBA6, "m_formatString")]
        public teStructuredDataAssetRef<ulong> m_formatString;

        [STUFieldAttribute(0xA546E9FE)]
        public teStructuredDataAssetRef<STU_4683D781>[] m_A546E9FE;

        [STUFieldAttribute(0x1D1FDD39, "m_heroes")]
        public teStructuredDataAssetRef<STUHero>[] m_heroes;

        [STUFieldAttribute(0xD9813284, "m_maps")]
        public teStructuredDataAssetRef<STUMap>[] m_maps;

        [STUFieldAttribute(0xDA359D3C, "m_teams")]
        public TeamIndex[] m_teams;

        [STUFieldAttribute(0x5D71EE31, "m_numeratorStat")]
        public teStructuredDataAssetRef<STUStat> m_numeratorStat;

        [STUFieldAttribute(0xDDD19A1F, "m_denominatorStat")]
        public teStructuredDataAssetRef<STUStat> m_denominatorStat;

        [STUFieldAttribute(0xCFF73168, "m_statClass", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_01B57CB8 m_statClass;

        [STUFieldAttribute(0x76236DBA, "m_displayType")]
        public Enum_98DA606A m_displayType;

        [STUFieldAttribute(0x294D2DBB, "m_statCategory")]
        public Enum_79C109B1 m_statCategory;

        [STUFieldAttribute(0x0FE078EA)]
        public Enum_1791D3C1 m_0FE078EA;

        [STUFieldAttribute(0x12716D08, "m_type")]
        public STUStatType m_type;

        [STUFieldAttribute(0xD336D9AD)]
        public Enum_245A25AF m_D336D9AD;

        [STUFieldAttribute(0xCC916787)]
        public Enum_C23A3813 m_CC916787;

        [STUFieldAttribute(0x1BB1E643)]
        public Enum_151AB9D7 m_1BB1E643;

        [STUFieldAttribute(0xA752A2BC)]
        public Enum_4E71875B m_A752A2BC;

        [STUFieldAttribute(0x70AB87EA, "m_primaryEvent")]
        public Enum_D7506F80 m_primaryEvent;

        [STUFieldAttribute(0x6725A40E, "m_secondaryEvent")]
        public Enum_D7506F80 m_secondaryEvent;

        [STUFieldAttribute(0x2AF02426)]
        public Enum_DD9CD824 m_2AF02426;

        [STUFieldAttribute(0x149D84C1)]
        public Enum_644A22C9 m_149D84C1;

        [STUFieldAttribute(0x07DFC2EF)]
        public Enum_09749D7B m_07DFC2EF;

        [STUFieldAttribute(0xF16265F5, "m_internalOnly")]
        public byte m_internalOnly;

        [STUFieldAttribute(0x4CA363ED)]
        public byte m_4CA363ED;

        [STUFieldAttribute(0x3949E6E6)]
        public byte m_3949E6E6;

        [STUFieldAttribute(0x74B9C9DA, "m_derivedStat")]
        public byte m_derivedStat;
    }
}
