// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4F67103D, "STUStatescriptActionBeamEffect")]
    public class STUStatescriptActionBeamEffect : STUStatescriptAction {
        [STUFieldAttribute(0x140A2F9C, "m_beamEffect", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_beamEffect;

        [STUFieldAttribute(0x4667A64E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_4667A64E;

        [STUFieldAttribute(0x1E4A0A7D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1E4A0A7D;

        [STUFieldAttribute(0xD0D2C5EA, "m_sourceHardpoint", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_sourceHardpoint;

        [STUFieldAttribute(0xF5895FED, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F5895FED;

        [STUFieldAttribute(0xD18F0A24, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D18F0A24;

        [STUFieldAttribute(0xF769DDB3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F769DDB3;

        [STUFieldAttribute(0x1061008B, "m_destinationHardpoint", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_destinationHardpoint;

        [STUFieldAttribute(0xAF5E3D3E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_AF5E3D3E;

        [STUFieldAttribute(0x38DB5A68)]
        public Enum_02753E5D m_38DB5A68;

        [STUFieldAttribute(0x8ADE9E40)]
        public byte m_8ADE9E40;
    }
}
