// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE0309618, "STUStatescriptStateUXProgression")]
    public class STUStatescriptStateUXProgression : STUStatescriptStateUXBase {
        [STUFieldAttribute(0x338887E8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_338887E8;

        [STUFieldAttribute(0x133F139C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_133F139C;

        [STUFieldAttribute(0xF5CE9879, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F5CE9879;

        [STUFieldAttribute(0x239AA437, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_239AA437;
    }
}
