// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x01D127EC, "STUStatescriptStateCounter")]
    public class STUStatescriptStateCounter : STUStatescriptState {
        [STUFieldAttribute(0xCC3DCC5A, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_CC3DCC5A;

        [STUFieldAttribute(0xC46A0B04, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C46A0B04;

        [STUFieldAttribute(0x170E6D20, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_170E6D20;

        [STUFieldAttribute(0x52C3D7B4, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_52C3D7B4;

        [STUFieldAttribute(0xAD62BF18, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_AD62BF18;

        [STUFieldAttribute(0xF1FD455C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F1FD455C;

        [STUFieldAttribute(0xC268DD22, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_C268DD22;

        [STUFieldAttribute(0x6F779E5E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_6F779E5E;

        [STUFieldAttribute(0xCCB64F5B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_CCB64F5B;

        [STUFieldAttribute(0x0BE0A889, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_0BE0A889;

        [STUFieldAttribute(0xE5F7B879, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_E5F7B879;

        [STUFieldAttribute(0x0A721709, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_0A721709;

        [STUFieldAttribute(0x41BA609A, "m_onAbortPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onAbortPlug;

        [STUFieldAttribute(0xFE841C79, "m_onFinishedPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onFinishedPlug;
    }
}
