// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x65F158DA, "STUStatescriptStateWait")]
    public class STUStatescriptStateWait : STUStatescriptState {
        [STUFieldAttribute(0xDB0E39DB, "m_timeout", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_timeout;

        [STUFieldAttribute(0x41BA609A, "m_onAbortPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onAbortPlug;

        [STUFieldAttribute(0xFE841C79, "m_onFinishedPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onFinishedPlug;

        [STUFieldAttribute(0x1BFF3867)]
        public byte m_1BFF3867;

        [STUFieldAttribute(0xC5A427FA)]
        public byte m_C5A427FA;
    }
}
