// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x1404DDF3, "STUSkinMaterial")]
    public class STUSkinMaterial : STUMaterialType {
        [STUFieldAttribute(0x950CDF36, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_EE22C9E5 m_950CDF36;

        [STUFieldAttribute(0x24BF30B9, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_F189210D m_24BF30B9;
    }
}
