// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE880F3C4, "STUSpawnComponent")]
    public class STUSpawnComponent : STUMirroredEntityComponent {
    }
}
