// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x2ECEFC8B, "STUStatescriptAction")]
    public class STUStatescriptAction : STUStatescriptActionTerminator {
        [STUFieldAttribute(0x460C9ED6, "m_outPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_outPlug;
    }
}
