// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7331CB24, "STUStatescriptStateInvisible")]
    public class STUStatescriptStateInvisible : STUStatescriptState {
        [STUFieldAttribute(0x5C2EBBD3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_5C2EBBD3;

        [STUFieldAttribute(0x13313C89, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_13313C89;

        [STUFieldAttribute(0xA2867F52, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A2867F52;

        [STUFieldAttribute(0xA6B05CE1, "m_hideModel", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_hideModel;

        [STUFieldAttribute(0x7A2FCE43, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_7A2FCE43;

        [STUFieldAttribute(0xE9E2290E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_E9E2290E;

        [STUFieldAttribute(0xF8A94689, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F8A94689;
    }
}
