// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE10CB86B, "STUStatescriptComponentInstanceData")]
    public class STUStatescriptComponentInstanceData : STUComponentInstanceData {
        [STUFieldAttribute(0x9719B746, "m_graphOverrides", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUStatescriptGraphWithOverrides[] m_graphOverrides;

        [STUFieldAttribute(0x4FE8EAB6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptSchema m_4FE8EAB6;
    }
}
