// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF12B5025, "STUSkeleton")]
    public class STUSkeleton : STUInstance {
        [STUFieldAttribute(0x55E4C0B6)]
        public teStructuredDataAssetRef<STU_A57C2818> m_55E4C0B6;

        [STUFieldAttribute(0x6D30C8EE)]
        public teString m_6D30C8EE;

        [STUFieldAttribute(0x4BB85F35, "m_sourceSet")]
        public teString m_sourceSet;
    }
}
