// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9B38211B, "STUStatescriptComponent")]
    public class STUStatescriptComponent : STUMirroredEntityComponent {
        [STUFieldAttribute(0x0175AD85, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUStatescriptGraphWithOverrides[] m_0175AD85;

        [STUFieldAttribute(0x4FE8EAB6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptSchema m_4FE8EAB6;

        [STUFieldAttribute(0x4FF25313, "m_clientOnly")]
        public byte m_clientOnly;
    }
}
