// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x84D05911, "STUStatescriptWeaponProjectileEntity")]
    public class STUStatescriptWeaponProjectileEntity : STUInstance {
        [STUFieldAttribute(0x98E1D459)]
        public teStructuredDataAssetRef<STUEntityDefinition>[] m_98E1D459;

        [STUFieldAttribute(0xB571FAB4, "m_entityDef", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entityDef;

        [STUFieldAttribute(0x48B39E49)]
        public byte m_48B39E49;
    }
}
