// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3A846155, "STUStatescriptStatePossessView")]
    public class STUStatescriptStatePossessView : STUStatescriptState {
        [STUFieldAttribute(0x33073533, "m_possessor", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_possessor;

        [STUFieldAttribute(0xD7148C41, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D7148C41;
    }
}
