// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB1001DCF, "STUStatescriptStatePhaseOut")]
    public class STUStatescriptStatePhaseOut : STUStatescriptState {
        [STUFieldAttribute(0x12716D08, "m_type")]
        public STUPhaseOutType m_type;
    }
}
