// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8D50485A, "STUStatescriptStateShockwave")]
    public class STUStatescriptStateShockwave : STUStatescriptState {
        [STUFieldAttribute(0x43D14192, "m_speed", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_speed;

        [STUFieldAttribute(0x13C82CF9, "m_distance", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_distance;

        [STUFieldAttribute(0x23DAE9A9, "m_posEntity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_posEntity;

        [STUFieldAttribute(0x74F86711, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_74F86711;

        [STUFieldAttribute(0xF6B861B5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F6B861B5;

        [STUFieldAttribute(0x9D812041, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9D812041;

        [STUFieldAttribute(0xF8C29D41, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F8C29D41;

        [STUFieldAttribute(0x08F9CB86, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarFilter m_08F9CB86;

        [STUFieldAttribute(0x35570DE3, "m_filter", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarFilter m_filter;

        [STUFieldAttribute(0xC86EA723, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_C86EA723;

        [STUFieldAttribute(0x170A891D, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_170A891D;

        [STUFieldAttribute(0x37072941, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_37072941;

        [STUFieldAttribute(0x1B8C7DD8, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1B8C7DD8;

        [STUFieldAttribute(0xFCF3C30C, "m_effect", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_effect;

        [STUFieldAttribute(0xA2102FBB, "m_contactSet", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_contactSet;

        [STUFieldAttribute(0x582D9F8F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_582D9F8F;

        [STUFieldAttribute(0x93E60229, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_93E60229;

        [STUFieldAttribute(0x41BA609A, "m_onAbortPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onAbortPlug;

        [STUFieldAttribute(0xFE841C79, "m_onFinishedPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onFinishedPlug;

        [STUFieldAttribute(0x5E4A73DE)]
        public Enum_4CD3930F m_5E4A73DE;

        [STUFieldAttribute(0x854CD6B8)]
        public byte m_854CD6B8;

        [STUFieldAttribute(0xC7293391)]
        public byte m_C7293391;
    }
}
