// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x0897C6FB, "STUSoundFilter")]
    public class STUSoundFilter : STUInstance {
        [STUFieldAttribute(0xC08C4427, "m_name")]
        public teString m_name;
    }
}
