// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3E490486, "STUStatescriptOutputPlug")]
    public class STUStatescriptOutputPlug : STUGraphPlug {
    }
}
