// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA39020FE, "STUSoundIntegrity")]
    public class STUSoundIntegrity : STUInstance {
        [STUFieldAttribute(0x8B15975C)]
        public byte[] m_8B15975C;

        [STUFieldAttribute(0x790363EB)]
        public byte[] m_790363EB;

        [STUFieldAttribute(0x35C00F0E)]
        public byte[] m_35C00F0E;
    }
}
