// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFA0FEC4F, "STUStatescriptStateUnkillable")]
    public class STUStatescriptStateUnkillable : STUStatescriptState {
        [STUFieldAttribute(0x0CFC7D02, "m_target", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_target;
    }
}
