// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x6A2C0D5F, "STUStatescriptHistoryVar")]
    public class STUStatescriptHistoryVar : STUInstance {
        [STUFieldAttribute(0xEC9F34A6, "m_out_Var", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_out_Var;

        [STUFieldAttribute(0x4CD99B2F)]
        public Enum_9E6E42F3 m_4CD99B2F;
    }
}
