// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8DE7E50F, "STUStatescriptStateTrackMovement")]
    public class STUStatescriptStateTrackMovement : STUStatescriptState {
        [STUFieldAttribute(0x44BB1696, "m_entity", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_entity;

        [STUFieldAttribute(0x6523E4F2, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_6523E4F2;

        [STUFieldAttribute(0x979AB3CB, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_979AB3CB;

        [STUFieldAttribute(0xE27094E0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_E27094E0;

        [STUFieldAttribute(0x8134E047, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_8134E047;

        [STUFieldAttribute(0xDF4AF27F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_DF4AF27F;

        [STUFieldAttribute(0x7BB19AE0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_7BB19AE0;

        [STUFieldAttribute(0x761CAF1E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_761CAF1E;

        [STUFieldAttribute(0x964174F9, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_964174F9;

        [STUFieldAttribute(0x68B1EC07, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_68B1EC07;

        [STUFieldAttribute(0x6FC2458E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_6FC2458E;

        [STUFieldAttribute(0xFE68FBAA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_FE68FBAA;

        [STUFieldAttribute(0x000946A5, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_000946A5;

        [STUFieldAttribute(0x5B60E813, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_5B60E813;
    }
}
