// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xBE49A4C2, "STUStatescriptEntryGameMessage")]
    public class STUStatescriptEntryGameMessage : STUStatescriptEntry {
        [STUFieldAttribute(0xC55D5C0D, "m_params", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_C679B01F[] m_params;

        [STUFieldAttribute(0x5178F207, "m_gameMessage", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarGameMessage m_gameMessage;

        [STUFieldAttribute(0xAFF3B654, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_AFF3B654;

        [STUFieldAttribute(0xBC77119F, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_BC77119F;

        [STUFieldAttribute(0xA6152623, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_A6152623;

        [STUFieldAttribute(0x35570DE3, "m_filter", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarFilter m_filter;

        [STUFieldAttribute(0xEB7F6AB1)]
        public byte m_EB7F6AB1;
    }
}
