// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xB1C3AA7F, "STUSoundBankDataVersion")]
    public class STUSoundBankDataVersion : STUInstance {
        [STUFieldAttribute(0x81386F9F)]
        public teString m_81386F9F;

        [STUFieldAttribute(0x6105DA5C, "m_soundBank")]
        public teStructuredDataAssetRef<STUSoundBank> m_soundBank;

        [STUFieldAttribute(0x0F36E281, "m_soundWEMFiles")]
        public teStructuredDataAssetRef<STUSoundWEMFile>[] m_soundWEMFiles;

        [STUFieldAttribute(0x7EC6FE2A, "m_soundWEMStreams")]
        public teStructuredDataAssetRef<STUSoundWEMFile>[] m_soundWEMStreams;

        [STUFieldAttribute(0x567AF4DE, "m_wwiseWEMFileIDs")]
        public uint[] m_wwiseWEMFileIDs;

        [STUFieldAttribute(0x46EEF28E, "m_wwiseWEMStreamIDs")]
        public uint[] m_wwiseWEMStreamIDs;

        [STUFieldAttribute(0x1D0A3932)]
        public teString m_1D0A3932;

        [STUFieldAttribute(0xBDF1BA05)]
        public teStructuredDataAssetRef<STU_44C43EAC>[] m_BDF1BA05;

        [STUFieldAttribute(0x88759815)]
        public teStructuredDataAssetRef<STU_5665FB75>[] m_88759815;

        [STUFieldAttribute(0xD6ABC2C6)]
        public teStructuredDataAssetRef<STU_0BD00006>[] m_D6ABC2C6;

        [STUFieldAttribute(0x40AC0372)]
        public uint m_40AC0372;

        [STUFieldAttribute(0x7B2BA5DB)]
        public float m_7B2BA5DB;

        [STUFieldAttribute(0xF88A210D, "m_wwiseEventIDPlay")]
        public uint m_wwiseEventIDPlay;

        [STUFieldAttribute(0x1F55E901, "m_wwiseEventIDStop")]
        public uint m_wwiseEventIDStop;

        [STUFieldAttribute(0xEE2F5ACA)]
        public byte m_EE2F5ACA;
    }
}
