// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xD78490D1, "STUStatescriptStateApplyAura")]
    public class STUStatescriptStateApplyAura : STUStatescriptState {
        [STUFieldAttribute(0xC55D5C0D, "m_params", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_A51F99C5[] m_params;

        [STUFieldAttribute(0x49F7955A, "m_aura", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_aura;

        [STUFieldAttribute(0xF50C525A, "m_targets", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_targets;

        [STUFieldAttribute(0xB9607AFA, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B9607AFA;
    }
}
