// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x20A736E0, "STUStatescriptStateBridge")]
    public class STUStatescriptStateBridge : STUStatescriptState {
        [STUFieldAttribute(0x59C48F73, "m_inPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_8DCB62EA m_inPlug;

        [STUFieldAttribute(0x460C9ED6, "m_outPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_outPlug;
    }
}
