// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xF91C284F, "STUStatescriptWeaponProjectileExplosionRing")]
    public class STUStatescriptWeaponProjectileExplosionRing : STUInstance {
        [STUFieldAttribute(0x71EF3CA4, "m_radius", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_radius;

        [STUFieldAttribute(0xF2625472, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_F2625472;
    }
}
