// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x5C4B3874, "STUSoundSwitchGroup")]
    public class STUSoundSwitchGroup : STUInstance {
        [STUFieldAttribute(0xCE0B2C3D)]
        public teString m_CE0B2C3D;

        [STUFieldAttribute(0x1C0E5260)]
        public uint m_1C0E5260;
    }
}
