// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x53490C27, "STUSimpleMaterial")]
    public class STUSimpleMaterial : STUMaterialType {
        [STUFieldAttribute(0x525CF57C, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_66305D57 m_525CF57C;

        [STUFieldAttribute(0x24BF30B9, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_F189210D m_24BF30B9;

        [STUFieldAttribute(0x581598A7, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_520110FD m_581598A7;
    }
}
