// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC25082A2, "STUSkin")]
    public class STUSkin : STUSkinBase {
        [STUFieldAttribute(0x0CD16BAA)]
        public teStructuredDataAssetRef<ulong> m_0CD16BAA;

        [STUFieldAttribute(0x4F9828A3, "m_internalName")]
        public teString m_internalName;

        [STUFieldAttribute(0x9EBE9F47, "m_skinCode")]
        public teString m_skinCode;

        [STUFieldAttribute(0x558BBCDC, "m_skinThemes")]
        public teStructuredDataAssetRef<STUSkinTheme>[] m_skinThemes;

        [STUFieldAttribute(0x876B3D19, "m_skinThumbnail")]
        public teStructuredDataAssetRef<ulong> m_skinThumbnail;

        [STUFieldAttribute(0xA6459408, "m_skinEffects")]
        public teStructuredDataAssetRef<STUEffect>[] m_skinEffects;

        [STUFieldAttribute(0x06207B8F, "m_resourceKey")]
        public teStructuredDataAssetRef<STUResourceKey> m_resourceKey;

        [STUFieldAttribute(0x5C415784)]
        public teString m_5C415784;

        [STUFieldAttribute(0xD62F1F9F)]
        public byte m_D62F1F9F;
    }
}
