// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x619D9E95, "STUStatescriptStateModifyHealth")]
    public class STUStatescriptStateModifyHealth : STUStatescriptState {
        [STUFieldAttribute(0xD525B22B, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_D525B22B;

        [STUFieldAttribute(0x89174668, "m_modifyHealth", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptModifyHealth m_modifyHealth;

        [STUFieldAttribute(0xEBDA16F6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EBDA16F6;

        [STUFieldAttribute(0x9CC9F017, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9CC9F017;

        [STUFieldAttribute(0x6CB57812, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_6CB57812;

        [STUFieldAttribute(0xB70D8DDF, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_B70D8DDF;

        [STUFieldAttribute(0xC264695E, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_C264695E;

        [STUFieldAttribute(0xA8AFF195, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A8AFF195;

        [STUFieldAttribute(0x41BA609A, "m_onAbortPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onAbortPlug;

        [STUFieldAttribute(0xFE841C79, "m_onFinishedPlug", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_onFinishedPlug;

        [STUFieldAttribute(0x8004B1BD)]
        public Enum_8FD4F070 m_8004B1BD;

        [STUFieldAttribute(0x83377B7D)]
        public byte m_83377B7D;

        [STUFieldAttribute(0x73ABFB05)]
        public byte m_73ABFB05;
    }
}
