// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x985BCC76, "STUStatescriptStateDeflectProjectilesEffects")]
    public class STUStatescriptStateDeflectProjectilesEffects : STUStatescriptState {
        [STUFieldAttribute(0xEA946900, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EA946900;

        [STUFieldAttribute(0xECDC6FD3, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUStatescriptOutputPlug m_ECDC6FD3;

        [STUFieldAttribute(0x0196550C, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_0196550C;

        [STUFieldAttribute(0x1DBD2323, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_1DBD2323;
    }
}
