// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xC17B255D, "STUStatescriptStateHealthPool")]
    public class STUStatescriptStateHealthPool : STUStatescriptState {
        [STUFieldAttribute(0xEBDA16F6, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_EBDA16F6;

        [STUFieldAttribute(0x1BB6C936, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_1BB6C936;

        [STUFieldAttribute(0xC43222BC, "m_amount", ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_amount;

        [STUFieldAttribute(0xFE8B4208, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_FE8B4208;

        [STUFieldAttribute(0x9D2BE4AC, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_9D2BE4AC;

        [STUFieldAttribute(0xEFD1F791, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_EFD1F791;

        [STUFieldAttribute(0xD38FD608, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVarDynamic m_D38FD608;

        [STUFieldAttribute(0x2C27D174, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_2C27D174;

        [STUFieldAttribute(0xA8AFF195, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STUConfigVar m_A8AFF195;

        [STUFieldAttribute(0x36967FDE)]
        public Enum_F37295C3 m_36967FDE;
    }
}
