// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7113C69A, "STUTargetTagInstanceData")]
    public class STUTargetTagInstanceData : STUComponentInstanceData {
        [STUFieldAttribute(0x28234534, "m_targetTags")]
        public teStructuredDataAssetRef<STUTargetTag>[] m_targetTags;

        [STUFieldAttribute(0x493B0749)]
        public teUUID m_493B0749;
    }
}
