// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xEA8118E2, "STUTextureSource")]
    public class STUTextureSource : STUInstance {
        [STUFieldAttribute(0x15192D8D, "m_source")]
        public teStructuredDataAssetRef<STUEmptyAsset> m_source;

        [STUFieldAttribute(0x48D144DF)]
        public teStructuredDataAssetRef<STUEmptyAsset> m_48D144DF;

        [STUFieldAttribute(0x9CE0F03C)]
        public teString m_9CE0F03C;

        [STUFieldAttribute(0xC719E7D2)]
        public byte m_C719E7D2;
    }
}
