// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xE2F14378, "STUUnsynchronizedMoverComponentInstanceData")]
    public class STUUnsynchronizedMoverComponentInstanceData : STUComponentInstanceData {
        [STUFieldAttribute(0x7ECF87C0, ReaderType = typeof(EmbeddedInstanceFieldReader))]
        public STU_EADEEDEF m_7ECF87C0;
    }
}
