// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x4EE84DC0, "STUUnlock_POTGAnimation")]
    public class STUUnlock_POTGAnimation : STUUnlock {
        [STUFieldAttribute(0xD3832764, "m_animation")]
        public teStructuredDataAssetRef<STUAnimation> m_animation;

        [STUFieldAttribute(0x12716D08, "m_type")]
        public Enum_A2B71E4A m_type;
    }
}
