// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x018667E2, "STUUnlock_Pose")]
    public class STUUnlock_Pose : STUUnlock {
        [STUFieldAttribute(0xAE95765E, "m_pose")]
        public teStructuredDataAssetRef<ulong> m_pose;
    }
}
