// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x8CDAA871, "STUUnlock_AvatarPortrait")]
    public class STUUnlock_AvatarPortrait : STUUnlock {
        [STUFieldAttribute(0x5DD25DBA, ReaderType = typeof(InlineInstanceFieldReader))]
        public STUUnlock_SprayPaintEffect m_5DD25DBA;
    }
}
