// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x7979C642, "STUUnlock_Trophy")]
    public class STUUnlock_Trophy : STUUnlock {
    }
}
