// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xAD81A809, "STUVoiceStimulusHeader")]
    public class STUVoiceStimulusHeader : STUInstance {
        [STUFieldAttribute(0x74679F65)]
        public ulong m_74679F65;

        [STUFieldAttribute(0x5C70B989)]
        public float m_5C70B989;

        [STUFieldAttribute(0x607D86D0)]
        public float m_607D86D0;

        [STUFieldAttribute(0xC6D114F6)]
        public byte m_C6D114F6;
    }
}
