// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.STU.Types.Enums;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xDCFD6BF4, "STUVoiceCategory")]
    public class STUVoiceCategory : STUInstance {
        [STUFieldAttribute(0xEEC0EC6B)]
        public uint m_EEC0EC6B;

        [STUFieldAttribute(0xB9DE2CFC)]
        public Enum_342B7F97 m_B9DE2CFC;

        [STUFieldAttribute(0x9826F802)]
        public byte m_9826F802;
    }
}
