// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xA1403E11, "STUVegetationMaterial")]
    public class STUVegetationMaterial : STUMaterialType {
        [STUFieldAttribute(0x9F5603CA, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_16EEE3AD m_9F5603CA;

        [STUFieldAttribute(0x24BF30B9, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_F189210D m_24BF30B9;
    }
}
