// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x3275DB08, "STUWaterMaterial")]
    public class STUWaterMaterial : STUMaterialType {
        [STUFieldAttribute(0x665D7785, ReaderType = typeof(InlineInstanceFieldReader))]
        public STU_5FE1E9BB m_665D7785;
    }
}
