// Instance generated by TankLibHelper.InstanceBuilder
using TankLib.Math;

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0xFA0FB365, "STUWaypointInstanceData")]
    public class STUWaypointInstanceData : STUComponentInstanceData {
        [STUFieldAttribute(0x27E34379)]
        public teVec3A m_27E34379;

        [STUFieldAttribute(0xBEEA12C3)]
        public teVec3A m_BEEA12C3;

        [STUFieldAttribute(0xC9ED2255)]
        public teVec3A m_C9ED2255;

        [STUFieldAttribute(0x5789B7F6)]
        public teVec3A m_5789B7F6;

        [STUFieldAttribute(0xEF87565D)]
        public teVec3A m_EF87565D;

        [STUFieldAttribute(0x340FE6F6)]
        public teVec3A m_340FE6F6;

        [STUFieldAttribute(0x2DDA10F0)]
        public teVec3A m_2DDA10F0;

        [STUFieldAttribute(0xBAA931C0)]
        public teUUID m_BAA931C0;

        [STUFieldAttribute(0x24EBFCB4)]
        public teUUID m_24EBFCB4;

        [STUFieldAttribute(0x614DC304)]
        public float m_614DC304;

        [STUFieldAttribute(0x3E9DCD88)]
        public byte m_3E9DCD88;

        [STUFieldAttribute(0x703E256A)]
        public byte m_703E256A;
    }
}
