// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x908FA5B4, "STUWaterType")]
    public class STUWaterType : STUInstance {
    }
}
