// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x378F54CD, "STUWeaponComponent")]
    public class STUWeaponComponent : STUMirroredEntityComponent {
        [STUFieldAttribute(0xA86EA67D)]
        public teStructuredDataAssetRef<STU_D83702BD> m_A86EA67D;

        [STUFieldAttribute(0x0841F7A8, "m_weapons", ReaderType = typeof(InlineInstanceFieldReader))]
        public STUWeaponDefinition[] m_weapons;
    }
}
