// Instance generated by TankLibHelper.InstanceBuilder

// ReSharper disable All
namespace TankLib.STU.Types {
    [STUAttribute(0x9B73837C, "STUWeek")]
    public class STUWeek : STUInstance {
        [STUFieldAttribute(0x95417FF7, "m_monday")]
        public teString m_monday;

        [STUFieldAttribute(0xB652FCB0, "m_tuesday")]
        public teString m_tuesday;

        [STUFieldAttribute(0xCBAFB6C4, "m_wednesday")]
        public teString m_wednesday;

        [STUFieldAttribute(0x41AD24D4, "m_thursday")]
        public teString m_thursday;

        [STUFieldAttribute(0xFA21E4BE, "m_friday")]
        public teString m_friday;

        [STUFieldAttribute(0x1F3000CE, "m_saturday")]
        public teString m_saturday;

        [STUFieldAttribute(0x86CD933F, "m_sunday")]
        public teString m_sunday;
    }
}
