// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0xD61991A8, "STUContactType")]
    public enum STUContactType : uint {
    }
}
