// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0x492FEC63, "STULocale")]
    public enum STULocale : uint {
    }
}
