// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0xB26EE6B7, "STUPhaseOutType")]
    public enum STUPhaseOutType : uint {
    }
}
