// Enum generated by TankLibHelper.EnumBuilder

// ReSharper disable All
namespace TankLib.STU.Types.Enums {
    [STUEnumAttribute(0x0CB7E361, "TeamIndex")]
    public enum TeamIndex : uint {
    }
}
